export const LICENSE_TOOL_PASSWORD = "258258";

export const LICENSE_PRIVATE_KEY = `-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIBdgb3waagHeWOgRLNuJUVxSQNIBHbWVU5iW9m5fr/6x
-----END PRIVATE KEY-----`;
