import { MenuGroup } from "@/types/portal";
import { socialHubPath, socialInboxPath, socialLinkCenterPath, socialModuleCatalog, socialPerformancePath } from "@/lib/social-module-config";

const socialMenuGroup: MenuGroup = {
  title: "Mang xa hoi",
  href: socialHubPath,
  icon: "send",
  items: [
    {
      label: "Trung tam lien ket",
      href: socialLinkCenterPath,
      icon: "link-2",
      description: "Tao phien lien ket tu may tinh, QR / deeplink mobile va browser extension de dung tai khoan dang login san.",
    },
    {
      label: "Trung tam hoi thoai",
      href: socialInboxPath,
      icon: "headset",
      description: "Hang doi hoi thoai, lead can xu ly, SLA va noi dung tuong tac gan nhat.",
    },
    {
      label: "Hieu suat kenh",
      href: socialPerformancePath,
      icon: "bar-chart-3",
      description: "Tong hop hoi thoai, lead chuyen doi, toc do phan hoi va doanh thu ho tro theo kenh.",
    },
    {
      label: "Tong quan kenh",
      href: socialHubPath,
      icon: "waypoints",
      description: "Tong hop tat ca kenh social, messaging, token va tinh trang kich hoat.",
    },
    ...socialModuleCatalog.map((item) => ({
      label: item.menuLabel,
      href: `/social/${item.slug}`,
      icon: item.icon,
      description: item.subtitle,
    })),
  ],
};

export const menuGroups: MenuGroup[] = [
  {
    title: "Tong quan",
    href: "/dashboard",
    icon: "home",
    items: [
      { label: "Dashboard tong quan", href: "/dashboard", icon: "layout-dashboard", description: "Tong hop van hanh, doanh thu va lead theo ngay." },
      { label: "Dashboard KPI ngay / thang", href: "/overview/kpi", icon: "gauge", description: "Theo doi chi tieu KPI va doanh thu nhan vien." },
      { label: "Doanh thu theo chi nhanh", href: "/overview/branch-revenue", icon: "chart-column", description: "Bieu do doanh thu theo chi nhanh va goi dich vu." },
      { label: "Sinh nhat hoi vien", href: "/overview/birthday", icon: "cake", description: "Danh sach sinh nhat sap toi de CSKH chu dong." },
      { label: "Cham soc / lich hen", href: "/overview/follow-up", icon: "calendar-clock", description: "Cong viec follow-up, lich hen va canh bao qua han." },
      { label: "Bao cao Lead", href: "/overview/lead", icon: "user-round-search", description: "Tong hop lead moi, da cham soc va chuyen doi." },
    ],
  },
  {
    title: "Hoi vien",
    href: "/members/customers",
    icon: "users",
    items: [
      { label: "Danh sach hoi vien", href: "/members/customers", icon: "users", description: "Ho so hoi vien, trang thai, nhom va nguon khach." },
      { label: "Ho so Lead", href: "/members/leads", icon: "user-round-plus", description: "Danh sach lead, pipeline va lich hen tu van." },
      { label: "Trang thai hoi vien", href: "/members/status", icon: "badge-check", description: "Theo doi hoi vien dang active, prospect va inactive." },
      { label: "Xac nhan dang tap", href: "/members/presence", icon: "scan-face", description: "Bam vao de xac nhan hoi vien dang tap, off va xu ly qua ngay." },
      { label: "Cong no hoi vien", href: "/members/debt", icon: "wallet-cards", description: "Hop dong con no va gia tri hop dong con lai." },
      { label: "Nhom khach hang", href: "/members/customer-groups", icon: "layers-3", description: "Danh muc phan loai hoi vien theo nhom." },
      { label: "Nguon khach hang", href: "/members/customer-sources", icon: "waypoints", description: "Danh muc nguon khach tu referral, walk-in, social va ads." },
      { label: "Sinh nhat hoi vien", href: "/members/birthday", icon: "cake", description: "Lich nhac chuc mung sinh nhat va uu dai." },
    ],
  },
  {
    title: "Nghiep vu",
    href: "/operations/service-price-book",
    icon: "briefcase-business",
    items: [
      { label: "Bang gia dich vu", href: "/operations/service-price-book", icon: "file-text", description: "Danh sach dich vu, bang gia va goi tap dang ap dung." },
      { label: "Dang ky dich vu", href: "/operations/service-registration", icon: "file-signature", description: "Mo hop dong moi va dang ky goi dich vu cho hoi vien." },
      { label: "Danh sach hop dong", href: "/operations/contracts", icon: "list", description: "Theo doi toan bo hop dong, so buoi va cong no." },
      { label: "Gia han hop dong", href: "/operations/contract-renewal", icon: "refresh-cw", description: "Danh sach hop dong sap het han can gia han." },
      { label: "Nang cap hop dong", href: "/operations/contract-upgrade", icon: "arrow-up-right", description: "Xu ly nang cap goi tap va chenhlech gia tri." },
      { label: "Bao luu hop dong", href: "/operations/contract-freeze", icon: "pause-circle", description: "Theo doi cac hop dong tam dung, bao luu." },
      { label: "Chuyen nhuong hop dong", href: "/operations/contract-transfer", icon: "repeat-2", description: "Lich su chuyen nhuong / doi chu hop dong." },
      { label: "Chuyen chi nhanh", href: "/operations/branch-transfer", icon: "git-branch-plus", description: "Dieu chuyen hoi vien giua cac chi nhanh." },
      { label: "Huy hop dong", href: "/operations/contract-cancel", icon: "ban", description: "Theo doi hop dong da huy / dong." },
      { label: "Chuyen doi hop dong", href: "/operations/contract-conversion", icon: "shuffle", description: "Quy tac quy doi va chuyen doi goi dich vu." },
      { label: "Dang ky HD Loyalty", href: "/operations/loyalty", icon: "gift", description: "Ho so loyalty, uu dai va tich diem khach hang." },
    ],
  },
  {
    title: "Lich PT",
    href: "/pt-schedule/calendar",
    icon: "calendar-days",
    items: [
      { label: "Lich PT", href: "/pt-schedule/calendar", icon: "calendar-days", description: "Lich PT, dat lich, check-in va ket qua buoi tap." },
      { label: "Bao cao Booking", href: "/pt-schedule/booking-report", icon: "chart-column", description: "Tong hop booking PT va ty le hoan thanh." },
      { label: "Lich su Penalty", href: "/pt-schedule/penalty-history", icon: "history", description: "Nhat ky penalty, vi pham va dieu chinh lich." },
    ],
  },
  {
    title: "Lich lop",
    href: "/class-schedule/bookings",
    icon: "calendar-range",
    items: [
      { label: "Danh sach book lich", href: "/class-schedule/bookings", icon: "calendar-check-2", description: "Danh sach dat lich lop / PT nhom theo ngay." },
      { label: "Danh sach lop", href: "/class-schedule/classes", icon: "monitor", description: "Danh muc lop, line va nhom dich vu dang mo." },
      { label: "Lich lop", href: "/class-schedule/timetable", icon: "calendar", description: "Lich van hanh lop va phan bo khung gio." },
      { label: "Lich PT nhom", href: "/class-schedule/group-pt", icon: "users-round", description: "Lich PT nhom, dat cho va suc chua." },
      { label: "Danh muc Line", href: "/class-schedule/line-categories", icon: "list-tree", description: "Danh muc line, khu vuc va phong tap." },
      { label: "Lich Line", href: "/class-schedule/line-schedule", icon: "calendar-cog", description: "Lich line va phan bo theo khu vuc." },
      { label: "So do line / phong", href: "/class-schedule/line-layout", icon: "blocks", description: "So do line, phong tap va suc chua booking." },
      { label: "Booking CSKH", href: "/class-schedule/cskh-booking", icon: "headset", description: "Danh sach booking phat sinh tu CSKH." },
      { label: "Dinh kem Booking", href: "/class-schedule/booking-attachments", icon: "paperclip", description: "Tai lieu, file dinh kem lien quan booking." },
    ],
  },
  {
    title: "Nhan vien",
    href: "/staff/users",
    icon: "badge-plus",
    items: [
      { label: "Nhan vien", href: "/staff/users", icon: "badge-plus", description: "Ho so nhan vien, user login, vai tro va chi nhanh." },
      { label: "Danh muc bai tap", href: "/staff/exercise-library", icon: "dumbbell", description: "Thu vien bai tap, huong dan va ghi chu PT." },
      { label: "Danh sach Stage", href: "/staff/stages", icon: "workflow", description: "Quan ly stage, cap do va lo trinh huan luyen." },
      { label: "Template giao an", href: "/staff/program-templates", icon: "scroll-text", description: "Kho template dung chung cho staff, tam thoi thay cho module giao an mau." },
      { label: "Giao an", href: "/staff/programs", icon: "book-open-check", description: "Danh sach giao an dang su dung cho hoc vien." },
      { label: "KPI", href: "/staff/kpi", icon: "line-chart", description: "Chi tieu va ket qua KPI theo nhan vien." },
      { label: "Danh sach ca lam", href: "/staff/shifts", icon: "clock-3", description: "Danh muc ca, gio vao/ra, tre, ve som, OT va ca qua dem." },
      { label: "Phan ca nhan vien", href: "/staff/shift-assignments", icon: "calendar-sync", description: "Gan ca co dinh / ca xoay cho nhan vien va theo doi trang thai dang lam." },
      { label: "Dieu chinh cham cong", href: "/staff/attendance-adjustments", icon: "fingerprint", description: "Su kien vao/ra, chinh cong tay va audit lich su sua." },
    ],
  },
  {
    title: "So quy",
    href: "/cashbook/receipts",
    icon: "wallet",
    items: [
      { label: "Phieu thu", href: "/cashbook/receipts", icon: "coins", description: "Thu tien hop dong, the, coc va doanh thu khac." },
      { label: "Phieu chi", href: "/cashbook/expenses", icon: "banknote-arrow-down", description: "Chi phi van hanh, marketing va thanh toan nha cung cap." },
    ],
  },
  {
    title: "Pro Shop",
    href: "/pro-shop/products",
    icon: "shopping-basket",
    items: [
      { label: "San pham", href: "/pro-shop/products", icon: "package-search", description: "Danh muc hang hoa, gia ban va ton kho." },
      { label: "Nhom hang / cap phat", href: "/operations/product-groups", icon: "layers-3", description: "Danh muc nhom hang dung chung cho Pro Shop va khan / vat tu dich vu." },
      { label: "Tu do", href: "/operations/lockers", icon: "grid-2x2", description: "Quan ly tu do, tien coc va lich su su dung." },
      { label: "Thue tu do", href: "/operations/locker-rentals", icon: "key-round", description: "Lap phieu thue tu, gan hoi vien va theo doi tinh trang dang thue." },
      { label: "Khan tap / vat tu", href: "/operations/towels", icon: "package-2", description: "Danh muc khan tap, vat tu va so lieu da ban / thu tien theo luot tu phieu thu." },
      { label: "Phat / tra khan", href: "/operations/towel-issues", icon: "workflow", description: "Theo doi tung luot phat khan, tra khan, mat / hu va dang giat." },
      { label: "Khach hang / NCC", href: "/pro-shop/partners", icon: "contact-round", description: "Khach mua hang va nha cung cap cho pro shop." },
      { label: "Bang gia", href: "/pro-shop/price-book", icon: "tag", description: "Bang gia ban le va gia uu dai theo san pham." },
      { label: "Ban hang", href: "/pro-shop/sales", icon: "shopping-cart", description: "Phat sinh ban hang, phieu thu va doanh thu shop." },
      { label: "Tra hang", href: "/pro-shop/returns", icon: "rotate-ccw", description: "Danh sach tra hang, hoan tien va dieu chinh ton." },
      { label: "Nhap hang", href: "/pro-shop/purchase-orders", icon: "truck", description: "Phieu nhap hang, NCC va cap nhat ton kho." },
      { label: "So quy", href: "/pro-shop/cashbook", icon: "wallet", description: "Thu chi rieng cho pro shop." },
    ],
  },
  {
    title: "Bao cao",
    href: "/reports/checkin",
    icon: "bar-chart-3",
    items: [
      { label: "Bao cao Checkin", href: "/reports/checkin", icon: "scan-line", description: "Theo doi checkin hoi vien va tan suat den tap." },
      { label: "PT - Training", href: "/reports/pt-training", icon: "dumbbell", description: "Hieu suat PT, lich day va buoi hoan thanh." },
      { label: "Cham cong nhan vien", href: "/reports/staff-attendance", icon: "fingerprint", description: "Cham cong nhan vien, may van tay va ca lam." },
      { label: "Cham cong lop", href: "/reports/class-attendance", icon: "users", description: "Si so lop, checkin lop va tinh trang tham gia." },
      { label: "Bao cao phan bo", href: "/reports/allocation", icon: "git-merge", description: "Phan bo hoc vien, PT va line/phong tap." },
      { label: "Hoat dong kinh doanh", href: "/reports/business-activity", icon: "activity", description: "Tong quan doanh thu, lead va hop dong." },
      { label: "Tong hop Sale goi dich vu", href: "/reports/sales-summary", icon: "pie-chart", description: "Tong hop sale theo goi va nhan vien." },
      { label: "Bieu do", href: "/reports/branch-revenue", icon: "chart-no-axes-combined", description: "Bieu do doanh thu, hoi vien moi va nguon lead." },
      { label: "Cong no", href: "/reports/debt", icon: "wallet-cards", description: "Cong no hoi vien, hop dong va phieu thu." },
      { label: "Tong hop chi nhanh", href: "/reports/branch-summary", icon: "building-2", description: "Thong ke tong hop theo tung chi nhanh." },
      { label: "Hoi vien sap het han", href: "/reports/expiring-members-revenue", icon: "calendar-range", description: "Hoi vien co hop dong het han trong thang va doanh thu da tao truoc ky nay." },
      { label: "Doanh thu theo loai HD", href: "/reports/contract-type-revenue", icon: "repeat", description: "So sanh doanh thu hop dong moi va hop dong gia han." },
      { label: "Doanh thu theo nhom DV", href: "/reports/service-group-revenue", icon: "layers-3", description: "Tong hop doanh thu theo nhom dich vu va tung goi ban." },
      { label: "Incentive Sale", href: "/reports/sales-incentive", icon: "coins", description: "Tinh thuong Sale theo target doanh thu va he so nguon khach." },
      { label: "Incentive PT", href: "/reports/pt-incentive", icon: "gift", description: "Tinh thuong PT theo doanh thu goi PT va bac thuong thang." },
      { label: "Goi tap - qua trinh tap", href: "/reports/package-progress", icon: "list-checks", description: "So buoi da dung, con lai va tien do tap." },
      { label: "Nguon khach hang", href: "/reports/customer-source", icon: "coins", description: "So luong hoi vien va doanh thu theo nguon meta, walk-in, gioi thieu..." },
      { label: "Gia tri HD con lai", href: "/reports/contract-remain", icon: "wallet-minimal", description: "Gia tri goc, da su dung, con lai va cong no." },
      { label: "Bao cao thu chi", href: "/reports/payment", icon: "receipt-text", description: "Thu, chi, loi nhuan tam tinh trong ky." },
      { label: "Bao cao tien coc", href: "/reports/deposit", icon: "shield-dollar-sign", description: "Tien coc dang giu, da tra va qua han." },
      { label: "Bao cao doanh thu the luot", href: "/reports/card-revenue", icon: "credit-card", description: "Doanh thu the luot va phat sinh giao dich." },
      { label: "Bao cao danh gia nhan vien", href: "/reports/staff-review", icon: "star", description: "Tong hop danh gia, KPI va hieu suat nhan vien." },
      { label: "Bao cao trang thai Lead", href: "/reports/lead-status", icon: "user-round-search", description: "Trang thai lead, pipeline va ty le chuyen doi." },
      { label: "Bao cao KPI", href: "/reports/kpi", icon: "gauge", description: "KPI doanh thu, lead va hop dong." },
      { label: "Bao cao Lead", href: "/reports/lead", icon: "users-round", description: "Tong hop lead, nguon lead va nhan vien phu trach." },
      { label: "Hieu suat chat / social", href: "/reports/social-channel-performance", icon: "messages-square", description: "Hoi thoai, lead chuyen doi, toc do phan hoi va doanh thu ho tro theo tung kenh." },
    ],
  },
  {
    title: "Thiet lap",
    href: "/settings/company",
    icon: "settings",
    items: [
      { label: "Thiet lap cong ty", href: "/settings/company", icon: "building", description: "Ten cong ty, logo, timezone va thong tin doanh nghiep." },
      { label: "Nhan dien chuong trinh", href: "/settings/program-branding", icon: "monitor", description: "Doi ten, logo va thong diep hien thi o man dang nhap.", ownerOnly: true },
      { label: "Thiet lap hoa don dien tu", href: "/settings/e-invoice", icon: "receipt", description: "Cau hinh hoa don dien tu va thong tin xuat hoa don." },
      { label: "Cau hinh bank", href: "/settings/bank", icon: "landmark", description: "Tai khoan ngan hang va cau hinh thanh toan." },
      { label: "Quan ly mau in", href: "/settings/print-templates", icon: "printer", description: "Mau in hop dong, phieu thu, phieu chi, ban hang, tra hang va xem truoc khi in." },
      { label: "Quan ly nguoi dung", href: "/settings/users", icon: "users", description: "Tai khoan he thong, vai tro va dat lai mat khau." },
      { label: "Vai tro / phan quyen", href: "/settings/roles", icon: "shield-check", description: "Tao vai tro, gan quyen va quan ly ma tran phan quyen." },
      { label: "Nguon ket noi CSDL", href: "/settings/database-sources", icon: "database", description: "Khai bao PostgreSQL / Neon.tech, chuoi ket noi va nguon data cho tung khach hang." },
      { label: "Cau hinh xuat bao cao", href: "/settings/report-templates", icon: "file-spreadsheet", description: "Designer mau in theo canvas cho tung bao cao, gom bo cuc, chu ky, header/footer va xem truoc." },
      { label: "Quan ly chi nhanh", href: "/settings/branches", icon: "map-pinned", description: "Chi nhanh, gio mo cua, luot dat va quy tac coc." },
      { label: "Lich su thao tac", href: "/settings/audit-logs", icon: "history", description: "Lich su thao tac create / update / delete / login / export." },
      { label: "Quan ly may cham cong", href: "/settings/attendance-machines", icon: "fingerprint", description: "Thiet bi cham cong, IP / Domain va dong bo." },
      { label: "Cau hinh SMS-Email-Zalo", href: "/settings/communication", icon: "send", description: "Quan ly kenh giao tiep va OTP." },
      { label: "Cau hinh sinh ma", href: "/settings/code-generation", icon: "hash", description: "Quy tac tao ma khach hang, hop dong, phieu thu." },
      { label: "Chuong trinh khuyen mai", href: "/settings/promotions", icon: "ticket-percent", description: "Khuyen mai, uu dai, bonus buoi va bonus ngay." },
      { label: "KPI / Incentive", href: "/settings/incentive-policy", icon: "wallet-cards", description: "Target doanh thu, % thuong Sale / PT va he so theo nguon khach." },
      { label: "Quan ly tich diem", href: "/settings/loyalty-points", icon: "gift", description: "Diem tich luy, quy doi va lich su diem." },
      { label: "Uu dai Loyalty", href: "/settings/loyalty-benefits", icon: "badge-percent", description: "Danh muc uu dai cho hoi vien loyalty." },
      { label: "Cau hinh Tag", href: "/settings/tags", icon: "tags", description: "Tag hoi vien, lead va phan loai noi bo." },
      { label: "Thiet lap truong du lieu", href: "/settings/custom-fields", icon: "list-filter", description: "Mo rong truong du lieu cho CRM va hoi vien." },
      { label: "Marketing", href: "/settings/marketing", icon: "megaphone", description: "Chien dich marketing, kenh va mau gui tu dong." },
      { label: "Cau hinh lam tron so", href: "/settings/rounding", icon: "scale", description: "Quy tac lam tron so tien va hoa don." },
      { label: "Thiet lap Penalty", href: "/settings/penalty", icon: "octagon-alert", description: "Muc phat, vi pham va quy tac penalty." },
    ],
  },
  socialMenuGroup,
];

const menuGroupFallbacks: Array<{ prefix: string; title: string }> = [
  { prefix: "/dashboard", title: "Tong quan" },
  { prefix: "/overview", title: "Tong quan" },
  { prefix: "/members", title: "Hoi vien" },
  { prefix: "/customers", title: "Hoi vien" },
  { prefix: "/leads", title: "Hoi vien" },
  { prefix: "/customer-groups", title: "Hoi vien" },
  { prefix: "/customer-sources", title: "Hoi vien" },
  { prefix: "/member-presence", title: "Hoi vien" },
  { prefix: "/operations", title: "Nghiep vu" },
  { prefix: "/contracts", title: "Nghiep vu" },
  { prefix: "/services", title: "Nghiep vu" },
  { prefix: "/service-packages", title: "Nghiep vu" },
  { prefix: "/deposits", title: "Nghiep vu" },
  { prefix: "/pt-schedule", title: "Lich PT" },
  { prefix: "/training-sessions", title: "Lich PT" },
  { prefix: "/class-schedule", title: "Lich lop" },
  { prefix: "/staff", title: "Nhan vien" },
  { prefix: "/staff-shifts", title: "Nhan vien" },
  { prefix: "/staff-shift-assignments", title: "Nhan vien" },
  { prefix: "/trainers", title: "Nhan vien" },
  { prefix: "/cashbook", title: "So quy" },
  { prefix: "/receipts", title: "So quy" },
  { prefix: "/expenses", title: "So quy" },
  { prefix: "/pro-shop", title: "Pro Shop" },
  { prefix: "/products", title: "Pro Shop" },
  { prefix: "/product-groups", title: "Pro Shop" },
  { prefix: "/lockers", title: "Pro Shop" },
  { prefix: "/locker-rentals", title: "Pro Shop" },
  { prefix: "/suppliers", title: "Pro Shop" },
  { prefix: "/purchase-orders", title: "Pro Shop" },
  { prefix: "/towel-issues", title: "Pro Shop" },
  { prefix: "/loyalty", title: "Nghiep vu" },
  { prefix: "/reports", title: "Bao cao" },
  { prefix: "/settings", title: "Thiet lap" },
  { prefix: "/social", title: "Mang xa hoi" },
  { prefix: "/branches", title: "Thiet lap" },
  { prefix: "/users", title: "Thiet lap" },
  { prefix: "/roles", title: "Thiet lap" },
  { prefix: "/audit-logs", title: "Thiet lap" },
  { prefix: "/attendance-machines", title: "Thiet lap" },
  { prefix: "/tenant-databases", title: "Thiet lap" },
];

const viewPermissionByPath: Record<string, string> = {
  "/dashboard": "dashboard.view",
  "/overview/kpi": "reports-kpi.view",
  "/overview/branch-revenue": "reports-branch-revenue.view",
  "/overview/birthday": "reports-birthday.view",
  "/overview/follow-up": "reports-follow-up.view",
  "/overview/lead": "reports-lead.view",
  "/members/customers": "customers.view",
  "/members/leads": "leads.view",
  "/members/status": "customers.view",
  "/members/presence": "member-presence.view",
  "/members/debt": "reports-contract-remain.view",
  "/members/customer-groups": "customer-groups.view",
  "/members/customer-sources": "customer-sources.view",
  "/members/birthday": "reports-birthday.view",
  "/operations/service-price-book": "service-packages.view",
  "/operations/service-registration": "contracts.view",
  "/operations/contracts": "contracts.view",
  "/operations/contract-renewal": "contracts.view",
  "/operations/contract-upgrade": "contracts.view",
  "/operations/contract-freeze": "contracts.view",
  "/operations/contract-transfer": "contracts.view",
  "/operations/branch-transfer": "contracts.view",
  "/operations/contract-cancel": "contracts.view",
  "/operations/contract-conversion": "contracts.view",
  "/operations/lockers": "lockers.view",
  "/operations/locker-rentals": "locker-rentals.view",
  "/operations/towel-issues": "towel-issues.view",
  "/operations/towels": "products.view",
  "/operations/product-groups": "product-groups.view",
  "/operations/loyalty": "customers.view",
  "/pt-schedule/calendar": "training-sessions.view",
  "/pt-schedule/booking-report": "reports-pt-training.view",
  "/pt-schedule/penalty-history": "audit-logs.view",
  "/class-schedule/bookings": "training-sessions.view",
  "/class-schedule/classes": "service-packages.view",
  "/class-schedule/timetable": "training-sessions.view",
  "/class-schedule/group-pt": "training-sessions.view",
  "/class-schedule/line-categories": "services.view",
  "/class-schedule/line-schedule": "training-sessions.view",
  "/class-schedule/line-layout": "branches.view",
  "/class-schedule/cskh-booking": "reports-follow-up.view",
  "/class-schedule/booking-attachments": "training-sessions.view",
  "/staff/users": "users.view",
  "/staff/exercise-library": "products.view",
  "/staff/stages": "roles.view",
  "/staff/program-templates": "settings.view",
  "/staff/programs": "trainers.view",
  "/staff/kpi": "reports-kpi.view",
  "/staff/shifts": "staff-shifts.view",
  "/staff/shift-assignments": "staff-shift-assignments.view",
  "/staff/attendance-adjustments": "staff-attendance-events.view",
  "/cashbook/receipts": "receipts.view",
  "/cashbook/expenses": "expenses.view",
  "/pro-shop/products": "products.view",
  "/pro-shop/partners": "suppliers.view",
  "/pro-shop/price-book": "products.view",
  "/pro-shop/sales": "shop-sales.view",
  "/pro-shop/returns": "shop-returns.view",
  "/pro-shop/purchase-orders": "purchase-orders.view",
  "/pro-shop/cashbook": "reports-payment.view",
  "/reports/checkin": "reports-checkin.view",
  "/reports/pt-training": "reports-pt-training.view",
  "/reports/staff-attendance": "reports-staff-attendance.view",
  "/reports/class-attendance": "reports-class-attendance.view",
  "/reports/allocation": "reports-allocation.view",
  "/reports/business-activity": "reports-business-activity.view",
  "/reports/sales-summary": "reports-sales-summary.view",
  "/reports/branch-revenue": "reports-branch-revenue.view",
  "/reports/debt": "reports-debt.view",
  "/reports/branch-summary": "reports-branch-summary.view",
  "/reports/expiring-members-revenue": "reports-expiring-members-revenue.view",
  "/reports/contract-type-revenue": "reports-contract-type-revenue.view",
  "/reports/service-group-revenue": "reports-service-group-revenue.view",
  "/reports/sales-incentive": "reports-sales-incentive.view",
  "/reports/pt-incentive": "reports-pt-incentive.view",
  "/reports/package-progress": "reports-package-progress.view",
  "/reports/customer-source": "reports-customer-source.view",
  "/reports/contract-remain": "reports-contract-remain.view",
  "/reports/payment": "reports-payment.view",
  "/reports/deposit": "reports-deposit.view",
  "/reports/card-revenue": "reports-card-revenue.view",
  "/reports/staff-review": "reports-staff-review.view",
  "/reports/lead-status": "reports-lead-status.view",
  "/reports/kpi": "reports-kpi.view",
  "/reports/lead": "reports-lead.view",
  "/settings/company": "settings.view",
  "/settings/program-branding": "settings.view",
  "/settings/e-invoice": "settings.view",
  "/settings/bank": "settings.view",
  "/settings/print-templates": "settings.view",
  "/settings/users": "users.view",
  "/settings/roles": "roles.view",
  "/settings/database-sources": "tenant-databases.view",
  "/settings/report-templates": "settings.view",
  "/settings/branches": "branches.view",
  "/settings/audit-logs": "audit-logs.view",
  "/settings/attendance-machines": "attendance-machines.view",
  "/settings/communication": "settings.view",
  "/settings/code-generation": "settings.view",
  "/settings/promotions": "settings.view",
  "/settings/incentive-policy": "settings.view",
  "/settings/loyalty-points": "settings.view",
  "/settings/loyalty-benefits": "settings.view",
  "/settings/tags": "settings.view",
  "/settings/custom-fields": "settings.view",
  "/settings/marketing": "settings.view",
  "/settings/rounding": "settings.view",
  "/settings/penalty": "settings.view",
  [socialHubPath]: "settings.view",
  [socialInboxPath]: "reports-social-inbox.view",
  [socialPerformancePath]: "reports-social-channel-performance.view",
  "/reports/social-channel-performance": "reports-social-channel-performance.view",
  ...Object.fromEntries(socialModuleCatalog.map((item) => [`/social/${item.slug}`, "settings.view"])),
};

export const isMenuItemActive = (pathname: string, href: string) => pathname === href || pathname.startsWith(`${href}/`);

export const getAllMenuItems = () => menuGroups.flatMap((group) => group.items);

export const getMenuGroupByPath = (pathname: string) =>
  menuGroups.find((group) => group.items.some((item) => isMenuItemActive(pathname, item.href))) ??
  menuGroups.find((group) => menuGroupFallbacks.some((rule) => rule.title === group.title && pathname.startsWith(rule.prefix))) ??
  menuGroups[0];

export const getViewPermissionForPath = (pathname: string) => {
  const matchingPath = Object.keys(viewPermissionByPath)
    .sort((left, right) => right.length - left.length)
    .find((path) => pathname === path || pathname.startsWith(`${path}/`));

  return matchingPath ? viewPermissionByPath[matchingPath] : undefined;
};
