import { PortalPageDefinition, ReportDefinition, ResourceDefinition, SettingDefinition } from "@/types/portal";
import { getAllMenuItems, getMenuGroupByPath, isMenuItemActive } from "@/lib/navigation-config";
import { attendanceMachineStatusOptions, auditLogFilters, branchField, contractManagementFilters, customerManagementFilters, leadManagementFilters, lockerManagementFilters, lockerRentalManagementFilters, paymentVoucherFilters, penaltyHistoryFilters, productCatalogFilters, purchaseOrderManagementFilters, resourceRegistry, serviceCatalogFilters, servicePackageCatalogFilters, staffAttendanceAdjustmentFilters, supplierCatalogFilters, trainerCatalogFilters, trainingScheduleFilters, userManagementFilters } from "@/lib/resource-registry";
import { getReportPermissionCode, reportRegistry } from "@/lib/report-registry";
import { settingsRegistry } from "@/lib/settings-registry";
import { socialHubPath, socialInboxPath, socialLinkCenterPath, socialLinkCenterSettingKey, socialModuleCatalog, socialHubSettingKey, socialPerformancePath } from "@/lib/social-module-config";

const endpointViewPermissionRegistry = new Map<string, string>([
  ...Object.values(resourceRegistry).map((resource) => [resource.endpoint, `${resource.permissionPrefix}.view`] as const),
  ...Object.values(settingsRegistry).map((setting) => [setting.endpoint, "settings.view"] as const),
  ...Object.values(reportRegistry).map((report) => [report.endpoint, report.permission || getReportPermissionCode(report.baseKey || report.key)] as const),
]);

export const getViewPermissionForEndpoint = (endpoint?: string) => {
  if (!endpoint) {
    return undefined;
  }

  return endpointViewPermissionRegistry.get(endpoint);
};

type ResourceCloneOverrides = Partial<
  Pick<ResourceDefinition, "title" | "subtitle" | "searchPlaceholder" | "createLabel" | "emptyStateTitle" | "emptyStateDescription" | "emptyStateExamples" | "defaultFilters" | "columns" | "filters" | "fields" | "detailFields">
>;

const cloneResourceDefinition = (key: string, baseKey: string, overrides: ResourceCloneOverrides = {}): ResourceDefinition => ({
  ...resourceRegistry[baseKey],
  ...overrides,
  key,
  baseKey,
  title: overrides.title || resourceRegistry[baseKey].title,
  subtitle: overrides.subtitle || resourceRegistry[baseKey].subtitle,
  searchPlaceholder: overrides.searchPlaceholder || resourceRegistry[baseKey].searchPlaceholder,
  createLabel: overrides.createLabel || resourceRegistry[baseKey].createLabel,
  emptyStateTitle: overrides.emptyStateTitle || resourceRegistry[baseKey].emptyStateTitle,
  emptyStateDescription: overrides.emptyStateDescription || resourceRegistry[baseKey].emptyStateDescription,
  emptyStateExamples: overrides.emptyStateExamples || resourceRegistry[baseKey].emptyStateExamples,
  columns: overrides.columns || resourceRegistry[baseKey].columns,
  filters: overrides.filters || resourceRegistry[baseKey].filters,
  fields: overrides.fields || resourceRegistry[baseKey].fields,
  detailFields: overrides.detailFields || resourceRegistry[baseKey].detailFields,
  defaultFilters: {
    ...(resourceRegistry[baseKey].defaultFilters || {}),
    ...(overrides.defaultFilters || {}),
  },
});

const cloneReportDefinition = (
  key: string,
  baseKey: string,
  overrides: Partial<Pick<ReportDefinition, "title" | "subtitle">> = {},
): ReportDefinition => ({
  ...reportRegistry[baseKey],
  key,
  baseKey,
  permission: reportRegistry[baseKey].permission || getReportPermissionCode(baseKey),
  title: overrides.title || reportRegistry[baseKey].title,
  subtitle: overrides.subtitle || reportRegistry[baseKey].subtitle,
});

const cloneSettingDefinition = (
  key: string,
  baseKey: string,
  overrides: Partial<
    Pick<
      SettingDefinition,
      "title" | "subtitle" | "searchPlaceholder" | "createLabel" | "emptyStateTitle" | "emptyStateDescription" | "noticeTitle" | "noticeDescription"
    >
  > = {},
): SettingDefinition => ({
  ...settingsRegistry[baseKey],
  key,
  baseKey,
  title: overrides.title || settingsRegistry[baseKey].title,
  subtitle: overrides.subtitle || settingsRegistry[baseKey].subtitle,
  searchPlaceholder: overrides.searchPlaceholder || settingsRegistry[baseKey].searchPlaceholder,
  createLabel: overrides.createLabel || settingsRegistry[baseKey].createLabel,
  emptyStateTitle: overrides.emptyStateTitle || settingsRegistry[baseKey].emptyStateTitle,
  emptyStateDescription: overrides.emptyStateDescription || settingsRegistry[baseKey].emptyStateDescription,
  noticeTitle: overrides.noticeTitle || settingsRegistry[baseKey].noticeTitle,
  noticeDescription: overrides.noticeDescription || settingsRegistry[baseKey].noticeDescription,
});

export const portalPageRegistry: Record<string, PortalPageDefinition> = {
  dashboard: {
    kind: "dashboard",
    key: "dashboard",
    title: "Tong quan he thong",
    subtitle: "Tong hop hoi vien, hop dong, lead, doanh thu, cong no va canh bao van hanh theo chi nhanh.",
  },
  "overview/kpi": {
    kind: "report",
    key: "overview-kpi",
    reportKey: "kpi",
    title: "Dashboard KPI ngay / thang",
    subtitle: "Theo doi lead, hop dong, doanh thu va % KPI tren mot man hinh tong hop.",
  },
  "overview/branch-revenue": {
    kind: "report",
    key: "overview-branch-revenue",
    reportKey: "branch-revenue",
    title: "Doanh thu theo chi nhanh",
    subtitle: "So sanh doanh thu membership, PT, coc va cac nguon thu giua cac chi nhanh.",
  },
  "overview/birthday": {
    kind: "report",
    key: "overview-birthday",
    reportKey: "birthday",
    title: "Sinh nhat hoi vien",
    subtitle: "Danh sach hoi vien sap sinh nhat de CSKH chu dong chuc mung va gui uu dai.",
  },
  "overview/follow-up": {
    kind: "report",
    key: "overview-follow-up",
    reportKey: "follow-up",
    title: "Cham soc / lich hen",
    subtitle: "Tong hop lich hen, follow-up, dau viec qua han va nhac viec CSKH.",
  },
  "overview/lead": {
    kind: "report",
    key: "overview-lead",
    reportKey: "lead",
    title: "Bao cao Lead",
    subtitle: "Tong hop lead, nguon lead, nhan vien phu trach va ty le chuyen doi.",
  },
  "members/customers": {
    kind: "resource",
    key: "members-customers",
    resourceKey: "customers",
    title: "Hoi vien / khach hang",
    subtitle: "Ho so hoi vien, trang thai, cong no, lich su mua goi va thong tin lien he.",
  },
  "members/leads": {
    kind: "resource",
    key: "members-leads",
    resourceKey: "leads",
    title: "Ho so Lead",
    subtitle: "Danh sach lead, pipeline, lich hen va lich su cham soc.",
  },
  "members/status": {
    kind: "resource",
    key: "members-status",
    resourceKey: "customers",
    title: "Trang thai hoi vien",
    subtitle: "Theo doi hoi vien active, prospect, inactive va cac canh bao lien quan.",
  },
  "members/presence": {
    kind: "resource",
    key: "members-presence",
    resourceKey: "member-presence",
    title: "Xac nhan dang tap",
    subtitle: "Bam xac nhan hoi vien dang tap / off, theo doi qua ngay va lich su hien dien gan nhat.",
  },
  "members/debt": {
    kind: "report",
    key: "members-debt",
    reportKey: "contract-remain",
    title: "Cong no hoi vien",
    subtitle: "Tong hop hop dong con no, gia tri con lai va nhac viec can thu.",
  },
  "members/customer-groups": {
    kind: "resource",
    key: "members-customer-groups",
    resourceKey: "customer-groups",
    title: "Nhom khach hang",
    subtitle: "Danh muc phan nhom hoi vien, VIP va doanh nghiep.",
  },
  "members/customer-sources": {
    kind: "resource",
    key: "members-customer-sources",
    resourceKey: "customer-sources",
    title: "Nguon khach hang",
    subtitle: "Danh muc nguon khach tu referral, walk-in, social, ads va CRM hoi vien.",
  },
  "members/birthday": {
    kind: "report",
    key: "members-birthday",
    reportKey: "birthday",
    title: "Sinh nhat hoi vien",
    subtitle: "Lich nhac sinh nhat, doi tuong can CSKH va thong tin hoi vien active.",
  },
  "operations/service-price-book": {
    kind: "resource",
    key: "operations-service-price-book",
    resourceKey: "service-packages",
    title: "Bang gia dich vu",
    subtitle: "Bang gia membership, PT, combo, buoi KM va quy tac gia tri con lai.",
  },
  "operations/service-registration": {
    kind: "resource",
    key: "operations-service-registration",
    resourceKey: "contracts",
    title: "Dang ky dich vu",
    subtitle: "Mo hop dong moi, dang ky goi tap va lien ket thanh toan hoi vien.",
  },
  "operations/contracts": {
    kind: "resource",
    key: "operations-contracts",
    resourceKey: "contracts",
    title: "Danh sach hop dong",
    subtitle: "Theo doi hop dong, so buoi, thanh toan, cong no va trang thai kich hoat.",
  },
  "operations/contract-renewal": {
    kind: "resource",
    key: "operations-contract-renewal",
    resourceKey: "contracts",
    title: "Gia han hop dong",
    subtitle: "Danh sach hop dong sap het han va xu ly gia han / tiep tuc goi tap.",
  },
  "operations/contract-upgrade": {
    kind: "resource",
    key: "operations-contract-upgrade",
    resourceKey: "contracts",
    title: "Nang cap hop dong",
    subtitle: "Nang cap goi tap, cap nhat gia chenhlech va quy doi so buoi.",
  },
  "operations/contract-freeze": {
    kind: "resource",
    key: "operations-contract-freeze",
    resourceKey: "contracts",
    title: "Bao luu hop dong",
    subtitle: "Theo doi hop dong tam dung, bao luu va ngay kich hoat lai.",
  },
  "operations/contract-transfer": {
    kind: "resource",
    key: "operations-contract-transfer",
    resourceKey: "contracts",
    title: "Chuyen nhuong hop dong",
    subtitle: "Chuyen nhuong / doi chu hop dong va lich su dieu chinh lien quan.",
  },
  "operations/branch-transfer": {
    kind: "resource",
    key: "operations-branch-transfer",
    resourceKey: "contracts",
    title: "Chuyen chi nhanh",
    subtitle: "Theo doi hoi vien, hop dong va giao dich duoc dieu chuyen giua cac chi nhanh.",
  },
  "operations/contract-cancel": {
    kind: "resource",
    key: "operations-contract-cancel",
    resourceKey: "contracts",
    title: "Huy hop dong",
    subtitle: "Danh sach hop dong huy / dong va lich su thao tac lien quan.",
  },
  "operations/contract-conversion": {
    kind: "resource",
    key: "operations-contract-conversion",
    resourceKey: "contracts",
    title: "Chuyen doi hop dong",
    subtitle: "Xu ly chuyen doi goi, quy doi gia tri con lai va cap nhat lich su.",
  },
  "operations/lockers": {
    kind: "resource",
    key: "operations-lockers",
    resourceKey: "lockers",
    title: "Tu do",
    subtitle: "Theo doi tinh trang tu do, khach dang thue, tien coc va lich su su dung.",
  },
  "operations/locker-rentals": {
    kind: "resource",
    key: "operations-locker-rentals",
    resourceKey: "locker-rentals",
    title: "Thue tu do",
    subtitle: "Lap phieu thue tu, gan hoi vien va theo doi lich su su dung theo tung tu.",
  },
  "operations/towel-issues": {
    kind: "resource",
    key: "operations-towel-issues",
    resourceKey: "towel-issues",
    title: "Phat / tra khan",
    subtitle: "Theo doi tung luot phat khan, tra khan, mat / hu va dang giat theo hoi vien.",
  },
  "operations/towels": {
    kind: "resource",
    key: "operations-towels",
    resourceKey: "products",
    title: "Khan tap / vat tu",
    subtitle: "Danh muc khan tap, vat tu, ton kho, so luong da ban va cac luot thu tien theo chi nhanh.",
  },
  "operations/product-groups": {
    kind: "resource",
    key: "operations-product-groups",
    resourceKey: "product-groups",
    title: "Nhom hang / cap phat",
    subtitle: "Noi tao va quan ly nhom hang de gan vao Pro Shop, khan tap va vat tu dich vu theo chi nhanh.",
  },
  "operations/loyalty": {
    kind: "resource",
    key: "operations-loyalty",
    resourceKey: "customers",
    title: "Dang ky HD Loyalty",
    subtitle: "Theo doi hoi vien loyalty, uu dai tich diem va phan nhom khach hang trung thanh.",
  },
  "pt-schedule/calendar": {
    kind: "resource",
    key: "pt-schedule-calendar",
    resourceKey: "training-sessions",
    title: "Lich PT",
    subtitle: "Dat lich PT, check-in buoi tap, ket qua buoi va tru so buoi con lai.",
  },
  "pt-schedule/booking-report": {
    kind: "report",
    key: "pt-schedule-booking-report",
    reportKey: "pt-training",
    title: "Bao cao Booking PT",
    subtitle: "Tong hop booking PT, huan luyen vien phu trach va ty le hoan thanh buoi tap.",
  },
  "pt-schedule/penalty-history": {
    kind: "resource",
    key: "pt-schedule-penalty-history",
    resourceKey: "audit-logs",
    title: "Lich su Penalty",
    subtitle: "Nhat ky penalty, vi pham, cap nhat lich va cac thao tac lien quan den dat lich.",
  },
  "class-schedule/bookings": {
    kind: "resource",
    key: "class-schedule-bookings",
    resourceKey: "training-sessions",
    title: "Danh sach book lich",
    subtitle: "Danh sach booking theo ngay, lop, PT nhom va trang thai check-in.",
  },
  "class-schedule/classes": {
    kind: "resource",
    key: "class-schedule-classes",
    resourceKey: "service-packages",
    title: "Danh sach lop",
    subtitle: "Danh muc lop, goi class va cac line dang van hanh.",
  },
  "class-schedule/timetable": {
    kind: "resource",
    key: "class-schedule-timetable",
    resourceKey: "training-sessions",
    title: "Lich lop",
    subtitle: "Lich van hanh lop theo ngay, khung gio, line va nhan su phu trach.",
  },
  "class-schedule/group-pt": {
    kind: "resource",
    key: "class-schedule-group-pt",
    resourceKey: "training-sessions",
    title: "Lich PT nhom",
    subtitle: "Lich PT nhom, dat cho, suc chua va theo doi tham gia.",
  },
  "class-schedule/line-categories": {
    kind: "resource",
    key: "class-schedule-line-categories",
    resourceKey: "services",
    title: "Danh muc Line",
    subtitle: "Danh muc line, loai lop, khu vuc va cau hinh van hanh phong tap.",
  },
  "class-schedule/line-schedule": {
    kind: "resource",
    key: "class-schedule-line-schedule",
    resourceKey: "training-sessions",
    title: "Lich Line",
    subtitle: "Phan bo lich theo line, line booking va cong suat phong tap.",
  },
  "class-schedule/line-layout": {
    kind: "resource",
    key: "class-schedule-line-layout",
    resourceKey: "branches",
    title: "So do line / phong",
    subtitle: "Bo tri line, phong tap, suc chua va quy tac dat lich theo chi nhanh.",
  },
  "class-schedule/cskh-booking": {
    kind: "report",
    key: "class-schedule-cskh-booking",
    reportKey: "follow-up",
    title: "Booking CSKH",
    subtitle: "Theo doi booking phat sinh tu CSKH, lich hen va nhac viec cham soc.",
  },
  "class-schedule/booking-attachments": {
    kind: "resource",
    key: "class-schedule-booking-attachments",
    resourceKey: "training-sessions",
    title: "Dinh kem Booking",
    subtitle: "Tra cuu booking va file dinh kem phat sinh trong qua trinh van hanh lop / PT.",
  },
  "staff/users": {
    kind: "resource",
    key: "staff-users",
    resourceKey: "users",
    title: "Nhan vien",
    subtitle: "Ho so nhan vien, login he thong, vai tro, chi nhanh va trang thai tai khoan.",
  },
  "staff/exercise-library": {
    kind: "resource",
    key: "staff-exercise-library",
    resourceKey: "products",
    title: "Danh muc bai tap",
    subtitle: "Thu vien bai tap, dung cu tap va tai nguyen ho tro PT trien khai giao an.",
  },
  "staff/stages": {
    kind: "resource",
    key: "staff-stages",
    resourceKey: "roles",
    title: "Danh sach Stage",
    subtitle: "Quan ly stage, cap do, nhom phu trach va mo ta quy trinh huan luyen.",
  },
  "staff/program-templates": {
    kind: "setting",
    key: "staff-program-templates",
    settingKey: "birthday-template",
    title: "Template giao an",
    subtitle: "Tam thoi dung chung thu vien template he thong trong khi module giao an mau chua co backend rieng.",
  },
  "staff/programs": {
    kind: "resource",
    key: "staff-programs",
    resourceKey: "trainers",
    title: "Giao an",
    subtitle: "Danh sach giao an, huan luyen vien phu trach va tai nguyen lien quan.",
  },
  "staff/kpi": {
    kind: "report",
    key: "staff-kpi",
    reportKey: "kpi",
    title: "KPI nhan vien",
    subtitle: "Lead, hop dong, doanh thu va % hoan thanh KPI theo nhan vien.",
  },
  "staff/shifts": {
    kind: "resource",
    key: "staff-shifts-page",
    resourceKey: "staff-shifts",
    title: "Danh sách ca làm",
    subtitle: "Danh mục ca, giờ vào/ra, nghỉ giữa ca, OT, ca qua đêm và các tham số trễ / về sớm.",
  },
  "staff/shift-assignments": {
    kind: "resource",
    key: "staff-shift-assignments-page",
    resourceKey: "staff-shift-assignments",
    title: "Phân ca nhân viên",
    subtitle: "Gán ca cố định / ca xoay cho nhân viên, hỗ trợ không thời hạn và theo dõi trạng thái đang làm.",
  },
  "staff/attendance-adjustments": {
    kind: "resource",
    key: "staff-attendance-adjustments",
    resourceKey: "staff-attendance-events",
    title: "Dieu chinh cham cong",
    subtitle: "Them, sua, xoa su kien vao/ra, doi nguon du lieu va theo doi lich su audit cho HR.",
  },
  "cashbook/receipts": {
    kind: "resource",
    key: "cashbook-receipts",
    resourceKey: "receipts",
    title: "Phieu thu",
    subtitle: "Thu tien hop dong, coc, the luot va cac nguon thu van hanh.",
  },
  "cashbook/expenses": {
    kind: "resource",
    key: "cashbook-expenses",
    resourceKey: "expenses",
    title: "Phieu chi",
    subtitle: "Chi phi van hanh, marketing, nha cung cap va phe duyet thanh toan.",
  },
  "pro-shop/products": {
    kind: "resource",
    key: "pro-shop-products",
    resourceKey: "products",
    title: "San pham",
    subtitle: "Danh muc san pham, ton kho, gia ban va tinh trang ban hang.",
  },
  "pro-shop/partners": {
    kind: "resource",
    key: "pro-shop-partners",
    resourceKey: "suppliers",
    title: "Khach hang / NCC",
    subtitle: "Danh sach doi tac, nha cung cap va thong tin lien he phuc vu Pro Shop.",
  },
  "pro-shop/price-book": {
    kind: "resource",
    key: "pro-shop-price-book",
    resourceKey: "products",
    title: "Bang gia Pro Shop",
    subtitle: "Bang gia ban le, gia von va ton kho san pham Pro Shop.",
  },
  "pro-shop/sales": {
    kind: "resource",
    key: "pro-shop-sales",
    resourceKey: "shop-sales",
    title: "Ban hang",
    subtitle: "Giao dich ban hang Pro Shop, dong san pham, thu ngan va lenh in hoa don ban le.",
  },
  "pro-shop/returns": {
    kind: "resource",
    key: "pro-shop-returns",
    resourceKey: "shop-returns",
    title: "Tra hang",
    subtitle: "Danh sach tra hang, dong san pham, hoan tien, dieu chinh ton kho va lenh in phieu tra.",
  },
  "pro-shop/purchase-orders": {
    kind: "resource",
    key: "pro-shop-purchase-orders",
    resourceKey: "purchase-orders",
    title: "Nhap hang",
    subtitle: "Phieu nhap hang Pro Shop, nha cung cap va tong gia tri nhap.",
  },
  "pro-shop/cashbook": {
    kind: "report",
    key: "pro-shop-cashbook",
    reportKey: "payment",
    title: "So quy Pro Shop",
    subtitle: "Thu chi, loi nhuan tam tinh va dong tien cua phan he Pro Shop.",
  },
  "reports/checkin": {
    kind: "report",
    key: "reports-checkin",
    reportKey: "checkin",
    title: "Bao cao Checkin",
    subtitle: "Tong hop checkin hoi vien, tan suat tap va xu huong tham gia.",
  },
  "reports/pt-training": {
    kind: "report",
    key: "reports-pt-training",
    reportKey: "pt-training",
    title: "PT - Training",
    subtitle: "Hieu suat PT, tong buoi, so khach dang phu trach va ket qua huan luyen.",
  },
  "reports/staff-attendance": {
    kind: "report",
    key: "reports-staff-attendance",
    reportKey: "staff-attendance",
    title: "Cham cong nhan vien",
    subtitle: "Bang cong theo ngay, vao/ra, di muon, thieu checkout va gio lam theo nhan vien.",
  },
  "reports/class-attendance": {
    kind: "report",
    key: "reports-class-attendance",
    reportKey: "class-attendance",
    title: "Cham cong lop",
    subtitle: "Thong ke si so lop, check-in lop va tinh trang tham gia theo buoi.",
  },
  "reports/allocation": {
    kind: "report",
    key: "reports-allocation",
    reportKey: "allocation",
    title: "Bao cao phan bo",
    subtitle: "Phan bo doanh thu, nhan su va tai nguyen theo chi nhanh / line.",
  },
  "reports/business-activity": {
    kind: "dashboard",
    key: "reports-business-activity",
    title: "Hoat dong kinh doanh",
    subtitle: "Tong hop doanh thu, lead, hop dong va nhac viec van hanh tren mot man hinh.",
  },
  "reports/sales-summary": {
    kind: "report",
    key: "reports-sales-summary",
    reportKey: "sales-summary",
    title: "Tong hop Sale goi dich vu",
    subtitle: "Tong hop doanh thu sale, hop dong moi va hieu suat theo nhan vien / goi tap.",
  },
  "reports/debt": {
    kind: "report",
    key: "reports-debt",
    reportKey: "debt",
    title: "Cong no",
    subtitle: "Cong no hop dong, gia tri con lai va canh bao can thu.",
  },
  "reports/branch-summary": {
    kind: "report",
    key: "reports-branch-summary",
    reportKey: "branch-summary",
    title: "Tong hop chi nhanh",
    subtitle: "Tong hop doanh thu, van hanh va hieu qua theo tung chi nhanh.",
  },
  "reports/expiring-members-revenue": {
    kind: "report",
    key: "reports-expiring-members-revenue",
    reportKey: "expiring-members-revenue",
    title: "Hoi vien sap het han",
    subtitle: "Thong ke hoi vien co hop dong het han trong thang va doanh thu da mang ve truoc ky nay.",
  },
  "reports/contract-type-revenue": {
    kind: "report",
    key: "reports-contract-type-revenue",
    reportKey: "contract-type-revenue",
    title: "Doanh thu theo loai hop dong",
    subtitle: "So sanh doanh thu hop dong moi va hop dong gia han theo tung ky.",
  },
  "reports/service-group-revenue": {
    kind: "report",
    key: "reports-service-group-revenue",
    reportKey: "service-group-revenue",
    title: "Doanh thu theo nhom dich vu",
    subtitle: "Tong hop doanh thu theo nhom dich vu va tung goi ban de nhin ro GOLD, SILVER, PT.",
  },
  "reports/sales-incentive": {
    kind: "report",
    key: "reports-sales-incentive",
    reportKey: "sales-incentive",
    title: "Incentive Sale",
    subtitle: "Doanh thu the hoi vien, quy doi theo nguon khach va tinh thuong Sale theo target.",
  },
  "reports/pt-incentive": {
    kind: "report",
    key: "reports-pt-incentive",
    reportKey: "pt-incentive",
    title: "Incentive PT",
    subtitle: "Doanh thu goi PT, bac thuong thang va so tien incentive cua tung PT.",
  },
  "reports/package-progress": {
    kind: "report",
    key: "reports-package-progress",
    reportKey: "package-progress",
    title: "Goi tap - qua trinh tap",
    subtitle: "Theo doi so buoi da dung, con lai va tien do training tren he thong.",
  },
  "reports/customer-source": {
    kind: "report",
    key: "reports-customer-source",
    reportKey: "customer-source",
    title: "Bao cao nguon khach hang",
    subtitle: "Thong ke so luong hoi vien va doanh thu theo tung nguon khach.",
  },
  "reports/card-revenue": {
    kind: "report",
    key: "reports-card-revenue",
    reportKey: "card-revenue",
    title: "Bao cao doanh thu the luot",
    subtitle: "Doanh thu the luot, giao dich phat sinh va tong hop thu theo ky.",
  },
  "reports/staff-review": {
    kind: "report",
    key: "reports-staff-review",
    reportKey: "staff-review",
    title: "Bao cao danh gia nhan vien",
    subtitle: "Tong hop KPI, doanh thu, lead chuyen doi va hieu suat nhan vien.",
  },
  "reports/lead-status": {
    kind: "report",
    key: "reports-lead-status",
    reportKey: "lead-status",
    title: "Bao cao trang thai Lead",
    subtitle: "Phan bo trang thai lead, nguon lead va kha nang chuyen doi.",
  },
  "settings/company": {
    kind: "setting",
    key: "settings-company",
    settingKey: "company",
    title: "Thiet lap cong ty",
    subtitle: "Thong tin doanh nghiep, app name, timezone, currency va logo he thong.",
  },
  "settings/program-branding": {
    kind: "setting",
    key: "settings-program-branding",
    settingKey: "program-branding",
    title: "Nhan dien chuong trinh",
    subtitle: "Doi ten, logo va thong diep hien thi o man dang nhap cua he thong.",
  },
  "settings/e-invoice": {
    kind: "setting",
    key: "settings-e-invoice",
    settingKey: "e-invoice",
    title: "Thiet lap hoa don dien tu",
    subtitle: "Thong tin gui hoa don, email thong bao va tham so van hanh hoa don dien tu.",
  },
  "settings/bank": {
    kind: "setting",
    key: "settings-bank",
    settingKey: "bank",
    title: "Cau hinh bank",
    subtitle: "Tai khoan ngan hang, chuan hien thi va tham so thanh toan van hanh.",
  },
  "settings/print-templates": {
    kind: "setting",
    key: "settings-print-templates",
    settingKey: "print-templates",
    title: "Quan ly mau in",
    subtitle: "Mau in hop dong, phieu thu, phieu chi, ban hang, tra hang va xem truoc mau in.",
  },
  "settings/users": {
    kind: "resource",
    key: "settings-users",
    resourceKey: "users",
    title: "Quan ly nguoi dung",
    subtitle: "Tai khoan he thong, dat lai mat khau, vai tro va pham vi chi nhanh.",
  },
  "settings/roles": {
    kind: "resource",
    key: "settings-roles",
    resourceKey: "roles",
    title: "Vai tro / phan quyen",
    subtitle: "Tao vai tro, gan quyen va quan ly ma tran phan quyen.",
  },
  "settings/database-sources": {
    kind: "resource",
    key: "settings-database-sources",
    resourceKey: "tenant-databases",
    title: "Nguon ket noi CSDL",
    subtitle: "Khai bao PostgreSQL / Neon.tech, chuoi ket noi va nguon data cho tung khach hang.",
  },
  "settings/report-templates": {
    kind: "setting",
    key: "settings-report-templates",
    settingKey: "report-templates",
    title: "Cau hinh xuat bao cao",
    subtitle: "Cau hinh tieu de, header/footer, bo loc va xem truoc truoc khi in bao cao.",
  },
  "settings/branches": {
    kind: "resource",
    key: "settings-branches",
    resourceKey: "branches",
    title: "Quan ly chi nhanh",
    subtitle: "Thong tin chi nhanh, thoi gian mo cua va quy tac dat / coc.",
  },
  "settings/audit-logs": {
    kind: "resource",
    key: "settings-audit-logs",
    resourceKey: "audit-logs",
    title: "Lich su thao tac",
    subtitle: "Lich su thao tac, dang nhap, xuat file va cap nhat cau hinh he thong.",
  },
  "settings/attendance-machines": {
    kind: "resource",
    key: "settings-attendance-machines",
    resourceKey: "attendance-machines",
    title: "Quan ly may cham cong",
    subtitle: "Thiet bi cham cong, cong ket noi, IP / Domain va trang thai dong bo.",
  },
  "settings/communication": {
    kind: "setting",
    key: "settings-communication",
    settingKey: "communication",
    title: "Cau hinh SMS-Email-Zalo",
    subtitle: "Quan ly kenh SMS / Email / Zalo, OTP va mau thong bao van hanh.",
  },
  "settings/code-generation": {
    kind: "setting",
    key: "settings-code-generation",
    settingKey: "code-generation",
    title: "Cau hinh sinh ma",
    subtitle: "Quy tac sinh ma hoi vien, hop dong, thu chi, booking va cac danh muc chung.",
  },
  "settings/promotions": {
    kind: "setting",
    key: "settings-promotions",
    settingKey: "promotions",
    title: "Chuong trinh khuyen mai",
    subtitle: "Mau khuyen mai, uu dai, bonus buoi / ngay va thong diep gui tu dong.",
  },
  "settings/incentive-policy": {
    kind: "setting",
    key: "settings-incentive-policy",
    settingKey: "incentive-policy",
    title: "KPI / Incentive",
    subtitle: "Target doanh thu, ty le thuong Sale / PT va he so quy doi theo nguon khach.",
  },
  "settings/loyalty-points": {
    kind: "setting",
    key: "settings-loyalty-points",
    settingKey: "loyalty-points",
    title: "Quan ly tich diem",
    subtitle: "Ty le tich diem, quy doi diem va tham so loyalty theo chi nhanh / toan he thong.",
  },
  "settings/loyalty-benefits": {
    kind: "setting",
    key: "settings-loyalty-benefits",
    settingKey: "loyalty-benefits",
    title: "Uu dai Loyalty",
    subtitle: "Nguong hang thanh vien, uu dai sinh nhat, referral va quy tac nhan dien loyalty.",
  },
  "settings/tags": {
    kind: "setting",
    key: "settings-tags",
    settingKey: "tags",
    title: "Cau hinh Tag",
    subtitle: "Bo tag mac dinh, auto-tag lead nong, cong no, VIP va follow-up qua han.",
  },
  "settings/custom-fields": {
    kind: "setting",
    key: "settings-custom-fields",
    settingKey: "custom-fields",
    title: "Thiet lap truong du lieu",
    subtitle: "Cau hinh truong du lieu, hien thi form va mo rong thong tin nghiep vu.",
  },
  "settings/marketing": {
    kind: "setting",
    key: "settings-marketing",
    settingKey: "marketing",
    title: "Marketing",
    subtitle: "Cau hinh chien dich, kenh gui, template va quota truyen thong.",
  },
  "settings/rounding": {
    kind: "setting",
    key: "settings-rounding",
    settingKey: "rounding",
    title: "Cau hinh lam tron so",
    subtitle: "Quy tac lam tron so tien, hoa don va hien thi bao cao.",
  },
  "settings/penalty": {
    kind: "setting",
    key: "settings-penalty",
    settingKey: "penalty",
    title: "Thiet lap Penalty",
    subtitle: "Quy tac penalty, muc phat va canh bao vi pham dat lich / cham cong.",
  },
  "settings/sms": { kind: "setting", key: "settings-sms", settingKey: "sms" },
  "settings/email": { kind: "setting", key: "settings-email", settingKey: "email" },
  "settings/zalo": { kind: "setting", key: "settings-zalo", settingKey: "zalo" },
  "settings/general": { kind: "setting", key: "settings-general", settingKey: "general" },
  "settings/birthday-template": { kind: "setting", key: "settings-birthday-template", settingKey: "birthday-template" },
  [socialHubPath.replace(/^\//, "")]: {
    kind: "setting",
    key: "social-hub",
    settingKey: socialHubSettingKey,
    title: "Tong quan mang xa hoi",
    subtitle: "Tong hop tat ca kenh social va messaging de cau hinh, theo doi va doi chieu nhanh.",
  },
  [socialLinkCenterPath.replace(/^\//, "")]: {
    kind: "setting",
    key: "social-link-center",
    settingKey: socialLinkCenterSettingKey,
    title: "Trung tam lien ket thiet bi",
    subtitle: "Lien ket may tinh, trinh duyet va dien thoai de tan dung phien dang login san cua kenh social / chat.",
  },
  [socialInboxPath.replace(/^\//, "")]: {
    kind: "report",
    key: "social-inbox-page",
    reportKey: "social-inbox",
    title: "Trung tam hoi thoai",
    subtitle: "Hang cho hoi thoai, lead can xu ly, SLA va tac vu theo kenh.",
  },
  [socialPerformancePath.replace(/^\//, "")]: {
    kind: "report",
    key: "social-performance-page",
    reportKey: "social-channel-performance",
    title: "Hieu suat kenh social / chat",
    subtitle: "Tong hop hoi thoai, lead chuyen doi, toc do phan hoi va doanh thu ho tro theo kenh.",
  },
  ...Object.fromEntries(
    socialModuleCatalog.map((item) => [
      `social/${item.slug}`,
      {
        kind: "setting",
        key: `social-${item.slug}`,
        settingKey: item.settingKey,
        title: item.title,
        subtitle: item.subtitle,
      } satisfies PortalPageDefinition,
    ]),
  ),
  customers: { kind: "resource", key: "customers-page", resourceKey: "customers" },
  leads: { kind: "resource", key: "leads-page", resourceKey: "leads" },
  contracts: { kind: "resource", key: "contracts-page", resourceKey: "contracts" },
  services: { kind: "resource", key: "services-page", resourceKey: "services" },
  "service-packages": { kind: "resource", key: "service-packages-page", resourceKey: "service-packages" },
  trainers: { kind: "resource", key: "trainers-page", resourceKey: "trainers" },
  "training-sessions": { kind: "resource", key: "training-sessions-page", resourceKey: "training-sessions" },
  receipts: { kind: "resource", key: "receipts-page", resourceKey: "receipts" },
  expenses: { kind: "resource", key: "expenses-page", resourceKey: "expenses" },
  lockers: { kind: "resource", key: "lockers-page", resourceKey: "lockers" },
  "locker-rentals": { kind: "resource", key: "locker-rentals-page", resourceKey: "locker-rentals" },
  "towel-issues": { kind: "resource", key: "towel-issues-page", resourceKey: "towel-issues" },
  deposits: { kind: "resource", key: "deposits-page", resourceKey: "deposits" },
  products: { kind: "resource", key: "products-page", resourceKey: "products" },
  suppliers: { kind: "resource", key: "suppliers-page", resourceKey: "suppliers" },
  "purchase-orders": { kind: "resource", key: "purchase-orders-page", resourceKey: "purchase-orders" },
  "tenant-databases": { kind: "resource", key: "tenant-databases-page", resourceKey: "tenant-databases" },
  branches: { kind: "resource", key: "branches-page", resourceKey: "branches" },
  users: { kind: "resource", key: "users-page", resourceKey: "users" },
  roles: { kind: "resource", key: "roles-page", resourceKey: "roles" },
  "attendance-machines": { kind: "resource", key: "attendance-machines-page", resourceKey: "attendance-machines" },
  "staff-shifts": { kind: "resource", key: "staff-shifts-resource-page", resourceKey: "staff-shifts" },
  "staff-shift-assignments": { kind: "resource", key: "staff-shift-assignments-resource-page", resourceKey: "staff-shift-assignments" },
  "staff-attendance-events": { kind: "resource", key: "staff-attendance-events-page", resourceKey: "staff-attendance-events" },
  "member-presence": { kind: "resource", key: "member-presence-page", resourceKey: "member-presence" },
  "customer-groups": { kind: "resource", key: "customer-groups-page", resourceKey: "customer-groups" },
  "customer-sources": { kind: "resource", key: "customer-sources-page", resourceKey: "customer-sources" },
  "product-groups": { kind: "resource", key: "product-groups-page", resourceKey: "product-groups" },
  "audit-logs": { kind: "resource", key: "audit-logs-page", resourceKey: "audit-logs" },
  "reports/kpi": { kind: "report", key: "reports-kpi-page", reportKey: "kpi" },
  "reports/lead": { kind: "report", key: "reports-lead-page", reportKey: "lead" },
  "reports/branch-revenue": { kind: "report", key: "reports-branch-revenue-page", reportKey: "branch-revenue" },
  "reports/contract-remain": { kind: "report", key: "reports-contract-remain-page", reportKey: "contract-remain" },
  "reports/payment": { kind: "report", key: "reports-payment-page", reportKey: "payment" },
  "reports/deposit": { kind: "report", key: "reports-deposit-page", reportKey: "deposit" },
  "reports/trainer-performance": { kind: "report", key: "reports-trainer-performance-page", reportKey: "trainer-performance" },
  "reports/birthday": { kind: "report", key: "reports-birthday-page", reportKey: "birthday" },
  "reports/follow-up": { kind: "report", key: "reports-follow-up-page", reportKey: "follow-up" },
  "reports/social-channel-performance": { kind: "report", key: "reports-social-channel-performance-page", reportKey: "social-channel-performance" },
};

const contractStatusOptions = [
  { label: "Draft", value: "DRAFT" },
  { label: "Active", value: "ACTIVE" },
  { label: "Paused", value: "PAUSED" },
  { label: "Expired", value: "EXPIRED" },
  { label: "Cancelled", value: "CANCELLED" },
] as const;

const resourcePageOverrides: Record<string, ResourceCloneOverrides> = {
  "members-customers": {
    filters: customerManagementFilters,
    columns: [
      { key: "customerInfo", label: "Thong tin hoi vien", minWidth: 240, wrap: true, multiline: true },
      { key: "membershipStatus", label: "Trang thai", type: "status", minWidth: 108, align: "center" },
      { key: "registrationDate", label: "Thong tin dang ky", type: "date", minWidth: 180, wrap: true, multiline: true },
      { key: "endTrainingDate", label: "Thoi gian goi tap", type: "date", minWidth: 180, wrap: true, multiline: true },
      { key: "outstandingDebt", label: "Cong no", type: "currency", minWidth: 120, align: "right" },
    ],
    detailFields: ["code", "fingerprintCode", "customerInfo", "membershipStatus", "branchName", "groupName", "assignedUserName", "profileCount", "registrationDate", "startTrainingDate", "endTrainingDate", "fullAddress", "outstandingDebt", "note"],
  },
  "members-leads": {
    filters: leadManagementFilters,
    columns: [
      { key: "code", label: "Ma lead", minWidth: 100 },
      { key: "leadInfo", label: "Thong tin lead", minWidth: 240 },
      { key: "sourceName", label: "Nguon lead", minWidth: 130 },
      { key: "assignedUserName", label: "Nhan vien phu trach", minWidth: 160 },
      { key: "status", label: "Trang thai", type: "status", minWidth: 108, align: "center" },
      { key: "followUpState", label: "Tinh trang follow-up", type: "status", minWidth: 140, align: "center" },
      { key: "potentialLevel", label: "Muc do tiem nang", type: "status", minWidth: 132, align: "center" },
      { key: "appointmentAt", label: "Lich hen", type: "date", minWidth: 118 },
      { key: "nextFollowUpAt", label: "Hen tiep theo", type: "date", minWidth: 118 },
    ],
    detailFields: ["code", "leadInfo", "branchName", "sourceName", "assignedUserName", "status", "potentialLevel", "followUpState", "latestActivityType", "latestPerformedByName", "lastContactResult", "budgetExpected", "campaign", "demand", "nextFollowUpAt", "appointmentAt", "convertedCustomerName", "careNote"],
  },
  "members-status": {
    filters: customerManagementFilters,
    columns: [
      { key: "customerInfo", label: "Thong tin hoi vien", minWidth: 240, wrap: true, multiline: true },
      { key: "membershipStatus", label: "Trang thai", type: "status", minWidth: 108, align: "center" },
      { key: "startTrainingDate", label: "Thong tin dang ky", type: "date", minWidth: 180, wrap: true, multiline: true },
      { key: "endTrainingDate", label: "Thoi gian goi tap", type: "date", minWidth: 180, wrap: true, multiline: true },
      { key: "outstandingDebt", label: "Cong no", type: "currency", minWidth: 120, align: "right" },
      { key: "otherInfo", label: "Thong tin khac", minWidth: 190, wrap: true, multiline: true },
    ],
    detailFields: ["code", "customerInfo", "membershipStatus", "branchName", "groupName", "assignedUserName", "registrationDate", "startTrainingDate", "endTrainingDate", "fullAddress", "otherInfo", "outstandingDebt", "note"],
  },
  "members-customer-groups": {
    columns: [
      { key: "code", label: "Ma nhom", minWidth: 110 },
      { key: "name", label: "Ten nhom", minWidth: 180 },
      { key: "description", label: "Mo ta", minWidth: 260 },
      { key: "createdAt", label: "Ngay tao", type: "date", minWidth: 110 },
    ],
    detailFields: ["code", "name", "description"],
  },
  "members-customer-sources": {
    columns: [
      { key: "code", label: "Ma nguon", minWidth: 110 },
      { key: "name", label: "Ten nguon", minWidth: 180 },
      { key: "channel", label: "Nhom kenh", minWidth: 140 },
      { key: "description", label: "Mo ta", minWidth: 240 },
    ],
    detailFields: ["code", "name", "channel", "description"],
  },
  "operations-service-price-book": {
    searchPlaceholder: "Tim ma goi, ten goi, loai goi, dich vu",
    createLabel: "Them bang gia",
    filters: servicePackageCatalogFilters,
    columns: [
      { key: "code", label: "Ma goi", minWidth: 96 },
      { key: "name", label: "Ten goi", minWidth: 180 },
      { key: "serviceName", label: "Dich vu", minWidth: 150 },
      { key: "packageType", label: "Phan loai goi", minWidth: 110 },
      { key: "sessionLabel", label: "So buoi", minWidth: 110 },
      { key: "durationDays", label: "Thoi han", minWidth: 96, align: "center" },
      { key: "price", label: "Gia ban", type: "currency", minWidth: 120, align: "right" },
      { key: "contractCount", label: "So dang ky", minWidth: 86, align: "center" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "name", "serviceName", "serviceCategory", "branchName", "packageType", "sessionCount", "bonusSessions", "bonusDays", "durationDays", "price", "remainingValueRule", "contractCount", "status", "description"],
  },
  "operations-service-registration": {
    searchPlaceholder: "Tim ma dang ky, hoi vien, goi dich vu, sale",
    createLabel: "Dang ky moi",
    filters: contractManagementFilters,
    columns: [
      { key: "customerName", label: "Thong tin hoi vien", minWidth: 220, wrap: true, multiline: true },
      { key: "code", label: "Thong tin hop dong", minWidth: 180, wrap: true, multiline: true },
      { key: "servicePackageName", label: "Goi dich vu", minWidth: 220, wrap: true, multiline: true },
      { key: "paymentStatus", label: "Thanh toan", type: "status", minWidth: 180, wrap: true, multiline: true },
      { key: "startDate", label: "Thoi gian goi tap", type: "date", minWidth: 180, wrap: true, multiline: true },
    ],
    detailFields: ["code", "branchName", "customerName", "customerPhone", "servicePackageName", "serviceName", "saleUserName", "trainerName", "startDate", "endDate", "totalSessions", "bonusSessions", "remainingSessions", "totalAmount", "amountPaid", "amountDue", "paymentStatus", "status", "note"],
  },
  "operations-contracts": {
    searchPlaceholder: "Tim ma hop dong, hoi vien, sale, PT",
    filters: contractManagementFilters,
    columns: [
      { key: "customerName", label: "Thong tin hoi vien", minWidth: 220, wrap: true, multiline: true },
      { key: "code", label: "Thong tin hop dong", minWidth: 180, wrap: true, multiline: true },
      { key: "servicePackageName", label: "Goi dich vu", minWidth: 220, wrap: true, multiline: true },
      { key: "paymentStatus", label: "Thanh toan", type: "status", minWidth: 180, wrap: true, multiline: true },
      { key: "sessionUsage", label: "Tien do / so buoi", minWidth: 170, wrap: true, multiline: true },
    ],
  },
  "operations-contract-renewal": {
    searchPlaceholder: "Tim hop dong sap het han, hoi vien, goi dich vu",
    createLabel: "Lap gia han",
    filters: contractManagementFilters,
    defaultFilters: { status: "ACTIVE", expiring: "true" },
    columns: [
      { key: "customerName", label: "Thong tin hoi vien", minWidth: 220, wrap: true, multiline: true },
      { key: "code", label: "Thong tin hop dong", minWidth: 180, wrap: true, multiline: true },
      { key: "servicePackageName", label: "Goi hien tai", minWidth: 220, wrap: true, multiline: true },
      { key: "endDate", label: "Thoi gian / het han", type: "date", minWidth: 180, wrap: true, multiline: true },
      { key: "remainingSessions", label: "Tien do / so buoi", minWidth: 170, wrap: true, multiline: true },
      { key: "paymentStatus", label: "Thanh toan", type: "status", minWidth: 180, wrap: true, multiline: true },
    ],
    detailFields: ["code", "customerName", "customerPhone", "servicePackageName", "saleUserName", "trainerName", "startDate", "endDate", "remainingSessions", "daysRemaining", "remainingValue", "amountDue", "paymentStatus", "status", "note"],
  },
  "operations-contract-upgrade": {
    searchPlaceholder: "Tim hop dong can nang cap, hoi vien, ma HD cu",
    createLabel: "Lap nang cap",
    filters: contractManagementFilters,
    defaultFilters: { status: "ACTIVE" },
    columns: [
      { key: "customerName", label: "Thong tin hoi vien", minWidth: 220, wrap: true, multiline: true },
      { key: "code", label: "Thong tin hop dong", minWidth: 180, wrap: true, multiline: true },
      { key: "servicePackageName", label: "Goi hien tai", minWidth: 220, wrap: true, multiline: true },
      { key: "remainingValue", label: "Tien do / gia tri", minWidth: 170, wrap: true, multiline: true },
      { key: "paymentStatus", label: "Thanh toan", type: "status", minWidth: 180, wrap: true, multiline: true },
    ],
    detailFields: ["code", "customerName", "servicePackageName", "oldContractCode", "grossAmount", "totalDiscount", "vatAmount", "totalAmount", "amountPaid", "amountDue", "remainingValue", "paymentStatus", "status", "note"],
  },
  "operations-contract-freeze": {
    searchPlaceholder: "Tim hop dong bao luu, hoi vien, goi dich vu",
    createLabel: "Lap bao luu",
    filters: contractManagementFilters,
    defaultFilters: { status: "PAUSED" },
    columns: [
      { key: "customerName", label: "Thong tin hoi vien", minWidth: 220, wrap: true, multiline: true },
      { key: "code", label: "Thong tin hop dong", minWidth: 180, wrap: true, multiline: true },
      { key: "servicePackageName", label: "Goi tam dung", minWidth: 220, wrap: true, multiline: true },
      { key: "endDate", label: "Thoi gian bao luu", type: "date", minWidth: 180, wrap: true, multiline: true },
      { key: "remainingSessions", label: "Tien do / so buoi", minWidth: 170, wrap: true, multiline: true },
      { key: "paymentStatus", label: "Thanh toan", type: "status", minWidth: 180, wrap: true, multiline: true },
    ],
    detailFields: ["code", "customerName", "servicePackageName", "startDate", "endDate", "remainingSessions", "remainingValue", "paymentStatus", "status", "note"],
  },
  "operations-contract-transfer": {
    searchPlaceholder: "Tim hop dong chuyen nhuong, hoi vien, ma hop dong",
    createLabel: "Lap chuyen nhuong",
    filters: contractManagementFilters,
    columns: [
      { key: "customerName", label: "Thong tin hoi vien", minWidth: 220, wrap: true, multiline: true },
      { key: "code", label: "Thong tin hop dong", minWidth: 180, wrap: true, multiline: true },
      { key: "servicePackageName", label: "Goi dang chuyen", minWidth: 220, wrap: true, multiline: true },
      { key: "remainingSessions", label: "Tien do / so buoi", minWidth: 170, wrap: true, multiline: true },
      { key: "paymentStatus", label: "Thanh toan", type: "status", minWidth: 180, wrap: true, multiline: true },
    ],
    detailFields: ["code", "customerName", "customerPhone", "servicePackageName", "oldContractCode", "remainingSessions", "remainingValue", "amountDue", "paymentStatus", "status", "note"],
  },
  "operations-branch-transfer": {
    searchPlaceholder: "Tim hop dong dieu chuyen chi nhanh, hoi vien, goi dich vu",
    createLabel: "Lap chuyen chi nhanh",
    filters: contractManagementFilters,
    columns: [
      { key: "customerName", label: "Thong tin hoi vien", minWidth: 220, wrap: true, multiline: true },
      { key: "code", label: "Thong tin hop dong", minWidth: 180, wrap: true, multiline: true },
      { key: "servicePackageName", label: "Goi dang tap", minWidth: 220, wrap: true, multiline: true },
      { key: "endDate", label: "Thoi gian goi tap", type: "date", minWidth: 180, wrap: true, multiline: true },
      { key: "status", label: "Trang thai", type: "status", minWidth: 120, align: "center" },
    ],
    detailFields: ["code", "branchName", "customerName", "servicePackageName", "saleUserName", "trainerName", "startDate", "endDate", "remainingSessions", "amountDue", "paymentStatus", "status", "note"],
  },
  "operations-contract-cancel": {
    searchPlaceholder: "Tim hop dong da huy, hoi vien, goi dich vu",
    createLabel: "Lap huy",
    emptyStateTitle: "Chua co hop dong huy",
    emptyStateDescription: "Bo loc hien tai chua co hop dong nao duoc huy. Hay dieu chinh bo loc hoac lap giao dich huy moi.",
    filters: contractManagementFilters,
    defaultFilters: { status: "CANCELLED" },
    columns: [
      { key: "customerName", label: "Thong tin hoi vien", minWidth: 220, wrap: true, multiline: true },
      { key: "code", label: "Thong tin hop dong", minWidth: 180, wrap: true, multiline: true },
      { key: "servicePackageName", label: "Goi da huy", minWidth: 220, wrap: true, multiline: true },
      { key: "paymentStatus", label: "Thanh toan", type: "status", minWidth: 180, wrap: true, multiline: true },
      { key: "endDate", label: "Dong / gia tri chot", type: "date", minWidth: 180, wrap: true, multiline: true },
    ],
    detailFields: ["code", "customerName", "servicePackageName", "amountPaid", "amountDue", "remainingValue", "paymentStatus", "status", "endDate", "note"],
  },
  "operations-contract-conversion": {
    searchPlaceholder: "Tim hop dong chuyen doi, ma HD cu, hoi vien",
    createLabel: "Lap chuyen doi",
    filters: contractManagementFilters,
    columns: [
      { key: "customerName", label: "Thong tin hoi vien", minWidth: 220, wrap: true, multiline: true },
      { key: "code", label: "Thong tin hop dong", minWidth: 180, wrap: true, multiline: true },
      { key: "servicePackageName", label: "Goi hien tai", minWidth: 220, wrap: true, multiline: true },
      { key: "remainingSessions", label: "Tien do / so buoi", minWidth: 170, wrap: true, multiline: true },
      { key: "paymentStatus", label: "Thanh toan", type: "status", minWidth: 180, wrap: true, multiline: true },
    ],
    detailFields: ["code", "customerName", "servicePackageName", "oldContractCode", "remainingSessions", "remainingValue", "amountDue", "paymentStatus", "status", "note"],
  },
  "operations-lockers": {
    filters: lockerManagementFilters,
    columns: [
      { key: "code", label: "Ma tu", minWidth: 96 },
      { key: "name", label: "Ten tu", minWidth: 150 },
      { key: "label", label: "Nhan tu", minWidth: 96 },
      { key: "branchName", label: "Chi nhanh", minWidth: 130 },
      { key: "currentCustomerName", label: "Khach dang thue", minWidth: 170 },
      { key: "activeRentalCount", label: "Luot thue mo", minWidth: 96, align: "center" },
      { key: "price", label: "Don gia", type: "currency", minWidth: 120, align: "right" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "name", "label", "branchName", "currentCustomerName", "currentRentalCode", "rentalCount", "activeRentalCount", "price", "status", "note"],
  },
  "operations-locker-rentals": {
    searchPlaceholder: "Tim ma thue, hoi vien, ma tu, nhan tu",
    createLabel: "Lap thue tu",
    filters: lockerRentalManagementFilters,
    columns: [
      { key: "code", label: "Ma thue", minWidth: 110 },
      { key: "lockerDisplayName", label: "Tu do", minWidth: 150 },
      { key: "customerName", label: "Hoi vien", minWidth: 170 },
      { key: "startDate", label: "Tu ngay", type: "date", minWidth: 118 },
      { key: "endDate", label: "Den ngay", type: "date", minWidth: 118 },
      { key: "depositAmount", label: "Tien coc", type: "currency", minWidth: 120, align: "right" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "branchName", "lockerDisplayName", "customerName", "customerCode", "startDate", "endDate", "depositAmount", "processedByName", "status", "note"],
  },
  "operations-towel-issues": {
    searchPlaceholder: "Tim ma phieu, hoi vien, khan, hop dong, phieu thu",
    createLabel: "Lap phieu phat khan",
    emptyStateTitle: "Chua co luot phat / tra khan",
    emptyStateDescription: "Hay tao khan / vat tu dich vu truoc, sau do lap phieu phat khan de theo doi trang thai dang phat, da tra, mat / hu hoac dang giat.",
    emptyStateExamples: [
      "Vi du 1: Hoi vien Dang Quoc Huy | Vat tu TWL001 - Khan tap test | So luong 1 | Trang thai Dang phat",
      "Vi du 2: Sau khi tra khan, mo lai phieu va chuyen sang Da tra de so luong san sang tang lai",
    ],
    columns: [
      { key: "code", label: "Ma phieu", minWidth: 110 },
      { key: "productOptionLabel", label: "Khan / vat tu", minWidth: 180 },
      { key: "customerName", label: "Hoi vien", minWidth: 170 },
      { key: "contractCode", label: "Hop dong", minWidth: 118 },
      { key: "quantity", label: "SL", minWidth: 70, align: "center" },
      { key: "issueDate", label: "Ngay phat", type: "date", minWidth: 118 },
      { key: "dueDate", label: "Han tra", type: "date", minWidth: 118 },
      { key: "status", label: "Trang thai", type: "status", minWidth: 108, align: "center" },
    ],
    detailFields: ["code", "branchName", "productOptionLabel", "customerName", "contractCode", "receiptCode", "quantity", "issueDate", "dueDate", "returnDate", "handledByName", "status", "note"],
  },
  "deposits-page": {
    searchPlaceholder: "Tim ma phieu coc, hoi vien, ma thue tu",
    columns: [
      { key: "code", label: "Ma phieu", minWidth: 104 },
      { key: "customerName", label: "Khach nop coc", minWidth: 170 },
      { key: "lockerRentalCode", label: "Ma thue tu", minWidth: 120 },
      { key: "itemType", label: "Loai coc", minWidth: 120 },
      { key: "amount", label: "So tien", type: "currency", minWidth: 120, align: "right" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
      { key: "receivedAt", label: "Ngay nhan", type: "date", minWidth: 118 },
      { key: "returnedAt", label: "Ngay tra", type: "date", minWidth: 118 },
    ],
    detailFields: ["code", "itemType", "customerName", "lockerRentalCode", "branchName", "amount", "status", "receivedAt", "returnedAt", "note"],
  },
  "operations-towels": {
    searchPlaceholder: "Tim ma vat tu, ten vat tu, nhom cap phat",
    createLabel: "Them khan / vat tu",
    defaultFilters: { usageType: "TOWEL_SERVICE" },
    filters: productCatalogFilters,
    emptyStateTitle: "Chua co khan / vat tu dich vu",
    emptyStateDescription: "Man nay chi hien vat tu co loai su dung la Khan / vat tu dich vu hoac Dung chung. Hay them moi vat tu va chon dung loai truoc khi lap phieu phat / tra.",
    emptyStateExamples: [
      "Vi du 1: Ma TWL001 | Ten Khan tap test | Don vi cai | Loai Khan / vat tu dich vu",
      "Vi du 2: Ton kho 20 | Nguong toi thieu 5 | Gia nhap 12000 | Gia ban 25000",
      "Vi du 3: Sau khi tao xong, vao Phat / tra khan hoac Phieu thu -> Cho thue khan / vat tu de lap giao dich",
    ],
    columns: [
      { key: "code", label: "Ma vat tu", minWidth: 100 },
      { key: "name", label: "Ten vat tu", minWidth: 180 },
      { key: "branchName", label: "Chi nhanh", minWidth: 130 },
      { key: "groupName", label: "Nhom cap phat", minWidth: 120 },
      { key: "stockQuantity", label: "Tong so luong", minWidth: 96, align: "center" },
      { key: "availableTowelQuantity", label: "San sang", minWidth: 84, align: "center" },
      { key: "activeIssueQuantity", label: "Dang phat", minWidth: 84, align: "center" },
      { key: "laundryQuantity", label: "Dang giat", minWidth: 84, align: "center" },
      { key: "towelRentalQuantity", label: "SL thue luot", minWidth: 96, align: "center" },
      { key: "towelSaleQuantity", label: "SL da ban", minWidth: 90, align: "center" },
      { key: "salePrice", label: "Gia ban", type: "currency", minWidth: 120, align: "right" },
      { key: "purchasePrice", label: "Gia nhap", type: "currency", minWidth: 120, align: "right" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "name", "branchName", "categoryName", "groupName", "unit", "stockQuantity", "availableTowelQuantity", "activeIssueQuantity", "laundryQuantity", "lostQuantity", "damagedQuantity", "minStockQuantity", "stockAlertLabel", "towelRentalQuantity", "towelSaleQuantity", "towelRentalRevenue", "towelSaleRevenue", "salePrice", "purchasePrice", "lastPurchaseDate", "lastTowelReceiptDate", "status"],
  },
  "operations-product-groups": {
    searchPlaceholder: "Tim ten nhom, loai vat tu, chi nhanh",
    createLabel: "Them nhom hang",
    emptyStateTitle: "Chua co nhom hang",
    emptyStateDescription: "Hay tao nhom hang truoc, sau do quay lai man hinh Khan tap / vat tu hoac Pro Shop de gan vao tung mat hang.",
    emptyStateExamples: [
      "Vi du 1: Ten nhom Towel Service | Loai Khan / vat tu dich vu | Chi nhanh VNChoice",
      "Vi du 2: Ten nhom Accessory | Loai Ban le | Chi nhanh VNChoice",
    ],
    filters: [
      branchField,
      { name: "usageType", label: "Loai vat tu", type: "select", options: [
        { label: "Ban le", value: "RETAIL" },
        { label: "Khan / vat tu dich vu", value: "TOWEL_SERVICE" },
        { label: "Dung chung", value: "BOTH" },
      ] },
    ],
    columns: [
      { key: "name", label: "Ten nhom", minWidth: 180 },
      { key: "usageType", label: "Loai vat tu", minWidth: 140 },
      { key: "branchName", label: "Chi nhanh", minWidth: 140 },
      { key: "description", label: "Mo ta", minWidth: 260 },
      { key: "updatedAt", label: "Cap nhat", type: "date", minWidth: 120 },
    ],
    detailFields: ["name", "usageType", "branchName", "description", "createdDateTime", "updatedDateTime"],
  },
  "operations-loyalty": {
    searchPlaceholder: "Tim ma hoi vien, ten hoi vien, hang loyalty",
    createLabel: "Them ho so loyalty",
    filters: customerManagementFilters,
    defaultFilters: { status: "ACTIVE" },
    columns: [
      { key: "customerInfo", label: "Thong tin hoi vien", minWidth: 240, wrap: true, multiline: true },
      { key: "registrationDate", label: "Thong tin loyalty", type: "date", minWidth: 180, wrap: true, multiline: true },
      { key: "endTrainingDate", label: "Thoi gian uu dai", type: "date", minWidth: 180, wrap: true, multiline: true },
      { key: "outstandingDebt", label: "Cong no", type: "currency", minWidth: 120, align: "right" },
      { key: "otherInfo", label: "Uu dai / ghi chu", minWidth: 190, wrap: true, multiline: true },
    ],
    detailFields: ["code", "customerInfo", "membershipStatus", "branchName", "groupName", "assignedUserName", "registrationDate", "startTrainingDate", "endTrainingDate", "otherInfo", "outstandingDebt", "note"],
  },
  "pt-schedule-calendar": {
    searchPlaceholder: "Tim ma lich PT, hoi vien, PT, hop dong",
    createLabel: "Them lich PT",
    filters: trainingScheduleFilters,
    columns: [
      { key: "scheduledAt", label: "Lich tap", type: "date", minWidth: 120 },
      { key: "code", label: "Ma lich", minWidth: 104 },
      { key: "customerName", label: "Hoi vien", minWidth: 160 },
      { key: "trainerName", label: "PT", minWidth: 130 },
      { key: "contractCode", label: "Hop dong", minWidth: 120 },
      { key: "location", label: "Khu vuc", minWidth: 140 },
      { key: "attendanceCount", label: "Diem danh", minWidth: 88, align: "center" },
      { key: "attachmentCount", label: "Dinh kem", minWidth: 88, align: "center" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "scheduledDateTime", "branchName", "customerName", "customerPhone", "trainerName", "contractCode", "contractPackageName", "durationMinutes", "location", "status", "checkInDateTime", "attendanceCount", "presentCount", "attachmentCount", "outcome", "note"],
  },
  "pt-schedule-penalty-history": {
    searchPlaceholder: "Tim ma buoi, module, hanh dong penalty",
    filters: penaltyHistoryFilters,
    defaultFilters: { entityType: "training_session" },
    emptyStateTitle: "Chua co penalty nao",
    emptyStateDescription: "Bo loc hien tai chua ghi nhan penalty hay dieu chinh lich nao. Hay doi khoang thoi gian hoac hanh dong de tiep tuc kiem tra.",
    columns: [
      { key: "createdAt", label: "Thoi gian", type: "date", minWidth: 120 },
      { key: "module", label: "Mo-dun", minWidth: 120 },
      { key: "action", label: "Hanh dong penalty", type: "status", minWidth: 132, align: "center" },
      { key: "entityType", label: "Doi tuong lien quan", minWidth: 148 },
      { key: "entityId", label: "Ma tham chieu", minWidth: 140 },
      { key: "ipAddress", label: "Nguon truy cap", minWidth: 140 },
    ],
    detailFields: ["module", "action", "entityType", "entityId", "ipAddress", "userAgent", "beforeData", "afterData", "metadata", "createdAt"],
  },
  "class-schedule-bookings": {
    searchPlaceholder: "Tim booking, hoi vien, PT, line, khu vuc",
    createLabel: "Them booking",
    filters: trainingScheduleFilters,
    columns: [
      { key: "scheduledAt", label: "Lich dat", type: "date", minWidth: 120 },
      { key: "code", label: "Ma booking", minWidth: 110 },
      { key: "customerName", label: "Hoi vien", minWidth: 160 },
      { key: "trainerName", label: "PT phu trach", minWidth: 140 },
      { key: "location", label: "Line / Khu vuc", minWidth: 150 },
      { key: "attendanceCount", label: "Diem danh", minWidth: 88, align: "center" },
      { key: "attachmentCount", label: "Dinh kem", minWidth: 88, align: "center" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "status", "trainerName", "contractCode", "contractPackageName", "location", "attendanceCount", "attachmentCount", "note"],
  },
  "class-schedule-classes": {
    searchPlaceholder: "Tim lop, goi class, line, dich vu",
    createLabel: "Them lop",
    filters: servicePackageCatalogFilters,
    columns: [
      { key: "code", label: "Ma lop", minWidth: 96 },
      { key: "name", label: "Ten lop", minWidth: 170 },
      { key: "serviceName", label: "Dich vu", minWidth: 150 },
      { key: "serviceCategory", label: "Nhom line", minWidth: 110 },
      { key: "packageType", label: "Loai goi", minWidth: 100 },
      { key: "sessionLabel", label: "So buoi", minWidth: 100, align: "center" },
      { key: "price", label: "Gia", type: "currency", minWidth: 120, align: "right" },
      { key: "contractCount", label: "So dang ky", minWidth: 92, align: "center" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "name", "serviceName", "packageType", "totalSessions", "price", "remainingValueRule", "status", "description"],
  },
  "class-schedule-timetable": {
    searchPlaceholder: "Tim lich lop, line, PT, khu vuc",
    createLabel: "Xep lich lop",
    filters: trainingScheduleFilters,
    columns: [
      { key: "scheduledAt", label: "Khung gio", type: "date", minWidth: 120 },
      { key: "code", label: "Ma lich", minWidth: 104 },
      { key: "trainerName", label: "Huong dan", minWidth: 140 },
      { key: "location", label: "Line / Phong", minWidth: 150 },
      { key: "customerName", label: "Booking chinh", minWidth: 160 },
      { key: "attendanceCount", label: "Diem danh", minWidth: 88, align: "center" },
      { key: "presentCount", label: "Co mat", minWidth: 78, align: "center" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "status", "trainerName", "location", "attendanceCount", "presentCount", "attachmentCount", "outcome", "note"],
  },
  "class-schedule-group-pt": {
    searchPlaceholder: "Tim lich PT nhom, PT, hoi vien, khu vuc",
    createLabel: "Them lich PT nhom",
    filters: trainingScheduleFilters,
    columns: [
      { key: "scheduledAt", label: "Lich PT nhom", type: "date", minWidth: 120 },
      { key: "code", label: "Ma lich", minWidth: 104 },
      { key: "trainerName", label: "PT", minWidth: 140 },
      { key: "location", label: "Khu vuc", minWidth: 150 },
      { key: "attendanceCount", label: "So booking", minWidth: 88, align: "center" },
      { key: "presentCount", label: "Co mat", minWidth: 78, align: "center" },
      { key: "consumedSessions", label: "Tru buoi", minWidth: 82, align: "center" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "status", "trainerName", "location", "attendanceCount", "presentCount", "consumedSessions", "attachmentCount", "outcome", "note"],
  },
  "class-schedule-line-categories": {
    searchPlaceholder: "Tim line, nhom lop, khu vuc, ma line",
    createLabel: "Them line",
    filters: serviceCatalogFilters,
    defaultFilters: { category: "class" },
    columns: [
      { key: "code", label: "Ma line", minWidth: 96 },
      { key: "name", label: "Ten line", minWidth: 170 },
      { key: "category", label: "Nhom", minWidth: 110 },
      { key: "branchName", label: "Chi nhanh", minWidth: 130 },
      { key: "packageCount", label: "So lop", minWidth: 82, align: "center" },
      { key: "activePackageCount", label: "Dang mo", minWidth: 82, align: "center" },
      { key: "contractItemCount", label: "Luot dung", minWidth: 86, align: "center" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "name", "status", "branchName", "defaultSessions", "defaultPrice", "durationDays", "description"],
  },
  "class-schedule-line-schedule": {
    searchPlaceholder: "Tim lich line, khu vuc, PT, booking",
    filters: trainingScheduleFilters,
    columns: [
      { key: "scheduledAt", label: "Lich line", type: "date", minWidth: 120 },
      { key: "code", label: "Ma lich", minWidth: 104 },
      { key: "location", label: "Line / Khu vuc", minWidth: 150 },
      { key: "trainerName", label: "Huong dan", minWidth: 140 },
      { key: "attendanceCount", label: "Booking", minWidth: 82, align: "center" },
      { key: "presentCount", label: "Co mat", minWidth: 78, align: "center" },
      { key: "attachmentCount", label: "Dinh kem", minWidth: 88, align: "center" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "status", "scheduledDateTime", "location", "trainerName", "presentCount", "attachmentCount", "outcome", "note"],
  },
  "class-schedule-line-layout": {
    searchPlaceholder: "Tim so do line, chi nhanh, khu vuc",
    columns: [
      { key: "code", label: "Ma CN", minWidth: 92 },
      { key: "name", label: "Chi nhanh / So do", minWidth: 170 },
      { key: "address", label: "Dia chi", minWidth: 220 },
      { key: "operatingHours", label: "Khung gio hoat dong", minWidth: 150 },
      { key: "maxBookingsPerDay", label: "Luot dat/ngay", minWidth: 110, align: "center" },
      { key: "requiresDepositLabel", label: "Yeu cau coc", minWidth: 110 },
      { key: "userCount", label: "Nhan vien", minWidth: 82, align: "center" },
      { key: "attendanceMachineCount", label: "May cham cong", minWidth: 110, align: "center" },
    ],
    detailFields: ["code", "name", "address", "operatingHours", "maxBookingsPerDay", "maxDepositHours", "requiresDepositLabel", "note"],
  },
  "class-schedule-booking-attachments": {
    searchPlaceholder: "Tim booking, hoi vien, PT, tep dinh kem",
    filters: trainingScheduleFilters,
    columns: [
      { key: "scheduledAt", label: "Thoi diem", type: "date", minWidth: 120 },
      { key: "code", label: "Ma booking", minWidth: 110 },
      { key: "customerName", label: "Hoi vien", minWidth: 160 },
      { key: "trainerName", label: "PT", minWidth: 140 },
      { key: "location", label: "Khu vuc", minWidth: 150 },
      { key: "attachmentCount", label: "So tep", minWidth: 82, align: "center" },
      { key: "attendanceCount", label: "Diem danh", minWidth: 88, align: "center" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "status", "scheduledDateTime", "trainerName", "contractCode", "location", "attachmentCount", "note"],
  },
  "staff-users": {
    filters: userManagementFilters,
    columns: [
      { key: "staffInfo", label: "Thong tin nhan vien", minWidth: 220, wrap: true, multiline: true },
      { key: "staffWorkInfo", label: "Cong viec", minWidth: 180, wrap: true, multiline: true, hideOnMobile: true, hideOnTablet: true },
      { key: "staffRolesInfo", label: "Vai tro", minWidth: 220, wrap: true, multiline: true, hideOnMobile: true },
      { key: "staffAccountInfo", label: "Tai khoan", minWidth: 160, wrap: true, multiline: true },
    ],
    detailFields: ["employeeCode", "attendanceCode", "fullName", "username", "branchName", "title", "roleNames", "permissionCount", "lastLoginDateTime", "email", "phone", "status", "createdDateTime", "updatedDateTime"],
  },
  "staff-exercise-library": {
    filters: productCatalogFilters,
    columns: [
      { key: "code", label: "Ma bai tap", minWidth: 100 },
      { key: "name", label: "Ten bai tap / dung cu", minWidth: 200 },
      { key: "categoryName", label: "Danh muc", minWidth: 130 },
      { key: "groupName", label: "Nhom", minWidth: 120 },
      { key: "unit", label: "Don vi", minWidth: 90 },
      { key: "stockQuantity", label: "So luong", minWidth: 86, align: "center" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "name", "status", "categoryName", "groupName", "unit", "branchName"],
  },
  "staff-stages": {
    columns: [
      { key: "code", label: "Ma stage", minWidth: 100 },
      { key: "name", label: "Ten stage", minWidth: 170 },
      { key: "roleType", label: "Loai", minWidth: 100, align: "center" },
      { key: "userCount", label: "So nhan vien", minWidth: 92, align: "center" },
      { key: "permissionCount", label: "So quyen", minWidth: 86, align: "center" },
      { key: "description", label: "Mo ta", minWidth: 240 },
    ],
    detailFields: ["code", "name", "description", "roleType", "createdDateTime", "updatedDateTime"],
  },
  "staff-programs": {
    filters: trainerCatalogFilters,
    columns: [
      { key: "code", label: "Ma giao an", minWidth: 100 },
      { key: "fullName", label: "PT phu trach", minWidth: 170 },
      { key: "branchName", label: "Chi nhanh", minWidth: 130 },
      { key: "specialty", label: "Chuyen mon", minWidth: 150 },
      { key: "activeContractCount", label: "Hoc vien dang theo", minWidth: 100, align: "center" },
      { key: "upcomingSessionCount", label: "Lich sap toi", minWidth: 96, align: "center" },
      { key: "completedSessionCount", label: "Da hoan thanh", minWidth: 96, align: "center" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "status", "fullName", "branchName", "specialty", "upcomingSessionCount", "completedSessionCount", "nextSessionDateTime", "note"],
  },
  "staff-attendance-adjustments": {
    filters: staffAttendanceAdjustmentFilters,
    columns: [
      { key: "eventDate", label: "Ngay", type: "date", minWidth: 110 },
      { key: "eventTime", label: "Gio", minWidth: 82, align: "center" },
      { key: "staffCode", label: "Ma NV", minWidth: 96 },
      { key: "staffName", label: "Nhan vien", minWidth: 170 },
      { key: "branchName", label: "Chi nhanh", minWidth: 130 },
      { key: "eventType", label: "Loai su kien", type: "status", minWidth: 118, align: "center" },
      { key: "source", label: "Nguon", type: "status", minWidth: 104, align: "center" },
      { key: "verificationMethod", label: "Xac thuc", type: "status", minWidth: 118, align: "center" },
      { key: "machineName", label: "May cham cong", minWidth: 150 },
    ],
    detailFields: ["staffCode", "attendanceCode", "username", "staffName", "staffTitle", "roleNames", "branchName", "rawCode", "note"],
  },
  "cashbook-receipts": {
    filters: paymentVoucherFilters,
    columns: [
      { key: "receiptDate", label: "Ngay thu", type: "date", minWidth: 110 },
      { key: "code", label: "Ma phieu", minWidth: 104 },
      { key: "customerName", label: "Khach hang", minWidth: 170 },
      { key: "contractCode", label: "Hop dong", minWidth: 120 },
      { key: "paymentMethodName", label: "Phuong thuc", minWidth: 130 },
      { key: "collectorName", label: "Nguoi thu", minWidth: 130 },
      { key: "sourceLabel", label: "Nguon thu", minWidth: 130 },
      { key: "amount", label: "So tien", type: "currency", minWidth: 120, align: "right" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "receiptDate", "branchName", "customerName", "customerPhone", "contractCode", "contractPackageName", "paymentMethodName", "collectorName", "sourceLabel", "itemCount", "totalQuantity", "productSummary", "amount", "status", "content", "note"],
  },
  "cashbook-expenses": {
    filters: paymentVoucherFilters,
    columns: [
      { key: "expenseDate", label: "Ngay chi", type: "date", minWidth: 110 },
      { key: "code", label: "Ma phieu", minWidth: 104 },
      { key: "payeeName", label: "Doi tuong nhan", minWidth: 170 },
      { key: "expenseLabel", label: "Loai chi", minWidth: 150 },
      { key: "paymentMethodName", label: "Phuong thuc", minWidth: 130 },
      { key: "approverName", label: "Nguoi phe duyet", minWidth: 140 },
      { key: "createdUserName", label: "Nguoi lap", minWidth: 130 },
      { key: "amount", label: "So tien", type: "currency", minWidth: 120, align: "right" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "expenseDate", "branchName", "payeeName", "expenseType", "expenseLabel", "paymentMethodName", "approverName", "createdUserName", "itemCount", "totalQuantity", "productSummary", "amount", "status", "note"],
  },
  "pro-shop-products": {
    defaultFilters: { usageType: "RETAIL" },
    filters: productCatalogFilters,
    columns: [
      { key: "code", label: "Ma san pham", minWidth: 100 },
      { key: "name", label: "Ten san pham", minWidth: 180 },
      { key: "branchName", label: "Chi nhanh", minWidth: 130 },
      { key: "categoryName", label: "Danh muc", minWidth: 130 },
      { key: "groupName", label: "Nhom", minWidth: 120 },
      { key: "stockQuantity", label: "Ton kho", minWidth: 86, align: "center" },
      { key: "stockValue", label: "Gia tri ton", type: "currency", minWidth: 120, align: "right" },
      { key: "salePrice", label: "Gia ban", type: "currency", minWidth: 120, align: "right" },
      { key: "stockAlertLabel", label: "Canh bao ton", minWidth: 120 },
    ],
    detailFields: ["code", "name", "branchName", "categoryName", "groupName", "unit", "purchasePrice", "salePrice", "stockQuantity", "minStockQuantity", "stockAlertLabel", "stockValue", "purchaseItemCount", "purchaseOrderCount", "lastPurchaseDate", "status"],
  },
  "pro-shop-partners": {
    filters: supplierCatalogFilters,
    columns: [
      { key: "code", label: "Ma doi tac", minWidth: 100 },
      { key: "name", label: "Ten doi tac", minWidth: 180 },
      { key: "branchName", label: "Chi nhanh", minWidth: 130 },
      { key: "contactName", label: "Nguoi lien he", minWidth: 150 },
      { key: "phone", label: "Dien thoai", minWidth: 120 },
      { key: "purchaseOrderCount", label: "So phieu nhap", minWidth: 90, align: "center" },
      { key: "completedPurchaseOrderCount", label: "Da hoan thanh", minWidth: 96, align: "center" },
      { key: "totalPurchaseAmount", label: "Gia tri nhap", type: "currency", minWidth: 120, align: "right" },
      { key: "lastOrderDate", label: "Lan nhap gan nhat", type: "date", minWidth: 110 },
    ],
    detailFields: ["code", "name", "branchName", "contactName", "phone", "email", "address", "purchaseOrderCount", "completedPurchaseOrderCount", "totalPurchaseAmount", "lastOrderDate", "note"],
  },
  "pro-shop-price-book": {
    defaultFilters: { usageType: "RETAIL" },
    filters: productCatalogFilters,
    columns: [
      { key: "code", label: "Ma san pham", minWidth: 100 },
      { key: "name", label: "Ten san pham", minWidth: 180 },
      { key: "groupName", label: "Nhom", minWidth: 120 },
      { key: "branchName", label: "Chi nhanh", minWidth: 130 },
      { key: "purchasePrice", label: "Gia nhap", type: "currency", minWidth: 120, align: "right" },
      { key: "salePrice", label: "Gia ban", type: "currency", minWidth: 120, align: "right" },
      { key: "stockQuantity", label: "Ton kho", minWidth: 86, align: "center" },
      { key: "stockAlertLabel", label: "Canh bao ton", minWidth: 120 },
    ],
    detailFields: ["code", "name", "branchName", "categoryName", "groupName", "unit", "purchasePrice", "salePrice", "stockQuantity", "minStockQuantity", "stockAlertLabel", "lastPurchaseDate", "status"],
  },
  "pro-shop-sales": {
    filters: paymentVoucherFilters,
    columns: [
      { key: "receiptDate", label: "Ngay ban", type: "date", minWidth: 110 },
      { key: "code", label: "Ma giao dich", minWidth: 110 },
      { key: "customerName", label: "Khach mua", minWidth: 170 },
      { key: "productSummary", label: "San pham", minWidth: 190 },
      { key: "totalQuantity", label: "SL", minWidth: 76, align: "center" },
      { key: "paymentMethodName", label: "Thanh toan", minWidth: 130 },
      { key: "collectorName", label: "Thu ngan", minWidth: 130 },
      { key: "amount", label: "Tong tien", type: "currency", minWidth: 120, align: "right" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "branchName", "customerName", "customerPhone", "paymentMethodName", "collectorName", "itemCount", "totalQuantity", "productSummary", "amount", "status", "content", "note"],
  },
  "pro-shop-returns": {
    filters: paymentVoucherFilters,
    columns: [
      { key: "expenseDate", label: "Ngay tra", type: "date", minWidth: 110 },
      { key: "code", label: "Ma phieu tra", minWidth: 110 },
      { key: "payeeName", label: "Khach nhan hoan", minWidth: 170 },
      { key: "productSummary", label: "San pham", minWidth: 190 },
      { key: "totalQuantity", label: "SL", minWidth: 76, align: "center" },
      { key: "paymentMethodName", label: "Thanh toan", minWidth: 130 },
      { key: "approverName", label: "Phe duyet", minWidth: 130 },
      { key: "amount", label: "Tong hoan", type: "currency", minWidth: 120, align: "right" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "branchName", "payeeName", "paymentMethodName", "approverName", "createdUserName", "itemCount", "totalQuantity", "productSummary", "amount", "status", "note"],
  },
  "pro-shop-purchase-orders": {
    filters: purchaseOrderManagementFilters,
    columns: [
      { key: "orderDate", label: "Ngay nhap", type: "date", minWidth: 110 },
      { key: "code", label: "Ma phieu", minWidth: 104 },
      { key: "supplierName", label: "Nha cung cap", minWidth: 180 },
      { key: "productSummary", label: "San pham", minWidth: 200 },
      { key: "totalQuantity", label: "Tong SL", minWidth: 82, align: "center" },
      { key: "itemCount", label: "So dong", minWidth: 82, align: "center" },
      { key: "createdUserName", label: "Nguoi lap", minWidth: 130 },
      { key: "totalAmount", label: "Tong tien", type: "currency", minWidth: 120, align: "right" },
      { key: "status", label: "Trang thai", type: "status", minWidth: 104, align: "center" },
    ],
    detailFields: ["code", "orderDate", "expectedDate", "branchName", "supplierName", "createdUserName", "productSummary", "itemCount", "totalQuantity", "totalAmount", "status", "note"],
  },
  "settings-users": {
    filters: userManagementFilters,
    columns: [
      { key: "staffInfo", label: "Thong tin tai khoan", minWidth: 220, wrap: true, multiline: true },
      { key: "staffWorkInfo", label: "Cong viec", minWidth: 180, wrap: true, multiline: true, hideOnMobile: true, hideOnTablet: true },
      { key: "staffRolesInfo", label: "Vai tro", minWidth: 220, wrap: true, multiline: true, hideOnMobile: true },
      { key: "staffAccountInfo", label: "Trang thai truy cap", minWidth: 160, wrap: true, multiline: true },
    ],
    detailFields: ["employeeCode", "attendanceCode", "username", "fullName", "branchName", "email", "phone", "title", "roleNames", "permissionCount", "lastLoginDateTime", "status", "avatarUrl", "createdDateTime", "updatedDateTime"],
  },
  "settings-branches": {
    columns: [
      { key: "code", label: "Ma CN", minWidth: 92 },
      { key: "name", label: "Ten chi nhanh", minWidth: 170 },
      { key: "operatingHours", label: "Khung gio hoat dong", minWidth: 150 },
      { key: "phone", label: "Dien thoai", minWidth: 120 },
      { key: "email", label: "Email", minWidth: 180 },
      { key: "userCount", label: "Nhan vien", minWidth: 82, align: "center" },
      { key: "customerCount", label: "Hoi vien", minWidth: 82, align: "center" },
      { key: "trainerCount", label: "PT", minWidth: 70, align: "center" },
      { key: "attendanceMachineCount", label: "May cham cong", minWidth: 110, align: "center" },
    ],
    detailFields: ["code", "name", "phone", "email", "operatingHours", "address", "maxDepositHours", "maxBookingsPerDay", "requiresDepositLabel", "logoUrl", "userCount", "customerCount", "trainerCount", "attendanceMachineCount", "note", "createdDateTime", "updatedDateTime"],
  },
  "settings-audit-logs": {
    filters: auditLogFilters,
    columns: [
      { key: "createdAt", label: "Thoi gian", type: "date", minWidth: 120 },
      { key: "module", label: "Mo-dun", minWidth: 120 },
      { key: "action", label: "Hanh dong", type: "status", minWidth: 104, align: "center" },
      { key: "entityType", label: "Doi tuong", minWidth: 130 },
      { key: "entityId", label: "Ma tham chieu", minWidth: 140 },
      { key: "ipAddress", label: "IP", minWidth: 120 },
    ],
    detailFields: ["module", "action", "entityType", "entityId", "ipAddress", "userAgent", "beforeData", "afterData", "metadata", "createdAt"],
  },
  "settings-attendance-machines": {
    filters: [
      branchField,
      { name: "status", label: "Trang thai", type: "select", options: [...attendanceMachineStatusOptions] },
    ],
    columns: [
      { key: "code", label: "Ma may", minWidth: 90 },
      { key: "name", label: "Ten may", minWidth: 138, wrap: true, multiline: true },
      { key: "vendor", label: "Vendor", minWidth: 92 },
      { key: "machineType", label: "Loai may", minWidth: 88, wrap: true },
      { key: "protocol", label: "Giao thuc", minWidth: 102, wrap: true, multiline: true },
      { key: "branchName", label: "Chi nhanh", minWidth: 112, wrap: true, multiline: true },
      { key: "host", label: "IP / Domain", minWidth: 118, wrap: true, multiline: true },
      { key: "connectionPort", label: "Cong ket noi", minWidth: 86, align: "center" },
      { key: "syncLabel", label: "Dong bo", minWidth: 86, wrap: true },
      { key: "eventCount", label: "So su kien", minWidth: 74, align: "center" },
      { key: "lastSyncedDateTime", label: "Lan dong bo cuoi", type: "date", minWidth: 108 },
      { key: "connectionStatus", label: "Trang thai", type: "status", minWidth: 92, align: "center" },
    ],
    detailFields: ["code", "name", "vendor", "machineType", "protocol", "model", "deviceIdentifier", "branchName", "host", "connectionPort", "username", "commKeyStatus", "timeZone", "pollingIntervalSeconds", "supportsCardEnrollment", "supportsFaceImage", "supportsFingerprintTemplate", "supportsWebhook", "syncLabel", "connectionStatus", "lastHeartbeatDateTime", "lastErrorMessage"],
  },
};

const settingPageOverrides: Record<
  string,
  Partial<
    Pick<
      SettingDefinition,
      "searchPlaceholder" | "createLabel" | "emptyStateTitle" | "emptyStateDescription" | "noticeTitle" | "noticeDescription"
    >
  >
> = {
  "staff-program-templates": {
    searchPlaceholder: "Tim ten mau, tieu de, kenh gui",
    createLabel: "Them mau dung chung",
    emptyStateTitle: "Chua co template dung chung",
    emptyStateDescription: "Thu vien template hien chua co ban ghi nao phu hop voi bo loc hien tai.",
    noticeTitle: "Nguon du lieu dung chung",
    noticeDescription: "Route template giao an hien tam thoi dung chung kho template he thong. Khi backend giao an mau san sang, man hinh nay se duoc tach rieng.",
  },
};


export const getMenuItemByPath = (pathname: string) => {
  const directItem = getAllMenuItems().find((item) => isMenuItemActive(pathname, item.href));
  if (directItem) return directItem;

  const pageKey = pathname.replace(/^\//, "");
  const page = portalPageRegistry[pageKey];

  if (page?.title) {
    return {
      label: page.title,
      href: pathname,
      description: page.subtitle,
    };
  }

  return getMenuGroupByPath(pathname)?.items[0];
};

export const getViewPermissionForPath = (pathname: string) => {
  const slug = pathname.replace(/^\//, "").split("/").filter(Boolean);
  const page = resolvePortalPage(slug);

  if (!page) {
    return undefined;
  }

  if (page.kind === "dashboard") {
    return "dashboard.view";
  }

  if (page.kind === "setting") {
    return "settings.view";
  }

  if (page.kind === "resource") {
    return `${page.resource.permissionPrefix}.view`;
  }

  return page.report.permission || "reports.view";
};

export const resolvePortalPage = (slug: string[]) => {
  const key = slug.filter(Boolean).join("/") || "dashboard";
  const page = portalPageRegistry[key];

  if (!page) return null;

  if (page.kind === "dashboard") {
    return {
      kind: "dashboard" as const,
      title: page.title || "Dashboard tong quan",
      subtitle: page.subtitle || "Tong hop van hanh he thong.",
    };
  }

  if (page.kind === "resource" && page.resourceKey) {
    const pageOverrides = resourcePageOverrides[page.key] || {};
    return {
      kind: "resource" as const,
      resource: cloneResourceDefinition(page.key, page.resourceKey, {
        ...pageOverrides,
        title: page.title || pageOverrides.title,
        subtitle: page.subtitle || pageOverrides.subtitle,
      }),
    };
  }

  if (page.kind === "report" && page.reportKey) {
    return {
      kind: "report" as const,
      report: cloneReportDefinition(page.key, page.reportKey, {
        title: page.title,
        subtitle: page.subtitle,
      }),
    };
  }

  if (page.kind === "setting" && page.settingKey) {
    const pageOverrides = settingPageOverrides[page.key] || {};
    return {
      kind: "setting" as const,
      setting: cloneSettingDefinition(page.key, page.settingKey, {
        ...pageOverrides,
        title: page.title,
        subtitle: page.subtitle,
      }),
    };
  }

  return null;
};
