import { ResourceDefinition } from "@/types/portal";

const branchField = {
  name: "branchId",
  label: "Chi nhanh",
  type: "select",
  required: true,
  optionsEndpoint: "/branches",
  optionLabelKey: "name",
  optionValueKey: "id",
} as const;

const optionalSettingBranchField = {
  ...branchField,
  required: false,
} as const;

const marketingChannelOptions = [
  { label: "Zalo", value: "ZALO" },
  { label: "SMS", value: "SMS" },
  { label: "Email", value: "EMAIL" },
] as const;

const roundingModeOptions = [{ label: "Gan nhat", value: "NEAREST" }] as const;

const receiptPayerKindOptions = [
  { label: "Hoi vien / hop dong", value: "MEMBER" },
  { label: "Khach le", value: "GUEST" },
] as const;

const receiptSourceOptions = [
  { label: "Thu hop dong / goi tap", value: "contract" },
  { label: "Ban san pham / Shop", value: "PRODUCT_SALE" },
  { label: "Cho thue khan / vat tu", value: "TOWEL_RENTAL" },
  { label: "Ban khan / vat tu", value: "TOWEL_SALE" },
  { label: "The luot / ve ngay", value: "card" },
  { label: "Tien coc", value: "deposit" },
  { label: "Thu khac", value: "other" },
] as const;

const productUsageTypeOptions = [
  { label: "Ban le", value: "RETAIL" },
  { label: "Khan / vat tu dich vu", value: "TOWEL_SERVICE" },
  { label: "Dung chung", value: "BOTH" },
] as const;

const towelIssueStatusOptions = [
  { label: "Dang phat", value: "ISSUED" },
  { label: "Da tra", value: "RETURNED" },
  { label: "Mat", value: "LOST" },
  { label: "Hu", value: "DAMAGED" },
  { label: "Dang giat", value: "LAUNDRY" },
] as const;

export const resourceRegistry: Record<string, ResourceDefinition> = {
  customers: {
    key: "customers",
    title: "Khach hang / Hoi vien",
    subtitle: "Quan ly hoi vien, hop dong, cong no va thong tin lien he day du theo ho so hoi vien.",
    searchPlaceholder: "Tim ma, ho ten, dien thoai hoi vien",
    endpoint: "/customers",
    permissionPrefix: "customers",
    columns: [
      { key: "customerInfo", label: "Thong tin hoi vien", minWidth: 240, wrap: true, multiline: true },
      { key: "membershipStatus", label: "Trang thai", type: "status", minWidth: 108, align: "center" },
      { key: "registrationDate", label: "Thong tin dang ky", type: "date", minWidth: 180, wrap: true, multiline: true },
      { key: "endTrainingDate", label: "Thoi gian goi tap", type: "date", minWidth: 180, wrap: true, multiline: true },
      { key: "otherInfo", label: "Thong tin khac", minWidth: 210, wrap: true, multiline: true },
    ],
    filters: [
      branchField,
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Active", value: "ACTIVE" }, { label: "Prospect", value: "PROSPECT" }, { label: "Inactive", value: "INACTIVE" }, { label: "Suspended", value: "SUSPENDED" }, { label: "Expired", value: "EXPIRED" }] },
      { name: "dateFrom", label: "Tu ngay", type: "date" },
      { name: "dateTo", label: "Den ngay", type: "date" },
    ],
    fields: [
      branchField,
      { name: "groupId", label: "Nhom khach hang", type: "select", optionsEndpoint: "/customer-groups", optionLabelKey: "name", optionValueKey: "id" },
      { name: "contactName", label: "Nguoi lien he", type: "text", placeholder: "Nhap nguoi lien he" },
      { name: "fullName", label: "Ho va ten", type: "text", required: true, placeholder: "Nhap ho va ten khach hang" },
      { name: "birthDate", label: "Ngay sinh", type: "date" },
      { name: "contactPhone", label: "SDT lien he", type: "phone", placeholder: "Nhap so dien thoai nguoi lien he" },
      { name: "code", label: "Ma khach hang", type: "text", required: true, placeholder: "Ma hoi vien / ma khach hang" },
      { name: "customerCardNumber", label: "The khach hang", type: "text", placeholder: "Nhap so the khach hang" },
      { name: "identityNumber", label: "CMND / CCCD", type: "text", placeholder: "Nhap so giay to" },
      { name: "fingerprintCode", label: "Ma cham cong", type: "text", placeholder: "Ma cham cong hoi vien / ma tren may" },
      { name: "email", label: "Email", type: "email", placeholder: "Nhap email" },
      { name: "identityIssueDate", label: "Ngay cap", type: "date" },
      { name: "phone", label: "So dien thoai", type: "phone", placeholder: "Nhap so dien thoai" },
      {
        name: "gender",
        label: "Gioi tinh",
        type: "select",
        options: [
          { label: "Nam", value: "MALE" },
          { label: "Nu", value: "FEMALE" },
          { label: "Khac", value: "OTHER" },
        ],
      },
      { name: "identityIssuePlace", label: "Noi cap", type: "text", placeholder: "Noi cap giay to" },
      { name: "assignedToId", label: "NV phu trach", type: "select", optionsEndpoint: "/users", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "sourceId", label: "Nguon khach", type: "select", optionsEndpoint: "/customer-sources", optionLabelKey: "name", optionValueKey: "id" },
      { name: "occupation", label: "Nganh nghe", type: "text", placeholder: "Nghe nghiep / nganh nghe" },
      { name: "referralName", label: "Nguoi gioi thieu", type: "text", placeholder: "Nguoi gioi thieu" },
      { name: "phoneSecondary", label: "So dien thoai 2", type: "phone", placeholder: "So dien thoai phu" },
      { name: "phoneTertiary", label: "So dien thoai 3", type: "phone", placeholder: "So dien thoai 3" },
      { name: "city", label: "Tinh / Thanh pho", type: "text", placeholder: "Tinh / thanh pho" },
      { name: "district", label: "Quan / Huyen", type: "text", placeholder: "Quan / huyen" },
      { name: "ward", label: "Phuong / Xa", type: "text", placeholder: "Phuong / xa" },
      { name: "address", label: "Thon, xom, so nha / Dia chi", type: "textarea", span: 3, placeholder: "Nhap dia chi chi tiet" },
      { name: "registrationDate", label: "Ngay dang ky", type: "date", required: true },
      { name: "startTrainingDate", label: "Ngay bat dau tap", type: "date" },
      { name: "endTrainingDate", label: "Ngay het han tap", type: "date" },
      {
        name: "membershipStatus",
        label: "Trang thai",
        type: "select",
        options: [
          { label: "Prospect", value: "PROSPECT" },
          { label: "Active", value: "ACTIVE" },
          { label: "Inactive", value: "INACTIVE" },
          { label: "Suspended", value: "SUSPENDED" },
          { label: "Expired", value: "EXPIRED" },
        ],
      },
      { name: "cardCovid", label: "The / Covid", type: "text", placeholder: "So the / thong tin covid" },
      { name: "profileCount", label: "So ho so", type: "number", placeholder: "1" },
      { name: "otherInfo", label: "Thong tin khac", type: "textarea", span: 3, placeholder: "Thong tin bo sung cho ho so hoi vien" },
      { name: "serviceNote", label: "Ghi chu dich vu", type: "textarea", span: 3, placeholder: "Ghi chu lien quan goi tap / yeu cau dich vu" },
      { name: "note", label: "Ghi chu", type: "textarea", span: 3, placeholder: "Ghi chu noi bo" },
    ],
    detailFields: [
      "code",
      "fingerprintCode",
      "fullName",
      "customerInfo",
      "membershipStatus",
      "registrationDate",
      "startTrainingDate",
      "endTrainingDate",
      "fullAddress",
      "branchName",
      "groupName",
      "contactName",
      "profileCount",
      "outstandingDebt",
      "note",
    ],
  },
  leads: {
    key: "leads",
    title: "Lead / CRM",
    subtitle: "Pipeline lead, lich hen, nguon lead va ket qua cham soc.",
    searchPlaceholder: "Tim ma lead, ho ten, so dien thoai",
    endpoint: "/leads",
    permissionPrefix: "leads",
    columns: [
      { key: "code", label: "Ma lead" },
      { key: "fullName", label: "Ho ten" },
      { key: "sourceName", label: "Nguon lead" },
      { key: "assignedUserName", label: "Phu trach" },
      { key: "status", label: "Trang thai", type: "status" },
      { key: "followUpState", label: "Follow-up", type: "status" },
      { key: "potentialLevel", label: "Muc do", type: "status" },
      { key: "nextFollowUpAt", label: "Hen tiep theo", type: "date" },
      { key: "budgetExpected", label: "Budget", type: "currency" },
    ],
    filters: [
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Moi", value: "NEW" }, { label: "Tu van", value: "CONSULTING" }, { label: "Da hen", value: "APPOINTED" }, { label: "Da chuyen doi", value: "CONVERTED" }] },
      { name: "dateFrom", label: "Tu ngay", type: "date" },
      { name: "dateTo", label: "Den ngay", type: "date" },
    ],
    fields: [
      branchField,
      { name: "sourceId", label: "Nguon lead", type: "select", optionsEndpoint: "/lead-sources", optionLabelKey: "name", optionValueKey: "id" },
      { name: "assignedToId", label: "Nhan vien phu trach", type: "select", optionsEndpoint: "/users", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "code", label: "Ma lead", type: "text", required: true },
      { name: "fullName", label: "Ho ten", type: "text", required: true },
      { name: "phone", label: "Dien thoai", type: "phone" },
      { name: "email", label: "Email", type: "email" },
      { name: "campaign", label: "Chien dich", type: "text" },
      { name: "demand", label: "Nhu cau", type: "textarea", span: 2 },
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Moi", value: "NEW" }, { label: "Tu van", value: "CONSULTING" }, { label: "Da hen", value: "APPOINTED" }, { label: "Bao gia", value: "QUOTED" }, { label: "Da chuyen doi", value: "CONVERTED" }, { label: "Huy", value: "CANCELLED" }] },
      { name: "potentialLevel", label: "Muc do", type: "select", options: [{ label: "Cold", value: "COLD" }, { label: "Warm", value: "WARM" }, { label: "Hot", value: "HOT" }] },
      { name: "lastContactResult", label: "Ket qua lien he gan nhat", type: "text" },
      { name: "budgetExpected", label: "Budget du kien", type: "currency" },
      { name: "nextFollowUpAt", label: "Follow-up", type: "datetime" },
      { name: "appointmentAt", label: "Lich hen", type: "datetime" },
      { name: "convertedCustomerId", label: "Khach hang convert", type: "select", optionsEndpoint: "/customers", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "careNote", label: "Ghi chu cham soc", type: "textarea", span: 2 },
    ],
    detailFields: [
      "code",
      "fullName",
      "phone",
      "email",
      "branchName",
      "sourceName",
      "assignedUserName",
      "status",
      "potentialLevel",
      "followUpState",
      "lastContactResult",
      "budgetExpected",
      "campaign",
      "demand",
      "nextFollowUpAt",
      "appointmentAt",
      "convertedCustomerName",
      "careNote",
    ],
  },
  contracts: {
    key: "contracts",
    title: "Hop dong / Goi tap",
    subtitle: "Quan ly hop dong, so buoi con lai, thanh toan va gia tri con lai.",
    searchPlaceholder: "Tim ma hop dong, khach hang, sale",
    endpoint: "/contracts",
    permissionPrefix: "contracts",
    columns: [
      { key: "code", label: "Ma hop dong" },
      { key: "branchName", label: "Chi nhanh", minWidth: 140 },
      { key: "customerName", label: "Khach hang" },
      { key: "packageName", label: "Goi dich vu" },
      { key: "status", label: "Trang thai", type: "status" },
      { key: "paymentStatus", label: "Thanh toan", type: "status" },
      { key: "sessionUsage", label: "Da dung / Tong" },
      { key: "amountDue", label: "Con no", type: "currency" },
      { key: "saleUserName", label: "Sale" },
      { key: "endDate", label: "Ngay het han", type: "date" },
    ],
    filters: [
      branchField,
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Active", value: "ACTIVE" }, { label: "Paused", value: "PAUSED" }, { label: "Cancelled", value: "CANCELLED" }] },
      { name: "paymentStatus", label: "Thanh toan", type: "select", options: [{ label: "Unpaid", value: "UNPAID" }, { label: "Partial", value: "PARTIAL" }, { label: "Paid", value: "PAID" }] },
      { name: "dateFrom", label: "Tu ngay", type: "date" },
      { name: "dateTo", label: "Den ngay", type: "date" },
    ],
    fields: [
      branchField,
      { name: "customerId", label: "Khach hang", type: "select", required: true, optionsEndpoint: "/customers", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "servicePackageId", label: "Goi dich vu", type: "select", required: true, optionsEndpoint: "/service-packages", optionLabelKey: "name", optionValueKey: "id" },
      { name: "saleUserId", label: "Sale", type: "select", optionsEndpoint: "/users", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "trainerId", label: "PT", type: "select", optionsEndpoint: "/trainers", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "code", label: "Ma hop dong", type: "text", required: true },
      { name: "contractType", label: "Loai hop dong", type: "text", required: true },
      { name: "packageName", label: "Ten goi", type: "text", required: true },
      { name: "startDate", label: "Ngay bat dau", type: "date", required: true },
      { name: "endDate", label: "Ngay ket thuc", type: "date", required: true },
      { name: "totalSessions", label: "Tong buoi", type: "number" },
      { name: "bonusSessions", label: "Buoi bonus", type: "number" },
      { name: "usedSessions", label: "Da dung", type: "number" },
      { name: "remainingSessions", label: "Con lai", type: "number" },
      { name: "unitPrice", label: "Don gia", type: "currency" },
      { name: "grossAmount", label: "Gia goc", type: "currency" },
      { name: "discountFixed", label: "Giam tru tien", type: "currency" },
      { name: "discountPercent", label: "Giam tru %", type: "currency" },
      { name: "totalDiscount", label: "Tong giam", type: "currency" },
      { name: "vatAmount", label: "VAT", type: "currency" },
      { name: "totalAmount", label: "Tong tien", type: "currency" },
      { name: "amountPaid", label: "Da thanh toan", type: "currency" },
      { name: "amountDue", label: "Con no", type: "currency" },
      { name: "remainingValue", label: "Gia tri con lai", type: "currency" },
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Draft", value: "DRAFT" }, { label: "Active", value: "ACTIVE" }, { label: "Paused", value: "PAUSED" }, { label: "Cancelled", value: "CANCELLED" }] },
      { name: "paymentStatus", label: "Trang thai thanh toan", type: "select", options: [{ label: "Unpaid", value: "UNPAID" }, { label: "Partial", value: "PARTIAL" }, { label: "Paid", value: "PAID" }] },
      { name: "oldContractCode", label: "Ma HD cu", type: "text" },
      { name: "richNote", label: "Ghi chu rich text", type: "textarea", span: 2 },
      { name: "note", label: "Ghi chu", type: "textarea", span: 2 },
    ],
    detailFields: [
      "code",
      "customerName",
      "customerPhone",
      "branchName",
      "servicePackageName",
      "serviceName",
      "saleUserName",
      "trainerName",
      "contractType",
      "status",
      "paymentStatus",
      "startDate",
      "endDate",
      "totalSessions",
      "bonusSessions",
      "usedSessions",
      "remainingSessions",
      "sessionUsage",
      "grossAmount",
      "totalDiscount",
      "vatAmount",
      "totalAmount",
      "amountPaid",
      "amountDue",
      "remainingValue",
      "paidPercent",
      "daysRemaining",
      "oldContractCode",
      "note",
    ],
  },
  receipts: {
    key: "receipts",
    title: "Phieu thu",
    subtitle: "Thu hop dong, ban san pham / vat tu, khach le va cac nguon thu van hanh theo chi nhanh.",
    searchPlaceholder: "Tim phieu thu, nguoi nop, hop dong, san pham",
    createLabel: "Lap phieu",
    endpoint: "/receipts",
    permissionPrefix: "receipts",
    columns: [
      { key: "code", label: "Ma phieu" },
      { key: "receiptDate", label: "Ngay thu", type: "date" },
      { key: "branchName", label: "Chi nhanh", minWidth: 140 },
      { key: "customerName", label: "Nguoi nop" },
      { key: "contractCode", label: "Hop dong" },
      { key: "sourceLabel", label: "Nguon thu" },
      { key: "paymentMethodName", label: "Phuong thuc" },
      { key: "collectorName", label: "Nguoi thu" },
      { key: "amount", label: "So tien", type: "currency" },
      { key: "status", label: "Trang thai", type: "status" },
    ],
    filters: [
      branchField,
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Completed", value: "COMPLETED" }, { label: "Pending", value: "PENDING" }] },
      { name: "dateFrom", label: "Tu ngay", type: "date" },
      { name: "dateTo", label: "Den ngay", type: "date" },
    ],
    fields: [
      branchField,
      { name: "payerKind", label: "Doi tuong nop", type: "select", virtual: true, options: [...receiptPayerKindOptions] },
      { name: "customerId", label: "Hoi vien / khach hang", type: "select", optionsEndpoint: "/customers", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "contractId", label: "Hop dong (neu co)", type: "select", optionsEndpoint: "/contracts", optionLabelKey: "code", optionValueKey: "id" },
      { name: "guestName", label: "Ten khach le", type: "text", placeholder: "Nhap ten khach le" },
      { name: "guestPhone", label: "SDT khach le", type: "phone", placeholder: "Nhap so dien thoai khach le" },
      { name: "paymentMethodId", label: "Phuong thuc thanh toan", type: "select", optionsEndpoint: "/payment-methods", optionLabelKey: "name", optionValueKey: "id" },
      { name: "code", label: "Ma phieu", type: "text", required: true },
      { name: "receiptDate", label: "Ngay thu", type: "datetime", required: true },
      { name: "sourceType", label: "Nguon thu", type: "select", required: true, options: [...receiptSourceOptions] },
      { name: "amount", label: "So tien (de trong de auto tinh neu co dong hang)", type: "currency" },
      { name: "lineItemsText", label: "San pham / vat tu", type: "line-items", span: 2 },
      { name: "content", label: "Noi dung thu", type: "text", placeholder: "Mo ta nguon thu / noi dung giao dich" },
      { name: "collectorId", label: "Nhan vien thu", type: "select", optionsEndpoint: "/users", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Completed", value: "COMPLETED" }, { label: "Pending", value: "PENDING" }] },
      { name: "note", label: "Ghi chu", type: "textarea", span: 2 },
    ],
    detailFields: [
      "code",
      "receiptDate",
      "amount",
      "status",
      "branchName",
      "customerName",
      "customerPhone",
      "contractCode",
      "contractPackageName",
      "paymentMethodName",
      "collectorName",
      "sourceLabel",
      "content",
      "note",
    ],
  },
  expenses: {
    key: "expenses",
    title: "Phieu chi",
    subtitle: "Theo doi chi phi van hanh, marketing, facility va phe duyet.",
    searchPlaceholder: "Tim phieu chi, doi tuong nhan, noi dung chi",
    createLabel: "Lap phieu",
    endpoint: "/expenses",
    permissionPrefix: "expenses",
    columns: [
      { key: "code", label: "Ma phieu" },
      { key: "expenseDate", label: "Ngay chi", type: "date" },
      { key: "branchName", label: "Chi nhanh", minWidth: 140 },
      { key: "payeeName", label: "Doi tuong nhan" },
      { key: "expenseType", label: "Loai chi" },
      { key: "paymentMethodName", label: "Phuong thuc" },
      { key: "approverName", label: "Nguoi phe duyet" },
      { key: "amount", label: "So tien", type: "currency" },
      { key: "status", label: "Trang thai", type: "status" },
    ],
    filters: [
      branchField,
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Completed", value: "COMPLETED" }, { label: "Pending", value: "PENDING" }] },
      { name: "dateFrom", label: "Tu ngay", type: "date" },
      { name: "dateTo", label: "Den ngay", type: "date" },
    ],
    fields: [
      branchField,
      { name: "paymentMethodId", label: "Phuong thuc thanh toan", type: "select", optionsEndpoint: "/payment-methods", optionLabelKey: "name", optionValueKey: "id" },
      { name: "code", label: "Ma phieu", type: "text", required: true },
      { name: "expenseDate", label: "Ngay chi", type: "datetime", required: true },
      { name: "payeeName", label: "Doi tuong nhan", type: "text", required: true },
      { name: "expenseType", label: "Loai chi", type: "text", required: true },
      { name: "amount", label: "So tien", type: "currency", required: true },
      { name: "approverId", label: "Nguoi phe duyet", type: "select", optionsEndpoint: "/users", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "createdUserId", label: "Nguoi lap phieu", type: "select", optionsEndpoint: "/users", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Completed", value: "COMPLETED" }, { label: "Pending", value: "PENDING" }] },
      { name: "note", label: "Ghi chu", type: "textarea", span: 2 },
    ],
    detailFields: [
      "code",
      "expenseDate",
      "amount",
      "status",
      "branchName",
      "payeeName",
      "expenseType",
      "paymentMethodName",
      "approverName",
      "createdUserName",
      "note",
    ],
  },
  "shop-sales": {
    key: "shop-sales",
    title: "Ban hang Pro Shop",
    subtitle: "Chung tu ban hang co dong san pham, tong tien, thanh toan va thu ngan.",
    searchPlaceholder: "Tim giao dich, khach mua, san pham",
    createLabel: "Lap giao dich",
    endpoint: "/shop-sales",
    permissionPrefix: "receipts",
    columns: [
      { key: "code", label: "Ma GD" },
      { key: "receiptDate", label: "Ngay ban", type: "date" },
      { key: "branchName", label: "Chi nhanh", minWidth: 140 },
      { key: "customerName", label: "Khach mua" },
      { key: "productSummary", label: "San pham" },
      { key: "totalQuantity", label: "SL" },
      { key: "paymentMethodName", label: "Thanh toan" },
      { key: "collectorName", label: "Thu ngan" },
      { key: "amount", label: "Tong tien", type: "currency" },
      { key: "status", label: "Trang thai", type: "status" },
    ],
    filters: [
      branchField,
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Completed", value: "COMPLETED" }, { label: "Pending", value: "PENDING" }] },
      { name: "dateFrom", label: "Tu ngay", type: "date" },
      { name: "dateTo", label: "Den ngay", type: "date" },
    ],
    fields: [
      branchField,
      { name: "customerId", label: "Khach mua", type: "select", optionsEndpoint: "/customers", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "paymentMethodId", label: "Phuong thuc thanh toan", type: "select", optionsEndpoint: "/payment-methods", optionLabelKey: "name", optionValueKey: "id" },
      { name: "code", label: "Ma giao dich", type: "text", required: true },
      { name: "receiptDate", label: "Ngay ban", type: "datetime", required: true },
      { name: "lineItemsText", label: "Dong san pham", type: "line-items", span: 2, required: true },
      { name: "amount", label: "Tong tien (de trong de auto tinh)", type: "currency" },
      { name: "content", label: "Noi dung giao dich", type: "text" },
      { name: "collectorId", label: "Thu ngan", type: "select", optionsEndpoint: "/users", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Completed", value: "COMPLETED" }, { label: "Pending", value: "PENDING" }] },
      { name: "note", label: "Ghi chu", type: "textarea", span: 2 },
    ],
    detailFields: [
      "code",
      "receiptDate",
      "amount",
      "status",
      "branchName",
      "customerName",
      "customerPhone",
      "paymentMethodName",
      "collectorName",
      "itemCount",
      "totalQuantity",
      "productSummary",
      "content",
      "note",
    ],
  },
  "shop-returns": {
    key: "shop-returns",
    title: "Tra hang Pro Shop",
    subtitle: "Chung tu tra hang / hoan tien co dong san pham, so tien va phe duyet.",
    searchPlaceholder: "Tim phieu tra, khach nhan hoan, san pham",
    createLabel: "Lap phieu tra",
    endpoint: "/shop-returns",
    permissionPrefix: "expenses",
    columns: [
      { key: "code", label: "Ma phieu" },
      { key: "expenseDate", label: "Ngay tra", type: "date" },
      { key: "branchName", label: "Chi nhanh", minWidth: 140 },
      { key: "payeeName", label: "Khach nhan hoan" },
      { key: "productSummary", label: "San pham" },
      { key: "totalQuantity", label: "SL" },
      { key: "paymentMethodName", label: "Thanh toan" },
      { key: "approverName", label: "Nguoi phe duyet" },
      { key: "amount", label: "Tong hoan", type: "currency" },
      { key: "status", label: "Trang thai", type: "status" },
    ],
    filters: [
      branchField,
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Completed", value: "COMPLETED" }, { label: "Pending", value: "PENDING" }] },
      { name: "dateFrom", label: "Tu ngay", type: "date" },
      { name: "dateTo", label: "Den ngay", type: "date" },
    ],
    fields: [
      branchField,
      { name: "paymentMethodId", label: "Phuong thuc hoan tien", type: "select", optionsEndpoint: "/payment-methods", optionLabelKey: "name", optionValueKey: "id" },
      { name: "code", label: "Ma phieu tra", type: "text", required: true },
      { name: "expenseDate", label: "Ngay tra", type: "datetime", required: true },
      { name: "payeeName", label: "Khach nhan hoan", type: "text", required: true },
      { name: "lineItemsText", label: "Dong san pham", type: "line-items", span: 2, required: true },
      { name: "amount", label: "Tong hoan (de trong de auto tinh)", type: "currency" },
      { name: "approverId", label: "Nguoi phe duyet", type: "select", optionsEndpoint: "/users", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "createdUserId", label: "Nguoi lap phieu", type: "select", optionsEndpoint: "/users", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Completed", value: "COMPLETED" }, { label: "Pending", value: "PENDING" }] },
      { name: "note", label: "Ly do / ghi chu", type: "textarea", span: 2 },
    ],
    detailFields: [
      "code",
      "expenseDate",
      "amount",
      "status",
      "branchName",
      "payeeName",
      "paymentMethodName",
      "approverName",
      "createdUserName",
      "itemCount",
      "totalQuantity",
      "productSummary",
      "note",
    ],
  },
  services: {
    key: "services",
    title: "Dich vu",
    subtitle: "Danh muc dich vu membership, PT va class.",
    searchPlaceholder: "Tim ma dich vu, ten dich vu",
    endpoint: "/services",
    permissionPrefix: "services",
    columns: [
      { key: "branchName", label: "Chi nhanh", minWidth: 150 },
      { key: "code", label: "Ma DV" },
      { key: "name", label: "Ten dich vu" },
      { key: "category", label: "Nhom" },
      { key: "packageCount", label: "So goi" },
      { key: "defaultPrice", label: "Gia", type: "currency" },
      { key: "status", label: "Trang thai", type: "status" },
    ],
    filters: [
      branchField,
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Active", value: "ACTIVE" }, { label: "Inactive", value: "INACTIVE" }] },
    ],
    fields: [
      branchField,
      { name: "code", label: "Ma DV", type: "text", required: true },
      { name: "name", label: "Ten dich vu", type: "text", required: true },
      { name: "category", label: "Nhom", type: "text", required: true },
      { name: "defaultPrice", label: "Gia", type: "currency" },
      { name: "durationDays", label: "Thoi han", type: "number" },
      { name: "defaultSessions", label: "So buoi", type: "number" },
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Active", value: "ACTIVE" }, { label: "Inactive", value: "INACTIVE" }] },
      { name: "description", label: "Mo ta", type: "textarea", span: 2 },
    ],
    detailFields: ["code", "name", "branchName", "status", "description"],
  },
  "service-packages": {
    key: "service-packages",
    title: "Goi dich vu",
    subtitle: "Gia, bonus, so buoi va quy tac gia tri con lai.",
    searchPlaceholder: "Tim ma goi, ten goi, ten dich vu",
    endpoint: "/service-packages",
    permissionPrefix: "service-packages",
    columns: [
      { key: "branchName", label: "Chi nhanh", minWidth: 150 },
      { key: "code", label: "Ma goi" },
      { key: "name", label: "Ten goi" },
      { key: "serviceName", label: "Dich vu" },
      { key: "price", label: "Gia", type: "currency" },
      { key: "sessionLabel", label: "So buoi" },
      { key: "status", label: "Trang thai", type: "status" },
    ],
    filters: [
      branchField,
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Active", value: "ACTIVE" }, { label: "Inactive", value: "INACTIVE" }] },
    ],
    fields: [
      { ...branchField, virtual: true, required: true },
      { name: "serviceId", label: "Dich vu", type: "select", required: true, optionsEndpoint: "/services", optionLabelKey: "name", optionValueKey: "id" },
      { name: "code", label: "Ma goi", type: "text", required: true },
      { name: "name", label: "Ten goi", type: "text", required: true },
      { name: "price", label: "Gia", type: "currency" },
      { name: "sessionCount", label: "So buoi", type: "number" },
      { name: "bonusSessions", label: "Buoi KM", type: "number" },
      { name: "bonusDays", label: "Ngay KM", type: "number" },
      { name: "durationDays", label: "Thoi han", type: "number" },
      { name: "packageType", label: "Loai goi", type: "text", required: true },
      { name: "remainingValueRule", label: "Rule GT con lai", type: "text" },
      { name: "description", label: "Mo ta", type: "textarea", span: 2 },
    ],
    detailFields: ["code", "name", "serviceName", "branchName", "price", "status", "description"],
  },
  trainers: {
    key: "trainers",
    title: "Huan luyen vien",
    subtitle: "Quan ly profile PT va chuyen mon.",
    searchPlaceholder: "Tim ma PT, ho ten, chuyen mon",
    endpoint: "/trainers",
    permissionPrefix: "trainers",
    columns: [
      { key: "code", label: "Ma PT" },
      { key: "fullName", label: "Ho ten" },
      { key: "branchName", label: "Chi nhanh" },
      { key: "specialty", label: "Chuyen mon" },
      { key: "upcomingSessionCount", label: "Lich sap toi" },
      { key: "status", label: "Trang thai", type: "status" },
    ],
    filters: [
      branchField,
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Active", value: "ACTIVE" }, { label: "Inactive", value: "INACTIVE" }] },
    ],
    fields: [
      branchField,
      { name: "code", label: "Ma PT", type: "text", required: true },
      { name: "fullName", label: "Ho ten", type: "text", required: true },
      { name: "phone", label: "Dien thoai", type: "phone" },
      { name: "email", label: "Email", type: "email" },
      { name: "specialty", label: "Chuyen mon", type: "text" },
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Active", value: "ACTIVE" }, { label: "Inactive", value: "INACTIVE" }] },
      { name: "note", label: "Ghi chu", type: "textarea", span: 2 },
    ],
    detailFields: ["code", "fullName", "branchName", "phone", "email", "specialty", "status", "note"],
  },
  "training-sessions": {
    key: "training-sessions",
    title: "Buoi tap",
    subtitle: "Lich tap, check-in va tru so buoi con lai.",
    searchPlaceholder: "Tim ma buoi, khach hang, PT",
    endpoint: "/training-sessions",
    permissionPrefix: "training-sessions",
    columns: [
      { key: "code", label: "Ma buoi" },
      { key: "scheduledAt", label: "Lich tap", type: "date" },
      { key: "branchName", label: "Chi nhanh", minWidth: 140 },
      { key: "customerName", label: "Khach hang" },
      { key: "trainerName", label: "PT" },
      { key: "status", label: "Trang thai", type: "status" },
      { key: "consumedSessions", label: "Tru buoi" },
    ],
    filters: [
      branchField,
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Scheduled", value: "SCHEDULED" }, { label: "Checked in", value: "CHECKED_IN" }, { label: "Completed", value: "COMPLETED" }, { label: "Missed", value: "MISSED" }, { label: "Cancelled", value: "CANCELLED" }] },
    ],
    fields: [
      branchField,
      { name: "contractId", label: "Hop dong", type: "select", optionsEndpoint: "/contracts", optionLabelKey: "code", optionValueKey: "id" },
      { name: "customerId", label: "Khach hang", type: "select", required: true, optionsEndpoint: "/customers", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "trainerId", label: "PT", type: "select", optionsEndpoint: "/trainers", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "code", label: "Ma buoi", type: "text", required: true },
      { name: "scheduledAt", label: "Lich tap", type: "datetime", required: true },
      { name: "durationMinutes", label: "Thoi luong", type: "number" },
      { name: "location", label: "Vi tri", type: "text" },
      { name: "consumedSessions", label: "Tru buoi", type: "number" },
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Scheduled", value: "SCHEDULED" }, { label: "Checked in", value: "CHECKED_IN" }, { label: "Completed", value: "COMPLETED" }, { label: "Missed", value: "MISSED" }, { label: "Cancelled", value: "CANCELLED" }] },
      { name: "outcome", label: "Ket qua", type: "textarea", span: 2 },
      { name: "note", label: "Ghi chu", type: "textarea", span: 2 },
    ],
    detailFields: ["code", "scheduledDateTime", "branchName", "status", "checkInDateTime", "outcome", "note"],
  },
  lockers: {
    key: "lockers",
    title: "Tu do",
    subtitle: "Quan ly ma tu, don gia va tinh trang su dung.",
    endpoint: "/lockers",
    permissionPrefix: "lockers",
    columns: [
      { key: "code", label: "Ma tu" },
      { key: "branchName", label: "Chi nhanh", minWidth: 140 },
      { key: "name", label: "Ten tu" },
      { key: "label", label: "Nhan" },
      { key: "price", label: "Don gia", type: "currency" },
      { key: "status", label: "Trang thai", type: "status" },
    ],
    filters: [branchField],
    fields: [
      branchField,
      { name: "code", label: "Ma tu", type: "text", required: true },
      { name: "name", label: "Ten tu", type: "text", required: true },
      { name: "label", label: "Nhan", type: "text" },
      { name: "price", label: "Don gia", type: "currency" },
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Empty", value: "EMPTY" }, { label: "Rented", value: "RENTED" }, { label: "Locked", value: "LOCKED" }, { label: "Maintenance", value: "MAINTENANCE" }] },
      { name: "note", label: "Ghi chu", type: "textarea", span: 2 },
    ],
    detailFields: ["code", "branchName", "name", "label", "price", "status", "note"],
  },
  "locker-rentals": {
    key: "locker-rentals",
    title: "Thue tu do",
    subtitle: "Lap phieu thue tu, gan hoi vien va theo doi thoi gian su dung.",
    searchPlaceholder: "Tim ma thue, hoi vien, ma tu, nhan tu",
    createLabel: "Lap thue tu",
    endpoint: "/locker-rentals",
    permissionPrefix: "locker-rentals",
    columns: [
      { key: "code", label: "Ma thue" },
      { key: "branchName", label: "Chi nhanh", minWidth: 140 },
      { key: "lockerDisplayName", label: "Tu do" },
      { key: "customerName", label: "Hoi vien" },
      { key: "startDate", label: "Tu ngay", type: "date" },
      { key: "endDate", label: "Den ngay", type: "date" },
      { key: "depositAmount", label: "Tien coc", type: "currency" },
      { key: "status", label: "Trang thai", type: "status" },
    ],
    filters: [
      branchField,
      {
        name: "status",
        label: "Trang thai thue",
        type: "select",
        options: [
          { label: "Dang thue", value: "ACTIVE" },
          { label: "Da tra", value: "RETURNED" },
          { label: "Qua han", value: "OVERDUE" },
          { label: "Da huy", value: "CANCELLED" },
        ],
      },
      { name: "dateFrom", label: "Tu ngay", type: "date" },
      { name: "dateTo", label: "Den ngay", type: "date" },
    ],
    fields: [
      branchField,
      { name: "lockerId", label: "Tu do", type: "select", required: true, optionsEndpoint: "/lockers", optionLabelKey: "lockerDisplayName", optionValueKey: "id" },
      { name: "customerId", label: "Hoi vien", type: "select", required: true, optionsEndpoint: "/customers", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "code", label: "Ma thue", type: "text", placeholder: "De trong de tu sinh ma" },
      { name: "startDate", label: "Tu ngay", type: "date", required: true },
      { name: "endDate", label: "Den ngay", type: "date", required: true },
      { name: "depositAmount", label: "Tien coc", type: "currency" },
      { name: "processedById", label: "Nguoi lap", type: "select", optionsEndpoint: "/users", optionLabelKey: "fullName", optionValueKey: "id" },
      {
        name: "status",
        label: "Trang thai",
        type: "select",
        options: [
          { label: "Dang thue", value: "ACTIVE" },
          { label: "Da tra", value: "RETURNED" },
          { label: "Qua han", value: "OVERDUE" },
          { label: "Da huy", value: "CANCELLED" },
        ],
      },
      { name: "note", label: "Ghi chu", type: "textarea", span: 2 },
    ],
    detailFields: ["code", "branchName", "lockerDisplayName", "customerName", "customerCode", "startDate", "endDate", "depositAmount", "processedByName", "status", "note"],
  },
  deposits: {
    key: "deposits",
    title: "Tien coc",
    subtitle: "Theo doi coc giu do, coc tu do va tinh trang hoan coc.",
    endpoint: "/deposits",
    permissionPrefix: "deposits",
    columns: [
      { key: "code", label: "Ma phieu" },
      { key: "branchName", label: "Chi nhanh", minWidth: 140 },
      { key: "itemType", label: "Loai coc" },
      { key: "amount", label: "So tien", type: "currency" },
      { key: "status", label: "Trang thai", type: "status" },
      { key: "receivedAt", label: "Ngay nhan", type: "date" },
    ],
    filters: [branchField],
    fields: [
      branchField,
      { name: "customerId", label: "Khach hang", type: "select", optionsEndpoint: "/customers", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "lockerRentalId", label: "Phieu thue tu", type: "select", optionsEndpoint: "/locker-rentals", optionLabelKey: "code", optionValueKey: "id" },
      { name: "code", label: "Ma phieu", type: "text", required: true },
      { name: "itemType", label: "Loai coc", type: "text", required: true },
      { name: "amount", label: "So tien", type: "currency", required: true },
      { name: "receivedAt", label: "Ngay nhan", type: "datetime", required: true },
      { name: "returnedAt", label: "Ngay tra", type: "datetime" },
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Holding", value: "HOLDING" }, { label: "Returned", value: "RETURNED" }, { label: "Overdue", value: "OVERDUE" }] },
      { name: "note", label: "Ghi chu", type: "textarea", span: 2 },
    ],
    detailFields: ["code", "branchName", "itemType", "amount", "status", "receivedAt", "returnedAt", "note"],
  },
  products: {
    key: "products",
    title: "Hang hoa",
    subtitle: "Ton kho, gia von, gia ban va loai nghiep vu cua mat hang.",
    searchPlaceholder: "Tim ma hang, ten hang, nhom hang",
    endpoint: "/products",
    permissionPrefix: "products",
    columns: [
      { key: "code", label: "Ma hang" },
      { key: "name", label: "Ten hang" },
      { key: "branchName", label: "Chi nhanh" },
      { key: "usageType", label: "Loai vat tu" },
      { key: "groupName", label: "Nhom" },
      { key: "stockQuantity", label: "Ton kho" },
      { key: "stockAlertLabel", label: "Canh bao ton" },
      { key: "salePrice", label: "Gia ban", type: "currency" },
    ],
    filters: [
      branchField,
      {
        name: "status",
        label: "Trang thai",
        type: "select",
        options: [
          { label: "Active", value: "ACTIVE" },
          { label: "Inactive", value: "INACTIVE" },
        ],
      },
      { name: "usageType", label: "Loai vat tu", type: "select", options: [...productUsageTypeOptions] },
    ],
    fields: [
      branchField,
      { name: "code", label: "Ma hang", type: "text", required: true },
      { name: "name", label: "Ten hang", type: "text", required: true },
      { name: "unit", label: "Don vi", type: "text", required: true },
      {
        name: "groupName",
        label: "Nhom hang",
        type: "select",
        optionsEndpoint: "/product-groups",
        optionLabelKey: "name",
        optionValueKey: "value",
        description: "Tao moi tai Nghiep vu -> Nhom hang / cap phat.",
      },
      { name: "purchasePrice", label: "Gia nhap", type: "currency" },
      { name: "salePrice", label: "Gia ban", type: "currency" },
      { name: "usageType", label: "Loai vat tu", type: "select", options: [...productUsageTypeOptions] },
      { name: "stockQuantity", label: "Ton kho", type: "number" },
      { name: "minStockQuantity", label: "Ton toi thieu", type: "number" },
      {
        name: "status",
        label: "Trang thai",
        type: "select",
        options: [
          { label: "Active", value: "ACTIVE" },
          { label: "Inactive", value: "INACTIVE" },
        ],
      },
    ],
    detailFields: ["code", "name", "branchName", "categoryName", "unit", "usageType", "groupName", "stockQuantity", "minStockQuantity", "stockAlertLabel", "purchasePrice", "salePrice", "lastPurchaseDate", "status"],
  },
  "towel-issues": {
    key: "towel-issues",
    title: "Phat / tra khan",
    subtitle: "Theo doi tung luot phat khan, tra khan, mat / hu va dang giat.",
    searchPlaceholder: "Tim ma phat, khan, hoi vien, hop dong, phieu thu",
    createLabel: "Lap phieu phat khan",
    endpoint: "/towel-issues",
    permissionPrefix: "towel-issues",
    columns: [
      { key: "code", label: "Ma phieu" },
      { key: "productOptionLabel", label: "Vat tu" },
      { key: "branchName", label: "Chi nhanh", minWidth: 140 },
      { key: "customerName", label: "Hoi vien" },
      { key: "quantity", label: "SL" },
      { key: "issueDate", label: "Ngay phat", type: "date" },
      { key: "dueDate", label: "Han tra", type: "date" },
      { key: "status", label: "Trang thai", type: "status" },
    ],
    filters: [
      branchField,
      { name: "status", label: "Trang thai", type: "select", options: [...towelIssueStatusOptions] },
      { name: "dateFrom", label: "Tu ngay", type: "date" },
      { name: "dateTo", label: "Den ngay", type: "date" },
    ],
    fields: [
      branchField,
      { name: "productId", label: "Khan / vat tu", type: "select", required: true, optionsEndpoint: "/products?usageType=TOWEL_SERVICE", optionLabelKey: "productOptionLabel", optionValueKey: "id" },
      { name: "customerId", label: "Hoi vien", type: "select", required: true, optionsEndpoint: "/customers", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "contractId", label: "Hop dong", type: "select", optionsEndpoint: "/contracts", optionLabelKey: "code", optionValueKey: "id" },
      { name: "code", label: "Ma phieu", type: "text", placeholder: "De trong de tu sinh ma" },
      { name: "quantity", label: "So luong", type: "number", required: true },
      { name: "issueDate", label: "Ngay phat", type: "datetime", required: true },
      { name: "dueDate", label: "Han tra", type: "datetime" },
      { name: "returnDate", label: "Ngay tra", type: "datetime" },
      { name: "handledById", label: "Nguoi xu ly", type: "select", optionsEndpoint: "/users", optionLabelKey: "fullName", optionValueKey: "id" },
      { name: "status", label: "Trang thai", type: "select", options: [...towelIssueStatusOptions] },
      { name: "note", label: "Ghi chu", type: "textarea", span: 2 },
    ],
    detailFields: ["code", "branchName", "productOptionLabel", "customerName", "contractCode", "receiptCode", "quantity", "issueDate", "dueDate", "returnDate", "handledByName", "status", "note"],
  },
  suppliers: {
    key: "suppliers",
    title: "Nha cung cap",
    subtitle: "Thong tin lien he nha cung cap va ghi chu mua hang.",
    searchPlaceholder: "Tim ma nha cung cap, ten nha cung cap",
    endpoint: "/suppliers",
    permissionPrefix: "suppliers",
    columns: [
      { key: "code", label: "Ma NCC" },
      { key: "name", label: "Ten NCC" },
      { key: "branchName", label: "Chi nhanh" },
      { key: "contactName", label: "Nguoi lien he" },
      { key: "purchaseOrderCount", label: "So phieu nhap" },
      { key: "lastOrderDate", label: "Don gan nhat", type: "date" },
    ],
    filters: [branchField],
    fields: [
      branchField,
      { name: "code", label: "Ma NCC", type: "text", required: true },
      { name: "name", label: "Ten NCC", type: "text", required: true },
      { name: "contactName", label: "Nguoi lien he", type: "text" },
      { name: "phone", label: "Dien thoai", type: "phone" },
      { name: "email", label: "Email", type: "email" },
      { name: "address", label: "Dia chi", type: "textarea", span: 2 },
      { name: "note", label: "Ghi chu", type: "textarea", span: 2 },
    ],
    detailFields: ["code", "name", "branchName", "contactName", "phone", "email", "purchaseOrderCount", "completedPurchaseOrderCount", "lastOrderDate", "address", "note"],
  },
  "purchase-orders": {
    key: "purchase-orders",
    title: "Phieu nhap",
    subtitle: "Nhap hang, tong tien, trang thai va thong tin nha cung cap.",
    searchPlaceholder: "Tim phieu nhap, nha cung cap, ma hang",
    createLabel: "Lap phieu nhap",
    endpoint: "/purchase-orders",
    permissionPrefix: "purchase-orders",
    columns: [
      { key: "code", label: "Ma phieu" },
      { key: "orderDate", label: "Ngay nhap", type: "date" },
      { key: "branchName", label: "Chi nhanh", minWidth: 140 },
      { key: "supplierName", label: "Nha cung cap" },
      { key: "status", label: "Trang thai", type: "status" },
      { key: "itemCount", label: "So dong" },
      { key: "totalAmount", label: "Tong tien", type: "currency" },
    ],
    filters: [
      branchField,
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Draft", value: "DRAFT" }, { label: "Pending", value: "PENDING" }, { label: "Completed", value: "COMPLETED" }, { label: "Cancelled", value: "CANCELLED" }] },
    ],
    fields: [
      branchField,
      { name: "supplierId", label: "Nha cung cap", type: "select", required: true, optionsEndpoint: "/suppliers", optionLabelKey: "name", optionValueKey: "id" },
      { name: "code", label: "Ma phieu", type: "text", required: true },
      { name: "orderDate", label: "Ngay nhap", type: "date", required: true },
      { name: "expectedDate", label: "Ngay du kien", type: "date" },
      { name: "items", label: "Dong nhap hang", type: "purchase-order-items", span: 2, required: true },
      { name: "totalAmount", label: "Tong tien", type: "currency" },
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Draft", value: "DRAFT" }, { label: "Pending", value: "PENDING" }, { label: "Completed", value: "COMPLETED" }, { label: "Cancelled", value: "CANCELLED" }] },
      { name: "note", label: "Ghi chu", type: "textarea", span: 2 },
    ],
    detailFields: ["code", "orderDate", "expectedDate", "branchName", "supplierName", "supplierContactName", "supplierPhone", "createdUserName", "itemCount", "totalQuantity", "productSummary", "status", "totalAmount", "note"],
  },
  "tenant-databases": {
    key: "tenant-databases",
    title: "CSDL khach hang",
    subtitle: "Cap moi va quan ly tung PostgreSQL rieng cho moi khach hang/tenant.",
    endpoint: "/tenant-databases",
    permissionPrefix: "tenant-databases",
    columns: [
      { key: "code", label: "Ma tenant" },
      { key: "name", label: "Ten tenant" },
      { key: "providerLabel", label: "Loai nguon", minWidth: 110 },
      { key: "connectionModeLabel", label: "Che do ket noi", minWidth: 130 },
      { key: "databaseHost", label: "Host", minWidth: 120 },
      { key: "databaseName", label: "Ten CSDL" },
      { key: "databaseUser", label: "User CSDL" },
      { key: "adminUsername", label: "Admin login" },
      { key: "status", label: "Trang thai", type: "status" },
      { key: "createdDateTime", label: "Ngay tao", type: "date" },
    ],
    filters: [
      {
        name: "status",
        label: "Trang thai",
        type: "select",
        options: [
          { label: "Active", value: "ACTIVE" },
          { label: "Inactive", value: "INACTIVE" },
        ],
      },
    ],
    fields: [
      { name: "code", label: "Ma tenant", type: "text", required: true, createOnly: true, section: "Nguon CSDL" },
      { name: "name", label: "Ten tenant", type: "text", required: true, section: "Nguon CSDL" },
      {
        name: "providerType",
        label: "Loai nguon",
        type: "select",
        required: true,
        section: "Nguon CSDL",
        options: [
          { label: "PostgreSQL", value: "POSTGRESQL" },
          { label: "Neon.tech", value: "NEON" },
        ],
      },
      {
        name: "connectionMode",
        label: "Che do ket noi",
        type: "select",
        required: true,
        section: "Nguon CSDL",
        options: [
          { label: "Chuoi ket noi", value: "CONNECTION_STRING" },
          { label: "Host / user / password", value: "PARAMETERS" },
        ],
      },
      {
        name: "connectionUrl",
        label: "Chuoi ket noi",
        type: "textarea",
        span: 2,
        section: "Ket noi",
        placeholder: "postgresql://user:password@host:5432/database?schema=public",
        description: "Dung khi ban muon nhap mot chuoi ket noi day du.",
      },
      {
        name: "directConnectionUrl",
        label: "Chuoi ket noi direct",
        type: "textarea",
        span: 2,
        section: "Ket noi",
        placeholder: "Chi ap dung cho Neon.tech neu co direct connection",
        description: "Neu la Neon, ban co the luu them direct connection URL cho backend worker / migrate.",
      },
      { name: "databaseHost", label: "Host may chu", type: "text", section: "Ket noi tham so" },
      { name: "databasePort", label: "Cong ket noi", type: "number", placeholder: "5432", section: "Ket noi tham so" },
      { name: "databaseName", label: "Ten CSDL", type: "text", section: "Ket noi tham so" },
      { name: "databaseUser", label: "User CSDL", type: "text", section: "Ket noi tham so" },
      {
        name: "databasePassword",
        label: "Mat khau CSDL",
        type: "password",
        section: "Ket noi tham so",
        sensitive: true,
        description: "Can nhap khi dung che do host / user / password, hoac khi can thay doi mat khau ket noi.",
      },
      { name: "adminUsername", label: "Username admin", type: "text", required: true, createOnly: true, section: "Tai khoan admin" },
      { name: "adminFullName", label: "Ho ten admin", type: "text", createOnly: true, section: "Tai khoan admin" },
      { name: "adminEmail", label: "Email admin", type: "email", section: "Tai khoan admin" },
      { name: "adminPhone", label: "Dien thoai admin", type: "phone", section: "Tai khoan admin" },
      { name: "adminPassword", label: "Mat khau admin", type: "password", required: true, createOnly: true, section: "Tai khoan admin", sensitive: true },
      { name: "branchName", label: "Chi nhanh mac dinh", type: "text", section: "Portal" },
      { name: "appUrl", label: "App URL", type: "text", placeholder: "https://tenant.your-domain.vn", section: "Portal" },
      { name: "note", label: "Ghi chu", type: "textarea", span: 2, section: "Khac" },
      {
        name: "isActive",
        label: "Kich hoat",
        type: "select",
        editOnly: true,
        section: "Khac",
        options: [
          { label: "Bat", value: "true" },
          { label: "Tat", value: "false" },
        ],
      },
    ],
    detailFields: [
      "code",
      "name",
      "providerLabel",
      "connectionModeLabel",
      "databaseHost",
      "databasePort",
      "databaseName",
      "databaseUser",
      "connectionUrlPreview",
      "directConnectionUrlPreview",
      "adminUsername",
      "adminEmail",
      "branchName",
      "appUrl",
      "status",
      "note",
      "createdDateTime",
      "updatedDateTime",
    ],
  },
  branches: {
    key: "branches",
    title: "Chi nhanh",
    subtitle: "Thong tin chi nhanh, thoi gian mo cua va quy tac dat / coc.",
    endpoint: "/branches",
    permissionPrefix: "branches",
    columns: [
      { key: "code", label: "Ma CN" },
      { key: "name", label: "Ten chi nhanh" },
      { key: "operatingHours", label: "Khung gio hoat dong", minWidth: 130 },
      { key: "phone", label: "Dien thoai" },
      { key: "userCount", label: "Nhan vien", minWidth: 88, align: "center" },
      { key: "attendanceMachineCount", label: "May cham cong", minWidth: 104, align: "center" },
      { key: "requiresDepositLabel", label: "Quy tac coc", minWidth: 120 },
    ],
    filters: [],
    fields: [
      { name: "code", label: "Ma chi nhanh", type: "text", required: true },
      { name: "name", label: "Ten chi nhanh", type: "text", required: true },
      { name: "phone", label: "Dien thoai", type: "phone" },
      { name: "email", label: "Email", type: "email" },
      { name: "openingTime", label: "Gio mo cua", type: "text" },
      { name: "closingTime", label: "Gio dong cua", type: "text" },
      { name: "maxDepositHours", label: "Gio coc toi da", type: "number" },
      { name: "maxBookingsPerDay", label: "Luot dat toi da/ngay", type: "number" },
      { name: "requiresDeposit", label: "Yeu cau coc", type: "select", options: [{ label: "Bat", value: "true" }, { label: "Tat", value: "false" }] },
      { name: "logoUrl", label: "Logo URL", type: "text", span: 2 },
      { name: "address", label: "Dia chi", type: "textarea", span: 2 },
      { name: "note", label: "Ghi chu", type: "textarea", span: 2 },
    ],
    detailFields: [
      "code",
      "name",
      "phone",
      "email",
      "operatingHours",
      "address",
      "maxDepositHours",
      "maxBookingsPerDay",
      "requiresDepositLabel",
      "logoUrl",
      "userCount",
      "customerCount",
      "trainerCount",
      "attendanceMachineCount",
      "note",
      "createdDateTime",
      "updatedDateTime",
    ],
  },
  users: {
    key: "users",
    title: "Nguoi dung",
    subtitle: "Tai khoan nhan su, trang thai, chi nhanh va chuc danh.",
    searchPlaceholder: "Tim ma NV, ten dang nhap, ho ten",
    endpoint: "/users",
    permissionPrefix: "users",
    columns: [
      { key: "employeeCode", label: "Ma NV", minWidth: 96 },
      { key: "username", label: "Ten dang nhap" },
      { key: "fullName", label: "Ho ten" },
      { key: "branchName", label: "Chi nhanh", minWidth: 130 },
      { key: "title", label: "Chuc danh", minWidth: 130 },
      { key: "roleNames", label: "Vai tro", minWidth: 220 },
      { key: "lastLoginDateTime", label: "Dang nhap cuoi", type: "date", minWidth: 110 },
      { key: "status", label: "Trang thai", type: "status" },
    ],
    filters: [
      branchField,
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Active", value: "ACTIVE" }, { label: "Locked", value: "LOCKED" }] },
    ],
    fields: [
      { name: "branchId", label: "Chi nhanh", type: "select", optionsEndpoint: "/branches", optionLabelKey: "name", optionValueKey: "id" },
      { name: "employeeCode", label: "Ma nhan vien", type: "text", placeholder: "De trong se lay theo username" },
      { name: "attendanceCode", label: "Ma cham cong", type: "text", placeholder: "Ma dung tren may van tay / the / face ID" },
      { name: "username", label: "Ten dang nhap", type: "text", required: true },
      { name: "fullName", label: "Ho ten", type: "text", required: true },
      { name: "email", label: "Email", type: "email" },
      { name: "phone", label: "Dien thoai", type: "phone" },
      { name: "password", label: "Mat khau", type: "password", required: true, createOnly: true },
      { name: "roleIds", label: "Vai tro", type: "checklist", required: true, multiple: true, optionsEndpoint: "/roles", optionLabelKey: "name", optionValueKey: "id", span: 2, description: "Vai tro quyet dinh quyen he thong. Neu bat PT / Huan luyen vien, nhan vien se duoc dong bo sang danh sach PT cua chi nhanh." },
      { name: "title", label: "Chuc danh", type: "text", placeholder: "Vi du: HR Executive, Senior PT", description: "Chuc danh chi de hien thi. He thong nhan dien PT dua tren vai tro PT / Huan luyen vien, khong dua tren noi dung o truong nay." },
      { name: "avatarUrl", label: "Avatar URL", type: "text", span: 2 },
      { name: "status", label: "Trang thai", type: "select", options: [{ label: "Active", value: "ACTIVE" }, { label: "Locked", value: "LOCKED" }] },
    ],
    detailFields: [
      "employeeCode",
      "attendanceCode",
      "username",
      "fullName",
      "branchName",
      "email",
      "phone",
      "title",
      "roleNames",
      "permissionCount",
      "lastLoginDateTime",
      "status",
      "avatarUrl",
      "createdDateTime",
      "updatedDateTime",
    ],
  },
  roles: {
    key: "roles",
    title: "Vai tro",
    subtitle: "Vai tro, mo ta va ma tran quyen.",
    endpoint: "/roles",
    permissionPrefix: "roles",
    columns: [
      { key: "code", label: "Ma vai tro" },
      { key: "name", label: "Ten vai tro" },
      { key: "roleType", label: "Loai vai tro" },
      { key: "permissionCount", label: "So quyen", minWidth: 86, align: "center" },
      { key: "userCount", label: "So nguoi dung", minWidth: 110, align: "center" },
    ],
    filters: [],
    fields: [
      { name: "code", label: "Ma vai tro", type: "text", required: true },
      { name: "name", label: "Ten vai tro", type: "text", required: true },
      { name: "description", label: "Mo ta", type: "textarea", span: 2 },
      { name: "permissionIds", label: "Quyen", type: "permission-matrix", multiple: true, optionsEndpoint: "/permissions", optionLabelKey: "code", optionValueKey: "id", span: 2 },
    ],
    detailFields: ["code", "name", "roleType", "description"],
  },
  "attendance-machines": {
    key: "attendance-machines",
    title: "May cham cong",
    subtitle: "Thiet bi cham cong, cong ket noi, IP / Domain va trang thai dong bo.",
    endpoint: "/attendance-machines",
    permissionPrefix: "attendance-machines",
    columns: [
      { key: "code", label: "Ma may" },
      { key: "name", label: "Ten may" },
      { key: "vendor", label: "Vendor", minWidth: 110 },
      { key: "machineType", label: "Loai may", minWidth: 110 },
      { key: "protocol", label: "Giao thuc", minWidth: 130 },
      { key: "branchName", label: "Chi nhanh", minWidth: 130 },
      { key: "host", label: "IP / Domain" },
      { key: "connectionPort", label: "Cong ket noi", minWidth: 110, align: "center" },
      { key: "syncLabel", label: "Dong bo", minWidth: 110 },
      { key: "connectionStatus", label: "Trang thai", type: "status" },
      { key: "lastSyncedDateTime", label: "Lan dong bo cuoi", type: "date", minWidth: 130 },
    ],
    filters: [
      branchField,
      {
        name: "status",
        label: "Trang thai",
        type: "select",
        options: [
          { label: "Connected", value: "CONNECTED" },
          { label: "Disconnected", value: "DISCONNECTED" },
          { label: "Syncing", value: "SYNCING" },
          { label: "Error", value: "ERROR" },
        ],
      },
    ],
    fields: [
      branchField,
      { name: "code", label: "Ma may", type: "text", required: true },
      { name: "name", label: "Ten may", type: "text", required: true },
      { name: "vendor", label: "Vendor", type: "select", options: [{ label: "Generic", value: "GENERIC" }, { label: "ZKTeco", value: "ZKTECO" }, { label: "Hikvision", value: "HIKVISION" }, { label: "Suprema", value: "SUPREMA" }, { label: "Anviz", value: "ANVIZ" }, { label: "Ronald Jack", value: "RONALD_JACK" }] },
      { name: "machineType", label: "Loai may", type: "select", options: [{ label: "Van tay", value: "FINGERPRINT" }, { label: "Khuon mat", value: "FACE" }, { label: "The", value: "CARD" }, { label: "Hybrid", value: "HYBRID" }] },
      { name: "protocol", label: "Giao thuc", type: "select", options: [{ label: "Generic export", value: "GENERIC_EXPORT" }, { label: "CSV import", value: "CSV_IMPORT" }, { label: "ZKTeco pull TCP", value: "ZK_PULL_TCP" }, { label: "ZKTeco ADMS push", value: "ZK_ADMS_PUSH" }, { label: "Hikvision ISAPI", value: "HIKVISION_ISAPI" }, { label: "Suprema BioStar", value: "SUPREMA_BIOSTAR" }, { label: "Generic HTTP", value: "GENERIC_HTTP" }] },
      { name: "model", label: "Model", type: "text" },
      { name: "deviceIdentifier", label: "Device ID / FDID", type: "text" },
      { name: "host", label: "IP / Domain", type: "text" },
      { name: "connectionPort", label: "Cong ket noi", type: "text" },
      { name: "username", label: "Tai khoan may", type: "text" },
      { name: "apiKey", label: "API key bridge", type: "password", placeholder: "Dung cho ket noi API bridge neu can" },
      { name: "webhookSecret", label: "Webhook secret bridge", type: "password", placeholder: "Secret de service tai chi nhanh day log ve server Da Nang" },
      { name: "commKey", label: "Comm key / communication password", type: "text", placeholder: "Bo trong neu may khong dung comm key" },
      { name: "timeZone", label: "Mui gio", type: "text", placeholder: "Asia/Bangkok" },
      { name: "pollingIntervalSeconds", label: "Chu ky poll log (giay)", type: "number", placeholder: "300" },
      { name: "supportsCardEnrollment", label: "Ho tro the", type: "select", options: [{ label: "Bat", value: "true" }, { label: "Tat", value: "false" }] },
      { name: "supportsFaceImage", label: "Ho tro anh khuon mat", type: "select", options: [{ label: "Bat", value: "true" }, { label: "Tat", value: "false" }] },
      { name: "supportsFaceTemplate", label: "Ho tro face template", type: "select", options: [{ label: "Bat", value: "true" }, { label: "Tat", value: "false" }] },
      { name: "supportsFingerprintTemplate", label: "Ho tro fingerprint template", type: "select", options: [{ label: "Bat", value: "true" }, { label: "Tat", value: "false" }] },
      { name: "supportsWebhook", label: "Ho tro webhook / push", type: "select", options: [{ label: "Bat", value: "true" }, { label: "Tat", value: "false" }] },
      {
        name: "connectionStatus",
        label: "Trang thai",
        type: "select",
        options: [
          { label: "Connected", value: "CONNECTED" },
          { label: "Disconnected", value: "DISCONNECTED" },
          { label: "Syncing", value: "SYNCING" },
          { label: "Error", value: "ERROR" },
        ],
      },
      { name: "syncEnabled", label: "Dong bo", type: "select", options: [{ label: "Bat", value: "true" }, { label: "Tat", value: "false" }] },
      { name: "password", label: "Mat khau", type: "password" },
    ],
    detailFields: ["code", "name", "vendor", "machineType", "protocol", "model", "deviceIdentifier", "branchName", "host", "connectionPort", "username", "apiKeyStatus", "webhookStatus", "commKeyStatus", "timeZone", "pollingIntervalSeconds", "supportsCardEnrollment", "supportsFaceImage", "supportsFingerprintTemplate", "supportsWebhook", "syncLabel", "connectionStatus", "lastHeartbeatDateTime", "lastErrorMessage"],
  },
  "staff-shifts": {
    key: "staff-shifts",
    title: "Danh sách ca làm",
    subtitle: "Danh mục ca, giờ vào/ra, nghỉ giữa ca, trễ, về sớm, OT và ca qua đêm.",
    searchPlaceholder: "Tìm mã ca, tên ca, giờ vào/ra",
    endpoint: "/staff-shifts",
    permissionPrefix: "staff-shifts",
    columns: [
      { key: "code", label: "Mã ca", minWidth: 110 },
      { key: "name", label: "Tên ca", minWidth: 140 },
      { key: "startTime", label: "Giờ bắt đầu", minWidth: 92, align: "center" },
      { key: "endTime", label: "Giờ kết thúc", minWidth: 92, align: "center" },
      { key: "breakMinutes", label: "Nghỉ giữa ca", minWidth: 92, align: "center" },
      { key: "workHours", label: "Giờ công", minWidth: 82, align: "center" },
      { key: "lateToleranceMinutes", label: "Trễ", minWidth: 70, align: "center" },
      { key: "earlyLeaveToleranceMinutes", label: "Về sớm", minWidth: 80, align: "center" },
      { key: "overtimeAfterMinutes", label: "OT", minWidth: 70, align: "center" },
      { key: "mealAllowance", label: "HT com", minWidth: 80, align: "center" },
      { key: "nightAllowance", label: "HT dem", minWidth: 80, align: "center" },
      { key: "overnightLabel", label: "Ca qua đêm", minWidth: 92, align: "center" },
    ],
    filters: [
      branchField,
      {
        name: "status",
        label: "Loại ca",
        type: "select",
        options: [
          { label: "Trong ngày", value: "DAY" },
          { label: "Qua đêm", value: "OVERNIGHT" },
        ],
      },
    ],
    fields: [
      branchField,
      { name: "code", label: "Mã ca", type: "text", required: true },
      { name: "name", label: "Tên ca", type: "text", required: true },
      { name: "startTime", label: "Giờ bắt đầu", type: "text", required: true, placeholder: "05:00" },
      { name: "endTime", label: "Giờ kết thúc", type: "text", required: true, placeholder: "13:00" },
      { name: "breakMinutes", label: "Nghỉ giữa ca (phút)", type: "number" },
      { name: "workHours", label: "Giờ công", type: "number" },
      { name: "lateToleranceMinutes", label: "Trễ (phút)", type: "number" },
      { name: "earlyLeaveToleranceMinutes", label: "Về sớm (phút)", type: "number" },
      { name: "overtimeAfterMinutes", label: "OT sau (phút)", type: "number" },
      { name: "mealAllowance", label: "HT com", type: "number" },
      { name: "nightAllowance", label: "HT dem", type: "number" },
      {
        name: "isOvernight",
        label: "Ca qua đêm",
        type: "select",
        options: [
          { label: "Không", value: "false" },
          { label: "Có", value: "true" },
        ],
      },
      { name: "note", label: "Ghi chú", type: "textarea", span: 2 },
    ],
    detailFields: ["code", "name", "branchName", "shiftWindow", "breakMinutes", "workHours", "lateToleranceMinutes", "earlyLeaveToleranceMinutes", "overtimeAfterMinutes", "mealAllowance", "nightAllowance", "overnightLabel", "assignmentCount", "note", "createdDateTime", "updatedDateTime"],
  },
  "staff-shift-assignments": {
    key: "staff-shift-assignments",
    title: "Phân ca nhân viên",
    subtitle: "Gán ca cố định / ca xoay cho nhân viên, hỗ trợ không thời hạn và đối soát trạng thái đang làm.",
    searchPlaceholder: "Tìm nhân viên, mã phân ca, mã ca",
    endpoint: "/staff-shift-assignments",
    permissionPrefix: "staff-shift-assignments",
    columns: [
      { key: "staffName", label: "Nhân viên", minWidth: 170 },
      { key: "branchName", label: "Chi nhánh", minWidth: 120 },
      { key: "shiftPatternLabel", label: "Lịch ca", minWidth: 250, wrap: true, multiline: true },
      { key: "rotationLabel", label: "Kiểu phân ca", minWidth: 120 },
      { key: "rotationCycleLabel", label: "Chu kỳ xoay", minWidth: 130 },
      { key: "effectiveRange", label: "Hiệu lực", minWidth: 150 },
      { key: "currentShiftName", label: "Ca hiện tại", minWidth: 140 },
      { key: "currentShiftStatus", label: "Trạng thái", type: "status", minWidth: 120, align: "center" },
    ],
    filters: [
      branchField,
      {
        name: "status",
        label: "Trạng thái",
        type: "select",
        options: [
          { label: "Đang làm", value: "WORKING" },
          { label: "Đi muộn", value: "LATE" },
          { label: "Chưa vào ca", value: "NOT_CHECKED_IN" },
          { label: "Sắp tới", value: "UPCOMING" },
          { label: "Đã xong", value: "COMPLETED" },
          { label: "Thiếu checkout", value: "MISSING_CHECKOUT" },
          { label: "Vắng mặt", value: "ABSENT" },
          { label: "Quá hạn", value: "EXPIRED" },
        ],
      },
    ],
    fields: [
      branchField,
      { name: "code", label: "Mã phân ca", type: "text", placeholder: "Tự động lấy theo ca đã chọn" },
      { name: "name", label: "Tên phân ca", type: "text", placeholder: "Tự động lấy theo ca đã chọn" },
      { name: "userIds", label: "Nhân viên", type: "select", required: true, multiple: true, createOnly: true, optionsEndpoint: "/users", optionLabelKey: "staffOptionLabel", optionValueKey: "id" },
      { name: "userId", label: "Nhân viên", type: "select", required: true, editOnly: true, optionsEndpoint: "/users", optionLabelKey: "staffOptionLabel", optionValueKey: "id" },
      { name: "shiftIds", label: "Danh sách ca", type: "select", required: true, multiple: true, optionsEndpoint: "/staff-shifts", optionLabelKey: "name", optionValueKey: "id", span: 2 },
      { name: "rotationCycleDays", label: "Chu kỳ xoay ca (ngày)", type: "number", placeholder: "1" },
      {
        name: "isUnlimitedRotation",
        label: "Ca xoay không thời hạn",
        type: "select",
        options: [
          { label: "Không", value: "false" },
          { label: "Có", value: "true" },
        ],
      },
      { name: "note", label: "Ghi chú", type: "textarea", span: 2 },
    ],
    detailFields: ["code", "name", "staffName", "staffCode", "attendanceCode", "branchName", "shiftPatternLabel", "rotationLabel", "rotationCycleLabel", "rotationCycleDays", "includeAllShiftsLabel", "effectiveRange", "currentShiftCode", "currentShiftName", "currentShiftWindow", "currentShiftStatus", "firstCheckInAt", "lastCheckOutAt", "workedHours", "lateMinutes", "earlyLeaveMinutes", "overtimeMinutes", "note", "createdDateTime", "updatedDateTime"],
  },
  "staff-attendance-events": {
    key: "staff-attendance-events",
    title: "Dieu chinh cham cong",
    subtitle: "Bang su kien vao/ra cua nhan vien, ho tro them sua xoa va audit lich su dieu chinh cong.",
    endpoint: "/staff-attendance-events",
    permissionPrefix: "staff-attendance-events",
    columns: [
      { key: "eventDate", label: "Ngay", type: "date", minWidth: 110 },
      { key: "eventTime", label: "Gio", minWidth: 82, align: "center" },
      { key: "staffName", label: "Nhan vien", minWidth: 170 },
      { key: "branchName", label: "Chi nhanh", minWidth: 140 },
      { key: "eventType", label: "Loai su kien", type: "status", minWidth: 118, align: "center" },
      { key: "source", label: "Nguon", type: "status", minWidth: 108, align: "center" },
      { key: "verificationMethod", label: "Xac thuc", type: "status", minWidth: 118, align: "center" },
      { key: "machineName", label: "May cham cong", minWidth: 150 },
      { key: "note", label: "Ghi chu", minWidth: 240 },
    ],
    filters: [
      branchField,
      { name: "eventType", label: "Loai su kien", type: "select", options: [{ label: "Check-in", value: "CHECK_IN" }, { label: "Check-out", value: "CHECK_OUT" }] },
      { name: "source", label: "Nguon", type: "select", options: [{ label: "May", value: "MACHINE" }, { label: "Thu cong", value: "MANUAL" }, { label: "Import", value: "IMPORT" }] },
      { name: "dateFrom", label: "Tu ngay", type: "date" },
      { name: "dateTo", label: "Den ngay", type: "date" },
    ],
    fields: [
      branchField,
      { name: "userId", label: "Nhan vien", type: "select", required: true, optionsEndpoint: "/users", optionLabelKey: "staffOptionLabel", optionValueKey: "id" },
      { name: "attendanceMachineId", label: "May cham cong", type: "select", optionsEndpoint: "/attendance-machines", optionLabelKey: "name", optionValueKey: "id" },
      { name: "eventAt", label: "Thoi diem", type: "datetime", required: true },
      { name: "eventType", label: "Loai su kien", type: "select", required: true, options: [{ label: "Check-in", value: "CHECK_IN" }, { label: "Check-out", value: "CHECK_OUT" }] },
      { name: "source", label: "Nguon du lieu", type: "select", required: true, options: [{ label: "Thu cong", value: "MANUAL" }, { label: "May", value: "MACHINE" }, { label: "Import", value: "IMPORT" }] },
      { name: "verificationMethod", label: "Phuong thuc xac thuc", type: "select", options: [{ label: "Manual", value: "MANUAL" }, { label: "Fingerprint", value: "FINGERPRINT" }, { label: "Face", value: "FACE" }, { label: "Card", value: "CARD" }, { label: "Mobile", value: "MOBILE" }] },
      { name: "rawCode", label: "Ma cham cong", type: "text", placeholder: "Tu dong lay theo username neu de trong" },
      { name: "note", label: "Ly do / ghi chu", type: "textarea", span: 2, required: true, placeholder: "Mo ta ly do dieu chinh cong de audit sau nay" },
    ],
    detailFields: ["staffName", "staffCode", "attendanceCode", "branchName", "eventDateTime", "eventType", "source", "verificationMethod", "machineName", "rawCode", "note", "createdDateTime", "updatedDateTime"],
  },
  "customer-groups": {
    key: "customer-groups",
    title: "Nhom khach hang",
    subtitle: "Danh muc phan nhom hoi vien, VIP va doanh nghiep.",
    endpoint: "/customer-groups",
    permissionPrefix: "customer-groups",
    columns: [{ key: "code", label: "Ma" }, { key: "name", label: "Ten nhom" }, { key: "description", label: "Mo ta" }],
    filters: [],
    fields: [{ name: "code", label: "Ma", type: "text", required: true }, { name: "name", label: "Ten nhom", type: "text", required: true }, { name: "description", label: "Mo ta", type: "textarea", span: 2 }],
    detailFields: ["code", "name", "description"],
  },
  "customer-sources": {
    key: "customer-sources",
    title: "Nguon khach hang",
    subtitle: "Danh muc nguon khach tu lead, referral, walk-in, social va ads.",
    endpoint: "/customer-sources",
    permissionPrefix: "customer-sources",
    columns: [{ key: "code", label: "Ma nguon" }, { key: "name", label: "Ten nguon" }, { key: "channel", label: "Nhom kenh" }],
    filters: [],
    fields: [{ name: "code", label: "Ma nguon", type: "text", required: true }, { name: "name", label: "Ten nguon", type: "text", required: true }, { name: "channel", label: "Nhom kenh", type: "text" }, { name: "description", label: "Mo ta", type: "textarea", span: 2 }],
    detailFields: ["code", "name", "channel", "description"],
  },
  "product-groups": {
    key: "product-groups",
    title: "Nhom hang / cap phat",
    subtitle: "Danh muc nhom hang dung chung cho Pro Shop va khan / vat tu dich vu theo chi nhanh.",
    searchPlaceholder: "Tim ten nhom, mo ta, chi nhanh",
    createLabel: "Them nhom hang",
    emptyStateTitle: "Chua co nhom hang",
    emptyStateDescription: "Tao nhom hang truoc, sau do quay lai man hinh Khan tap / vat tu hoac Pro Shop de gan cho tung mat hang.",
    endpoint: "/product-groups",
    permissionPrefix: "product-groups",
    columns: [
      { key: "name", label: "Ten nhom" },
      { key: "usageType", label: "Loai vat tu" },
      { key: "branchName", label: "Chi nhanh" },
      { key: "description", label: "Mo ta" },
    ],
    filters: [
      branchField,
      { name: "usageType", label: "Loai vat tu", type: "select", options: [...productUsageTypeOptions] },
    ],
    fields: [
      branchField,
      { name: "name", label: "Ten nhom", type: "text", required: true, placeholder: "Vi du: Towel Service, Accessory..." },
      { name: "usageType", label: "Loai vat tu", type: "select", required: true, options: [...productUsageTypeOptions] },
      { name: "description", label: "Mo ta", type: "textarea", span: 2, placeholder: "Mo ta nhanh cach su dung nhom hang nay" },
    ],
    detailFields: ["name", "usageType", "branchName", "description", "createdDateTime", "updatedDateTime"],
  },
  "member-presence": {
    key: "member-presence",
    title: "Xac nhan dang tap",
    subtitle: "Theo doi hoi vien dang tap, off, qua ngay va bam xac nhan truc tiep tai quay / module check-in.",
    searchPlaceholder: "Tim ma, ten hoi vien, so dien thoai, ma cham cong",
    endpoint: "/member-presence",
    permissionPrefix: "member-presence",
    allowCreate: false,
    allowEdit: false,
    allowDelete: false,
    columns: [
      { key: "customerInfo", label: "Hoi vien", minWidth: 220, wrap: true, multiline: true },
      { key: "membershipStatus", label: "Ky hoi vien", type: "status", minWidth: 120, align: "center" },
      { key: "branchName", label: "Chi nhanh", minWidth: 120 },
      { key: "attendanceCode", label: "Ma cham cong", minWidth: 110, align: "center" },
      { key: "presenceStatus", label: "Trang thai", type: "status", minWidth: 120, align: "center" },
      { key: "endTrainingDate", label: "Het han goi", type: "date", minWidth: 120, align: "center" },
      { key: "currentSessionDurationLabel", label: "Dang tap", minWidth: 90, align: "center" },
      { key: "nextAutoCloseAt", label: "Moc qua ngay", type: "date", minWidth: 110, align: "center" },
      { key: "lastCheckOutAt", label: "Lan off cuoi", type: "date", minWidth: 110, align: "center" },
    ],
    filters: [
      branchField,
      {
        name: "status",
        label: "Trang thai",
        type: "select",
        options: [
          { label: "Dang tap", value: "ACTIVE" },
          { label: "Off", value: "OFF" },
          { label: "Qua ngay", value: "AUTO_CLOSED" },
          { label: "Chua xac nhan", value: "NEVER_CHECKED_IN" },
        ],
      },
    ],
    fields: [],
    detailFields: ["fullName", "code", "branchName", "phone", "attendanceCode", "customerCardNumber", "membershipStatus", "endTrainingDate", "membershipStatusNote", "presenceStatus", "currentSessionStartedAt", "currentSessionDurationLabel", "nextAutoCloseAt", "lastCheckOutAt", "presenceStatusNote", "lastPresenceAt"],
  },
  "audit-logs": {
    key: "audit-logs",
    title: "Lich su thao tac",
    subtitle: "Lich su thao tac, dang nhap, xuat file va cap nhat cau hinh he thong.",
    endpoint: "/audit-logs",
    permissionPrefix: "audit-logs",
    columns: [
      { key: "module", label: "Mo-dun" },
      { key: "action", label: "Hanh dong", type: "status" },
      { key: "entityType", label: "Doi tuong" },
      { key: "entityId", label: "Ma tham chieu" },
      { key: "createdAt", label: "Thoi gian", type: "date" },
    ],
    filters: [{ name: "dateFrom", label: "Tu ngay", type: "date" }, { name: "dateTo", label: "Den ngay", type: "date" }],
    fields: [],
    detailFields: ["module", "action", "entityType", "entityId", "ipAddress", "userAgent"],
  },
};

const contractStatusOptions = [
  { label: "Draft", value: "DRAFT" },
  { label: "Active", value: "ACTIVE" },
  { label: "Paused", value: "PAUSED" },
  { label: "Expired", value: "EXPIRED" },
  { label: "Cancelled", value: "CANCELLED" },
] as const;

const membershipStatusOptions = [
  { label: "Active", value: "ACTIVE" },
  { label: "Prospect", value: "PROSPECT" },
  { label: "Inactive", value: "INACTIVE" },
  { label: "Suspended", value: "SUSPENDED" },
  { label: "Expired", value: "EXPIRED" },
] as const;

const leadStatusOptions = [
  { label: "Moi", value: "NEW" },
  { label: "Tu van", value: "CONSULTING" },
  { label: "Da hen", value: "APPOINTED" },
  { label: "Bao gia", value: "QUOTED" },
  { label: "Da chuyen doi", value: "CONVERTED" },
  { label: "Huy", value: "CANCELLED" },
] as const;

const userStatusOptions = [
  { label: "Active", value: "ACTIVE" },
  { label: "Locked", value: "LOCKED" },
] as const;

const productStatusOptions = [
  { label: "Active", value: "ACTIVE" },
  { label: "Inactive", value: "INACTIVE" },
] as const;

const paymentProcessingStatusOptions = [
  { label: "Completed", value: "COMPLETED" },
  { label: "Pending", value: "PENDING" },
] as const;

const lockerStatusOptions = [
  { label: "Empty", value: "EMPTY" },
  { label: "Rented", value: "RENTED" },
  { label: "Locked", value: "LOCKED" },
  { label: "Maintenance", value: "MAINTENANCE" },
] as const;

const lockerRentalStatusOptions = [
  { label: "Dang thue", value: "ACTIVE" },
  { label: "Da tra", value: "RETURNED" },
  { label: "Qua han", value: "OVERDUE" },
  { label: "Da huy", value: "CANCELLED" },
] as const;

const attendanceMachineStatusOptions = [
  { label: "Connected", value: "CONNECTED" },
  { label: "Disconnected", value: "DISCONNECTED" },
  { label: "Syncing", value: "SYNCING" },
  { label: "Error", value: "ERROR" },
] as const;

const attendanceMachineVendorOptions = [
  { label: "Generic", value: "GENERIC" },
  { label: "ZKTeco", value: "ZKTECO" },
  { label: "Hikvision", value: "HIKVISION" },
  { label: "Suprema", value: "SUPREMA" },
  { label: "Anviz", value: "ANVIZ" },
  { label: "Ronald Jack", value: "RONALD_JACK" },
] as const;

const attendanceMachineTypeOptions = [
  { label: "Van tay", value: "FINGERPRINT" },
  { label: "Khuon mat", value: "FACE" },
  { label: "The", value: "CARD" },
  { label: "Hybrid", value: "HYBRID" },
] as const;

const attendanceMachineProtocolOptions = [
  { label: "Generic export", value: "GENERIC_EXPORT" },
  { label: "CSV import", value: "CSV_IMPORT" },
  { label: "ZKTeco pull TCP", value: "ZK_PULL_TCP" },
  { label: "ZKTeco ADMS push", value: "ZK_ADMS_PUSH" },
  { label: "Hikvision ISAPI", value: "HIKVISION_ISAPI" },
  { label: "Suprema BioStar", value: "SUPREMA_BIOSTAR" },
  { label: "Generic HTTP", value: "GENERIC_HTTP" },
] as const;

const staffAttendanceEventTypeOptions = [
  { label: "Check-in", value: "CHECK_IN" },
  { label: "Check-out", value: "CHECK_OUT" },
] as const;

const staffAttendanceSourceOptions = [
  { label: "May", value: "MACHINE" },
  { label: "Thu cong", value: "MANUAL" },
  { label: "Import", value: "IMPORT" },
] as const;

const customerManagementFilters: ResourceDefinition["filters"] = [
  branchField,
  { name: "status", label: "Trang thai", type: "select", options: [...membershipStatusOptions] },
  { name: "dateFrom", label: "Tu ngay", type: "date" },
  { name: "dateTo", label: "Den ngay", type: "date" },
];

const leadManagementFilters: ResourceDefinition["filters"] = [
  branchField,
  { name: "status", label: "Trang thai", type: "select", options: [...leadStatusOptions] },
  { name: "dateFrom", label: "Tu ngay", type: "date" },
  { name: "dateTo", label: "Den ngay", type: "date" },
];

const userManagementFilters: ResourceDefinition["filters"] = [
  branchField,
  { name: "status", label: "Trang thai", type: "select", options: [...userStatusOptions] },
];

const trainerCatalogFilters: ResourceDefinition["filters"] = [
  branchField,
  { name: "status", label: "Trang thai", type: "select", options: [...productStatusOptions] },
];

const productCatalogFilters: ResourceDefinition["filters"] = [
  branchField,
  { name: "status", label: "Trang thai", type: "select", options: [...productStatusOptions] },
  { name: "usageType", label: "Loai vat tu", type: "select", options: [...productUsageTypeOptions] },
];

const supplierCatalogFilters: ResourceDefinition["filters"] = [branchField];

const purchaseOrderManagementFilters: ResourceDefinition["filters"] = [
  branchField,
  {
    name: "status",
    label: "Trang thai",
    type: "select",
    options: [
      { label: "Draft", value: "DRAFT" },
      { label: "Pending", value: "PENDING" },
      { label: "Completed", value: "COMPLETED" },
      { label: "Cancelled", value: "CANCELLED" },
    ],
  },
  { name: "dateFrom", label: "Tu ngay", type: "date" },
  { name: "dateTo", label: "Den ngay", type: "date" },
];

const paymentVoucherFilters: ResourceDefinition["filters"] = [
  branchField,
  { name: "status", label: "Trang thai", type: "select", options: [...paymentProcessingStatusOptions] },
  { name: "dateFrom", label: "Tu ngay", type: "date" },
  { name: "dateTo", label: "Den ngay", type: "date" },
];

const lockerManagementFilters: ResourceDefinition["filters"] = [
  branchField,
  { name: "status", label: "Trang thai", type: "select", options: [...lockerStatusOptions] },
];

const lockerRentalManagementFilters: ResourceDefinition["filters"] = [
  branchField,
  { name: "status", label: "Trang thai thue", type: "select", options: [...lockerRentalStatusOptions] },
  { name: "dateFrom", label: "Tu ngay", type: "date" },
  { name: "dateTo", label: "Den ngay", type: "date" },
];

const staffAttendanceAdjustmentFilters: ResourceDefinition["filters"] = [
  branchField,
  { name: "userId", label: "Nhan vien", type: "select", optionsEndpoint: "/users", optionLabelKey: "staffOptionLabel", optionValueKey: "id" },
  { name: "eventType", label: "Loai su kien", type: "select", options: [...staffAttendanceEventTypeOptions] },
  { name: "source", label: "Nguon", type: "select", options: [...staffAttendanceSourceOptions] },
  { name: "dateFrom", label: "Tu ngay", type: "date" },
  { name: "dateTo", label: "Den ngay", type: "date" },
];

const auditLogFilters: ResourceDefinition["filters"] = [
  branchField,
  {
    name: "status",
    label: "Hanh dong",
    type: "select",
    options: [
      { label: "Create", value: "CREATE" },
      { label: "Update", value: "UPDATE" },
      { label: "Delete", value: "DELETE" },
      { label: "Login", value: "LOGIN" },
      { label: "Export", value: "EXPORT" },
      { label: "Check in", value: "CHECK_IN" },
    ],
  },
  {
    name: "entityType",
    label: "Doi tuong",
    type: "select",
    options: [
      { label: "Hoi vien", value: "customer" },
      { label: "Lead", value: "lead" },
      { label: "Hop dong", value: "contract" },
      { label: "Phieu thu", value: "receipt" },
      { label: "Phieu chi", value: "expense" },
      { label: "Phieu nhap", value: "purchase_order" },
      { label: "Buoi tap", value: "training_session" },
      { label: "May cham cong", value: "attendance_machine" },
      { label: "Nguoi dung", value: "user" },
      { label: "Lich su thao tac", value: "audit_log" },
    ],
  },
  { name: "dateFrom", label: "Tu ngay", type: "date" },
  { name: "dateTo", label: "Den ngay", type: "date" },
];

const contractManagementFilters: ResourceDefinition["filters"] = [
  branchField,
  { name: "status", label: "Trang thai", type: "select", options: [...contractStatusOptions] },
  {
    name: "paymentStatus",
    label: "Thanh toan",
    type: "select",
    options: [
      { label: "Unpaid", value: "UNPAID" },
      { label: "Partial", value: "PARTIAL" },
      { label: "Paid", value: "PAID" },
      { label: "Refunded", value: "REFUNDED" },
    ],
  },
  { name: "dateFrom", label: "Tu ngay", type: "date" },
  { name: "dateTo", label: "Den ngay", type: "date" },
];

const serviceCatalogFilters: ResourceDefinition["filters"] = [
  branchField,
  { name: "status", label: "Trang thai", type: "select", options: [{ label: "Active", value: "ACTIVE" }, { label: "Inactive", value: "INACTIVE" }] },
  {
    name: "category",
    label: "Nhom",
    type: "select",
    options: [
      { label: "Membership", value: "membership" },
      { label: "Training", value: "training" },
      { label: "Class", value: "class" },
    ],
  },
];

const servicePackageCatalogFilters: ResourceDefinition["filters"] = [
  branchField,
  { name: "status", label: "Trang thai", type: "select", options: [{ label: "Active", value: "ACTIVE" }, { label: "Inactive", value: "INACTIVE" }] },
  {
    name: "packageType",
    label: "Loai goi",
    type: "select",
    options: [
      { label: "Membership", value: "membership" },
      { label: "PT", value: "pt" },
      { label: "Class", value: "class" },
    ],
  },
];

const trainingScheduleFilters: ResourceDefinition["filters"] = [
  branchField,
  {
    name: "status",
    label: "Trang thai",
    type: "select",
    options: [
      { label: "Scheduled", value: "SCHEDULED" },
      { label: "Checked in", value: "CHECKED_IN" },
      { label: "Completed", value: "COMPLETED" },
      { label: "Missed", value: "MISSED" },
      { label: "Cancelled", value: "CANCELLED" },
    ],
  },
  { name: "dateFrom", label: "Tu ngay", type: "date" },
  { name: "dateTo", label: "Den ngay", type: "date" },
];

const penaltyHistoryFilters: ResourceDefinition["filters"] = [
  branchField,
  {
    name: "status",
    label: "Hanh dong",
    type: "select",
    options: [
      { label: "Update", value: "UPDATE" },
      { label: "Check in", value: "CHECK_IN" },
      { label: "Create", value: "CREATE" },
      { label: "Delete", value: "DELETE" },
      { label: "Approve", value: "APPROVE" },
    ],
  },
  { name: "dateFrom", label: "Tu ngay", type: "date" },
  { name: "dateTo", label: "Den ngay", type: "date" },
];

export { attendanceMachineProtocolOptions, attendanceMachineStatusOptions, attendanceMachineTypeOptions, attendanceMachineVendorOptions, auditLogFilters, branchField, contractManagementFilters, contractStatusOptions, customerManagementFilters, leadManagementFilters, leadStatusOptions, lockerManagementFilters, lockerRentalManagementFilters, lockerStatusOptions, marketingChannelOptions, membershipStatusOptions, paymentProcessingStatusOptions, paymentVoucherFilters, penaltyHistoryFilters, productCatalogFilters, productStatusOptions, purchaseOrderManagementFilters, roundingModeOptions, serviceCatalogFilters, servicePackageCatalogFilters, staffAttendanceAdjustmentFilters, staffAttendanceEventTypeOptions, staffAttendanceSourceOptions, supplierCatalogFilters, trainerCatalogFilters, trainingScheduleFilters, userManagementFilters, userStatusOptions };
