import { SettingDefinition } from "@/types/portal";
import { branchField } from "@/lib/resource-registry";
import { socialHubSettingKey, socialLinkCenterSettingKey, socialModuleCatalog } from "@/lib/social-module-config";

const optionalSettingBranchField = {
  ...branchField,
  required: false,
} as const;

const marketingChannelOptions = [
  { label: "Zalo", value: "ZALO" },
  { label: "SMS", value: "SMS" },
  { label: "Email", value: "EMAIL" },
] as const;

const roundingModeOptions = [{ label: "Gan nhat", value: "NEAREST" }] as const;
const onOffOptions = [
  { label: "Bat", value: "true" },
  { label: "Tat", value: "false" },
] as const;
const socialConnectionModeOptions = [
  { label: "API / App", value: "API" },
  { label: "Webhook", value: "WEBHOOK" },
  { label: "Business / OA", value: "BUSINESS" },
  { label: "Bot / Agent", value: "BOT" },
] as const;
const socialPhoneFirstSettingKeys = new Set([
  "social-zalo-oa",
  "social-whatsapp",
  "social-wechat",
  "social-telegram",
  "social-viber",
  "social-line",
  "social-kakaotalk",
  "social-signal",
]);
const socialBasicCodeFieldMap: Partial<Record<(typeof socialModuleCatalog)[number]["settingKey"], { label: string; description: string }>> = {
  "social-zalo-oa": {
    label: "Ma Zalo / official account",
    description: "Nhap ma Zalo OA neu doi van hanh dang co san. He thong se tu lien ket vao cac truong ky thuat ben duoi.",
  },
  "social-line": {
    label: "Ma OA / ma channel",
    description: "Nhap ma channel neu doi van hanh dang co san. Phan webhook va secret he thong tu quan ly.",
  },
  "social-wechat": {
    label: "Ma official account",
    description: "Ma official account neu doi van hanh dang co san. Cac thong so ky thuat khac de he thong tu quan ly.",
  },
};

const buildSocialSettingDefinition = (platform: (typeof socialModuleCatalog)[number]): SettingDefinition => {
  const basicCodeField = socialBasicCodeFieldMap[platform.settingKey];
  const isPhoneFirst = socialPhoneFirstSettingKeys.has(platform.settingKey);
  return {
  key: platform.settingKey,
  title: platform.title,
  subtitle: platform.subtitle,
  endpoint: `/settings/${platform.settingKey}`,
  fields: [
    optionalSettingBranchField,
    {
      name: "isActive",
      label: "Bat kenh",
      type: "select",
      section: "Trang thai",
      options: [...onOffOptions],
      description: `Bat / tat cau hinh ${platform.title} ma khong can xoa token.`,
    },
    {
      name: "connectionMode",
      label: "Che do ket noi",
      type: "select",
      section: "Nang cao",
      advanced: true,
      autoManaged: true,
      options: [...socialConnectionModeOptions],
      description: "He thong tu de xuat mode phu hop. Chi doi khi ky thuat vien can can thiep.",
    },
    {
      name: "accountLabel",
      label: "Ten tai khoan / kenh",
      type: "text",
      section: "Kenh",
      description: `VD: ${platform.title} VNChoice Ho Tro Khach Hang. Day la ten de doi chieu trong noi bo.`,
    },
    {
      name: "accountId",
      label: basicCodeField?.label || "Ma tai khoan / profile",
      type: "text",
      section: basicCodeField ? "Dang nhap" : "Nang cao",
      advanced: !basicCodeField,
      description:
        basicCodeField?.description ||
        "Ma ky thuat cua page / OA / business account. Thuong ky thuat vien se bo sung neu provider yeu cau.",
    },
    {
      name: "username",
      label: "User / handle / ten dang nhap",
      type: "text",
      section: "Dang nhap",
      description: "VD: @vnchoicegym, @vnchoice.support, ten account van hanh hoac handle hien thi.",
    },
    {
      name: "pageName",
      label: "Ten page / OA / phong chat",
      type: "text",
      section: "Kenh",
      description: "Ten hien thi cho page, group, server, channel hoac official account.",
    },
    {
      name: "pageId",
      label: "Ma page / OA / kenh (ky thuat)",
      type: "text",
      section: "Nang cao",
      advanced: true,
      description: "Ma ky thuat cua page, OA, room hay channel. Thuong do ky thuat vien xu ly.",
    },
    {
      name: "phoneNumber",
      label: "So dien thoai / sender / so nhan OTP",
      type: "text",
      section: isPhoneFirst ? "Dang nhap" : "Kenh",
      description: "So van hanh gan voi kenh nhan tin. Dung de doi chieu nhanh trong noi bo.",
    },
    {
      name: "phoneNumberId",
      label: "Phone number ID (ky thuat)",
      type: "text",
      section: "Nang cao",
      advanced: true,
      description: "Ma ky thuat cua so WhatsApp Business. He thong uu tien ky thuat vien cau hinh mot lan.",
    },
    {
      name: "businessAccountId",
      label: "Business / WABA ID (ky thuat)",
      type: "text",
      section: "Nang cao",
      advanced: true,
      description: "Ma business account / WABA neu provider tach rieng.",
    },
    {
      name: "appId",
      label: "App ID / Client ID",
      type: "text",
      section: "Nang cao",
      advanced: true,
      description: "Thong tin app do ky thuat vien dang ky voi nen tang.",
    },
    {
      name: "appSecret",
      label: "Khoa ung dung / client secret",
      type: "password",
      sensitive: true,
      section: "Nang cao",
      advanced: true,
      description: "Khoa bao mat cua provider. He thong se an gia tri va tu giu noi bo.",
    },
    {
      name: "accessToken",
      label: "Mat khau / ma ket noi",
      type: "password",
      sensitive: true,
      span: 2,
      section: "Dang nhap",
      description: "Nhap ma ket noi, token dang nhap, bot token hoac mat khau ma kenh dang su dung de ket noi.",
    },
    {
      name: "refreshToken",
      label: "Refresh token",
      type: "password",
      sensitive: true,
      span: 2,
      section: "Nang cao",
      advanced: true,
      description: "Token gia han neu kenh yeu cau refresh access token dinh ky.",
    },
    {
      name: "apiUrl",
      label: "API / endpoint URL",
      type: "text",
      span: 2,
      section: "Nang cao",
      advanced: true,
      autoManaged: true,
      description: "Dia chi API goc. He thong se tu de xuat khi co quy uoc san.",
    },
    {
      name: "webhookUrl",
      label: "Webhook URL",
      type: "text",
      span: 2,
      section: "Nang cao",
      advanced: true,
      autoManaged: true,
      readOnly: true,
      description: `He thong tu sinh URL webhook cho ${platform.title}. Ky thuat vien chi copy khi can ket noi voi provider.`,
    },
    {
      name: "webhookVerifyToken",
      label: "Ma xac minh webhook",
      type: "password",
      sensitive: true,
      section: "Nang cao",
      advanced: true,
      autoManaged: true,
      readOnly: true,
      description: "He thong tu sinh ma xac minh callback. Nguoi van hanh khong can tu nhap.",
    },
    {
      name: "webhookSecret",
      label: "Ma bao mat webhook",
      type: "password",
      sensitive: true,
      section: "Nang cao",
      advanced: true,
      autoManaged: true,
      readOnly: true,
      description: "He thong tu sinh khoa chu ky de xac minh webhook va an lai khi tai trang.",
    },
    {
      name: "callbackUrl",
      label: "Callback / redirect URL",
      type: "text",
      span: 2,
      section: "Nang cao",
      advanced: true,
      autoManaged: true,
      readOnly: true,
      description: "URL callback OAuth / redirect. He thong tu tao san khi can.",
    },
    {
      name: "syncMessages",
      label: "Dong bo tin nhan",
      type: "select",
      section: "Van hanh",
      options: [...onOffOptions],
      description: "Dong bo message / DM / inbox vao hub xu ly hoi thoai.",
    },
    {
      name: "syncComments",
      label: "Dong bo comment / mention",
      type: "select",
      section: "Van hanh",
      options: [...onOffOptions],
      description: "Dong bo binh luan, reply, mention hoac tuong tac cong khai ve he thong.",
    },
    {
      name: "contactSyncEnabled",
      label: "Dong bo danh ba / profile",
      type: "select",
      section: "Van hanh",
      options: [...onOffOptions],
      description: "Luu profile / user tu kenh ve CRM de de doi chieu hoi vien / lead.",
    },
    {
      name: "autoReplyEnabled",
      label: "Bat auto reply",
      type: "select",
      section: "Van hanh",
      options: [...onOffOptions],
      description: "Cho phep gui tra loi tu dong khi moi khach nhan tin / de lai tuong tac.",
    },
    {
      name: "leadCaptureEnabled",
      label: "Bat nhan lead",
      type: "select",
      section: "Van hanh",
      options: [...onOffOptions],
      description: "Tu dong tao lead / khach tiem nang tu inbox, comment, form hoac campaign.",
    },
    {
      name: "teamInboxEnabled",
      label: "Bat team inbox / phan tuyen",
      type: "select",
      section: "Van hanh",
      options: [...onOffOptions],
      description: "Phan bo hoi thoai cho sale / CSKH / marketing trong noi bo.",
    },
    {
      name: "defaultOwner",
      label: "Nguoi phu trach mac dinh",
      type: "text",
      section: "Routing",
      description: "Username, ma nhan vien hoac ten nhan vien mac dinh nhan hoi thoai / lead.",
    },
    {
      name: "defaultTag",
      label: "Tag mac dinh",
      type: "text",
      section: "Routing",
      description: "VD: META, SOCIAL, HOT, INBOX-MOI ...",
    },
    {
      name: "greetingTemplate",
      label: "Mau loi chao / mo dau",
      type: "textarea",
      span: 2,
      section: "Template",
      description: "Tin nhan / reply dau tien khi bat dau hoi thoai.",
    },
    {
      name: "autoReplyTemplate",
      label: "Mau auto reply",
      type: "textarea",
      span: 2,
      section: "Template",
      description: "Noi dung tra loi tu dong khi khach de lai comment / inbox ngoai gio.",
    },
    {
      name: "handoffTemplate",
      label: "Mau ban giao agent",
      type: "textarea",
      span: 2,
      section: "Template",
      description: "Thong diep gui khi chuyen hoi thoai sang sale / CSKH phu trach.",
    },
    {
      name: "maxPerDay",
      label: "Quota / ngay",
      type: "number",
      section: "Van hanh",
      description: "So lan dong bo / gui / xu ly toi da trong ngay neu muon quan ly quota noi bo.",
    },
    {
      name: "note",
      label: "Ghi chu",
      type: "textarea",
      span: 2,
      section: "Template",
      description: platform.description,
    },
  ],
  };
};

const socialSettingsRegistry = Object.fromEntries(
  socialModuleCatalog.map((platform) => [platform.settingKey, buildSocialSettingDefinition(platform)]),
) as Record<string, SettingDefinition>;

export const settingsRegistry: Record<string, SettingDefinition> = {
  "program-branding": {
    key: "program-branding",
    title: "Nhan dien chuong trinh",
    subtitle: "Doi ten, logo va thong diep hien thi o man dang nhap.",
    endpoint: "/settings/program-branding",
    ownerOnly: true,
    fields: [
      { name: "brandLabel", label: "Nhan dien ngan", type: "text", section: "Thuong hieu" },
      { name: "appName", label: "Ten chuong trinh", type: "text", required: true, section: "Thuong hieu" },
      { name: "brandDescription", label: "Mo ta ngan", type: "textarea", span: 2, section: "Thuong hieu" },
      { name: "logoUrl", label: "Logo URL", type: "text", span: 2, section: "Logo" },
    ],
    noticeTitle: "Chi danh cho chu he thong",
    noticeDescription: "Module nay anh huong truc tiep den ten va logo hien thi tren man dang nhap cua chuong trinh.",
  },
  company: {
    key: "company",
    title: "Thiet lap cong ty",
    subtitle: "Thong tin doanh nghiep, lien he, logo va chuan hien thi he thong.",
    endpoint: "/settings/company",
    fields: [optionalSettingBranchField, { name: "companyName", label: "Ten cong ty", type: "text", required: true, section: "Ho so cong ty" }, { name: "legalName", label: "Phap nhan / ten xuat hoa don", type: "text", section: "Ho so cong ty" }, { name: "taxCode", label: "Ma so thue", type: "text", section: "Ho so cong ty" }, { name: "hotline", label: "Hotline", type: "phone", section: "Lien he" }, { name: "email", label: "Email cong ty", type: "email", section: "Lien he" }, { name: "website", label: "Website", type: "text", section: "Lien he" }, { name: "address", label: "Dia chi", type: "textarea", span: 2, section: "Lien he" }, { name: "logoUrl", label: "Logo URL", type: "text", span: 2, section: "Nhan dien" }, { name: "timezone", label: "Timezone", type: "text", required: true, section: "He thong" }, { name: "currency", label: "Don vi tien te", type: "text", required: true, section: "He thong" }, { name: "dateFormat", label: "Dinh dang ngay", type: "text", required: true, section: "He thong" }, { name: "uploadLimitMb", label: "Gioi han upload (MB)", type: "number", required: true, section: "He thong" }],
  },
  "e-invoice": {
    key: "e-invoice",
    title: "Thiet lap hoa don dien tu",
    subtitle: "Provider, thong tin xuat hoa don va dia chi nhan thong bao.",
    endpoint: "/settings/e-invoice",
    fields: [optionalSettingBranchField, { name: "provider", label: "Don vi hoa don", type: "text", required: true, section: "Ket noi" }, { name: "isActive", label: "Kich hoat", type: "select", section: "Ket noi", options: [{ label: "Bat", value: "true" }, { label: "Tat", value: "false" }] }, { name: "companyName", label: "Ten don vi", type: "text", section: "Thong tin xuat hoa don" }, { name: "taxCode", label: "Ma so thue", type: "text", section: "Thong tin xuat hoa don" }, { name: "serial", label: "Ky hieu", type: "text", section: "Thong tin xuat hoa don" }, { name: "templateCode", label: "Mau so", type: "text", section: "Thong tin xuat hoa don" }, { name: "issuePrefix", label: "Tien to so hoa don", type: "text", section: "Thong tin xuat hoa don" }, { name: "invoiceEmail", label: "Email nhan hoa don", type: "email", section: "Thong bao" }, { name: "notificationEmails", label: "Email thong bao noi bo", type: "textarea", span: 2, section: "Thong bao" }, { name: "note", label: "Ghi chu", type: "textarea", span: 2, section: "Thong bao" }],
  },
  bank: {
    key: "bank",
    title: "Cau hinh bank",
    subtitle: "Tai khoan nhan tien, noi dung chuyen khoan va template QR.",
    endpoint: "/settings/bank",
    fields: [optionalSettingBranchField, { name: "bankName", label: "Ten ngan hang", type: "text", required: true, section: "Tai khoan" }, { name: "accountName", label: "Chu tai khoan", type: "text", required: true, section: "Tai khoan" }, { name: "accountNumber", label: "So tai khoan", type: "text", required: true, section: "Tai khoan" }, { name: "branchName", label: "Chi nhanh NH", type: "text", section: "Tai khoan" }, { name: "transferContentPrefix", label: "Tien to noi dung CK", type: "text", section: "Thanh toan" }, { name: "qrTemplate", label: "QR template / URL", type: "textarea", span: 2, section: "Thanh toan" }, { name: "isActive", label: "Su dung tai khoan", type: "select", section: "Thanh toan", options: [{ label: "Bat", value: "true" }, { label: "Tat", value: "false" }] }, { name: "note", label: "Ghi chu", type: "textarea", span: 2, section: "Thanh toan" }],
  },
  communication: {
    key: "communication",
    title: "Cau hinh SMS - Email - Zalo",
    subtitle: "Tong quan kenh gui, OTP va quota van hanh theo tung kenh.",
    endpoint: "/settings/communication",
    layout: "communication",
    fields: [],
  },
  [socialHubSettingKey]: {
    key: socialHubSettingKey,
    title: "Tong quan mang xa hoi",
    subtitle: "Quan ly tat ca module social va messaging trong mot khu vuc cau hinh tap trung.",
    endpoint: "/settings/social-hub",
    layout: "social-hub",
    fields: [],
  },
  [socialLinkCenterSettingKey]: {
    key: socialLinkCenterSettingKey,
    title: "Trung tam lien ket thiet bi",
    subtitle: "Tao phien lien ket tu PC bridge, QR / deeplink mobile va browser extension de dung tai khoan dang login san tren thiet bi.",
    endpoint: "/settings/social-link-center",
    layout: "social-link-center",
    fields: [],
  },
  general: {
    key: "general",
    title: "Cau hinh chung",
    subtitle: "Ten he thong, timezone, currency va gioi han upload.",
    endpoint: "/settings/general",
    fields: [
      { name: "appName", label: "Ten he thong", type: "text", required: true, section: "Thong tin chung" },
      { name: "timezone", label: "Timezone", type: "text", required: true, section: "Thong tin chung" },
      { name: "currency", label: "Don vi tien te", type: "text", required: true, section: "Thong tin chung" },
      { name: "dateFormat", label: "Dinh dang ngay", type: "text", required: true, section: "Thong tin chung" },
      { name: "codeGeneration", label: "Sinh ma tu dong", type: "select", required: true, section: "Thong tin chung", options: [{ label: "Bat", value: "true" }, { label: "Tat", value: "false" }] },
      { name: "uploadLimitMb", label: "Upload max MB", type: "number", required: true, section: "Thong tin chung" },
      { name: "memberPresenceOvernightGraceHours", label: "Qua ngay hoi vien (gio)", type: "number", section: "Cham hien dien hoi vien" },
    ],
  },
  sms: {
    key: "sms",
    title: "Cau hinh SMS",
    subtitle: "Provider, sender, quota va template OTP / reminder / birthday.",
    endpoint: "/settings/sms",
    fields: [
      optionalSettingBranchField,
      { name: "isActive", label: "Bat kenh SMS", type: "select", section: "Trang thai", options: [{ label: "Bat", value: "true" }, { label: "Tat", value: "false" }] },
      { name: "provider", label: "Provider", type: "text", required: true, section: "Ket noi" },
      { name: "apiUrl", label: "API URL", type: "text", span: 2, section: "Ket noi" },
      { name: "apiKey", label: "API Key", type: "password", sensitive: true, section: "Ket noi" },
      { name: "secretKey", label: "Secret key", type: "password", sensitive: true, section: "Ket noi" },
      { name: "senderName", label: "Sender", type: "text", section: "Van hanh" },
      { name: "maxPerDay", label: "Quota / ngay", type: "number", section: "Van hanh" },
      { name: "templateOtp", label: "Mau OTP", type: "textarea", span: 2, section: "Template" },
      { name: "templateReminder", label: "Mau nhac lich", type: "textarea", span: 2, section: "Template" },
      { name: "templateBirthday", label: "Mau sinh nhat", type: "textarea", span: 2, section: "Template" },
    ],
  },
  email: {
    key: "email",
    title: "Cau hinh Email",
    subtitle: "SMTP / provider, tai khoan gui va template email van hanh.",
    endpoint: "/settings/email",
    fields: [
      optionalSettingBranchField,
      { name: "isActive", label: "Bat kenh Email", type: "select", section: "Trang thai", options: [{ label: "Bat", value: "true" }, { label: "Tat", value: "false" }] },
      { name: "provider", label: "Provider", type: "text", required: true, section: "Ket noi" },
      { name: "host", label: "SMTP host", type: "text", section: "Ket noi" },
      { name: "port", label: "Port", type: "number", section: "Ket noi" },
      { name: "encryption", label: "Encryption", type: "text", section: "Ket noi" },
      { name: "username", label: "Username", type: "text", section: "Tai khoan gui" },
      { name: "password", label: "Password", type: "password", sensitive: true, section: "Tai khoan gui" },
      { name: "fromName", label: "From name", type: "text", section: "Tai khoan gui" },
      { name: "fromEmail", label: "From email", type: "email", section: "Tai khoan gui" },
      { name: "maxPerDay", label: "Quota / ngay", type: "number", section: "Tai khoan gui" },
      { name: "templateOtp", label: "Mau OTP", type: "textarea", span: 2, section: "Template" },
      { name: "templateBirthday", label: "Mau sinh nhat", type: "textarea", span: 2, section: "Template" },
    ],
  },
  zalo: {
    key: "zalo",
    title: "Cau hinh Zalo",
    subtitle: "OA, access token, OTP login va template tin nhan van hanh.",
    endpoint: "/settings/zalo",
    fields: [
      optionalSettingBranchField,
      { name: "isActive", label: "Bat kenh Zalo", type: "select", section: "Trang thai", options: [{ label: "Bat", value: "true" }, { label: "Tat", value: "false" }] },
      { name: "otpEnabled", label: "Bat OTP login", type: "select", section: "Trang thai", options: [{ label: "Bat", value: "true" }, { label: "Tat", value: "false" }] },
      { name: "oaName", label: "OA name", type: "text", section: "OA / App" },
      { name: "oaId", label: "OA ID", type: "text", section: "OA / App" },
      { name: "appId", label: "App ID", type: "text", section: "OA / App" },
      { name: "appSecret", label: "App secret", type: "password", sensitive: true, section: "OA / App" },
      { name: "apiUrl", label: "ZNS API URL", type: "text", span: 2, section: "OTP" },
      { name: "otpTemplateId", label: "OTP Template ID", type: "text", section: "OTP" },
      { name: "otpTemplateDataKey", label: "Bien OTP", type: "text", section: "OTP" },
      { name: "otpPhoneOverride", label: "So test override", type: "text", section: "OTP" },
      { name: "otpCodeLength", label: "Do dai OTP", type: "number", section: "OTP" },
      { name: "otpTtlMinutes", label: "Hieu luc OTP (phut)", type: "number", section: "OTP" },
      { name: "otpResendCooldownSeconds", label: "Cooldown gui lai (giay)", type: "number", section: "OTP" },
      { name: "otpMaxRetry", label: "So lan sai toi da", type: "number", section: "OTP" },
      { name: "maxPerDay", label: "Quota / ngay", type: "number", section: "Van hanh" },
      { name: "token", label: "Token", type: "password", sensitive: true, span: 2, section: "Van hanh" },
      { name: "refreshToken", label: "Refresh token", type: "password", sensitive: true, span: 2, section: "Van hanh" },
      { name: "templateReminder", label: "Mau nhac lich", type: "textarea", span: 2, section: "Template" },
      { name: "templateBirthday", label: "Mau sinh nhat", type: "textarea", span: 2, section: "Template" },
    ],
  },
  "code-generation": {
    key: "code-generation",
    title: "Cau hinh sinh ma",
    subtitle: "Tien to ma va quy tac dem so cho hoi vien, hop dong, thu chi va san pham.",
    endpoint: "/settings/code-generation",
    fields: [optionalSettingBranchField, { name: "customerPrefix", label: "Tien to khach hang", type: "text", required: true, section: "Tien to ma" }, { name: "leadPrefix", label: "Tien to lead", type: "text", required: true, section: "Tien to ma" }, { name: "contractPrefix", label: "Tien to hop dong", type: "text", required: true, section: "Tien to ma" }, { name: "receiptPrefix", label: "Tien to phieu thu", type: "text", required: true, section: "Tien to ma" }, { name: "expensePrefix", label: "Tien to phieu chi", type: "text", required: true, section: "Tien to ma" }, { name: "sessionPrefix", label: "Tien to buoi tap", type: "text", section: "Tien to ma" }, { name: "productPrefix", label: "Tien to san pham", type: "text", section: "Tien to ma" }, { name: "padLength", label: "So chu so dem", type: "number", required: true, section: "Quy tac" }, { name: "resetByBranch", label: "Dem rieng theo chi nhanh", type: "select", section: "Quy tac", options: [{ label: "Co", value: "true" }, { label: "Khong", value: "false" }] }, { name: "note", label: "Ghi chu", type: "textarea", span: 2, section: "Quy tac" }],
  },
  "print-templates": {
    key: "print-templates",
    title: "Quan ly mau in",
    subtitle: "Header/footer hop dong, phieu thu, phieu chi, ban hang, tra hang va quy tac in mac dinh.",
    endpoint: "/settings/print-templates",
    fields: [
      optionalSettingBranchField,
      {
        name: "printerMode",
        label: "Che do in",
        type: "select",
        section: "Thong so in",
        description: "Web app hien tai van mo hop thoai in cua trinh duyet. Chrome / Edge khong cho web tu doi Destination, vi vay che do may in he thong va may in IP hien tai chi luu cau hinh de dung cho local bridge ve sau.",
        options: [
          { label: "Trinh duyet / hop thoai in (Dang ap dung)", value: "BROWSER_DIALOG" },
          { label: "Nhap ten may in he thong (Chi luu cau hinh)", value: "SYSTEM_NAME" },
          { label: "May in IP / Network (Chi luu cau hinh)", value: "NETWORK_IP" },
        ],
      },
      {
        name: "paperSize",
        label: "Kho giay",
        type: "text",
        section: "Thong so in",
        description: "Neu backend local doc duoc may in da chon, he thong se hien cac kho giay ho tro de chon nhu A4, A3, Letter...",
      },
      {
        name: "paperOrientation",
        label: "Chieu giay",
        type: "select",
        section: "Thong so in",
        description: "Chon huong in doc hoac ngang cho mau in nay.",
        options: [
          { label: "In doc", value: "PORTRAIT" },
          { label: "In ngang", value: "LANDSCAPE" },
        ],
      },
      {
        name: "defaultPrinterName",
        label: "May in ap dung",
        type: "text",
        section: "Thong so in",
        optionsEndpoint: "/settings/system-printers",
        optionLabelKey: "displayName",
        optionValueKey: "name",
        description: "Ten may in nay duoc luu lai trong cau hinh. Web app van mo hop thoai in cua trinh duyet, nen ban van can chon Destination thu cong khi in.",
      },
      {
        name: "printerIpAddress",
        label: "IP / Host may in",
        type: "text",
        section: "Thong so in",
        description: "Dung de luu thong tin may in mang / IP cho local bridge ve sau. Ban than web app khong the gui lenh in truc tiep toi dia chi nay trong hop thoai in cua Chrome / Edge.",
      },
      {
        name: "printerPort",
        label: "Port may in",
        type: "number",
        section: "Thong so in",
        description: "Thuong la 9100 cho RAW, 631 cho IPP, hoac port rieng theo hang may in.",
      },
      {
        name: "printerProtocol",
        label: "Giao thuc may in",
        type: "select",
        section: "Thong so in",
        options: [
          { label: "RAW 9100", value: "RAW_9100" },
          { label: "IPP", value: "IPP" },
          { label: "LPR", value: "LPR" },
        ],
      },
      {
        name: "printerQueueName",
        label: "Queue / Share name",
        type: "text",
        section: "Thong so in",
        description: "Can cho mot so may in LPR/IPP hoac khi in qua share name trong mang noi bo.",
      },
      {
        name: "printerDriverHint",
        label: "Driver / Model goi nho",
        type: "text",
        section: "Thong so in",
        description: "Luu ghi chu ve model, driver, kho giay, cau hinh kho lenh de nhan vien de doi chieu sau nay.",
      },
      {
        name: "showLogo",
        label: "In logo",
        type: "select",
        section: "Thong so in",
        options: [
          { label: "Co", value: "true" },
          { label: "Khong", value: "false" },
        ],
      },
      {
        name: "showSignature",
        label: "In chu ky",
        type: "select",
        section: "Thong so in",
        options: [
          { label: "Co", value: "true" },
          { label: "Khong", value: "false" },
        ],
      },
      { name: "contractHeader", label: "Header hop dong", type: "textarea", span: 2, section: "Noi dung chung" },
      { name: "receiptHeader", label: "Header phieu thu", type: "textarea", span: 2, section: "Phieu thu" },
      { name: "receiptFooter", label: "Footer phieu thu", type: "textarea", span: 2, section: "Phieu thu" },
      { name: "expenseHeader", label: "Header phieu chi", type: "textarea", span: 2, section: "Phieu chi" },
      { name: "expenseFooter", label: "Footer phieu chi", type: "textarea", span: 2, section: "Phieu chi" },
      { name: "salesHeader", label: "Header ban hang", type: "textarea", span: 2, section: "Ban hang" },
      { name: "salesFooter", label: "Footer ban hang", type: "textarea", span: 2, section: "Ban hang" },
      { name: "returnHeader", label: "Header tra hang", type: "textarea", span: 2, section: "Tra hang" },
      { name: "returnFooter", label: "Footer tra hang", type: "textarea", span: 2, section: "Tra hang" },
      { name: "note", label: "Ghi chu chung", type: "textarea", span: 2, section: "Noi dung chung" },
    ],
  },
  "report-templates": {
    key: "report-templates",
    title: "Cau hinh xuat bao cao",
    subtitle: "Designer mau in theo canvas cho tung bao cao, gom bo cuc, header/footer, chu ky va xem truoc ban in.",
    searchPlaceholder: "Tim ten bao cao, ma bao cao, nhom bao cao",
    endpoint: "/settings/report-templates",
    layout: "report-template-manager",
    fields: [
      optionalSettingBranchField,
      { name: "defaultTitle", label: "Tieu de mac dinh", type: "text", required: true, section: "Hien thi" },
      { name: "defaultSubtitle", label: "Mo ta phu", type: "text", section: "Hien thi" },
      { name: "currencyScale", label: "Scale tien te", type: "text", section: "Hien thi" },
      { name: "paperSize", label: "Kho giay", type: "text", section: "Hien thi" },
      {
        name: "defaultOrientation",
        label: "Chieu in",
        type: "select",
        section: "Hien thi",
        options: [
          { label: "Doc", value: "PORTRAIT" },
          { label: "Ngang", value: "LANDSCAPE" },
        ],
      },
      { name: "reportHeader", label: "Header bao cao", type: "textarea", span: 2, section: "Noi dung" },
      { name: "reportFooter", label: "Footer bao cao", type: "textarea", span: 2, section: "Noi dung" },
      {
        name: "showGeneratedBy",
        label: "Hien nguoi xuat",
        type: "select",
        section: "Tuy chon",
        options: [
          { label: "Co", value: "true" },
          { label: "Khong", value: "false" },
        ],
      },
      {
        name: "showPrintedAt",
        label: "Hien thoi gian xuat",
        type: "select",
        section: "Tuy chon",
        options: [
          { label: "Co", value: "true" },
          { label: "Khong", value: "false" },
        ],
      },
      {
        name: "showFilters",
        label: "In bo loc",
        type: "select",
        section: "Tuy chon",
        options: [
          { label: "Co", value: "true" },
          { label: "Khong", value: "false" },
        ],
      },
      {
        name: "showBranchSummary",
        label: "Tong hop chi nhanh",
        type: "select",
        section: "Tuy chon",
        options: [
          { label: "Co", value: "true" },
          { label: "Khong", value: "false" },
        ],
      },
      {
        name: "showSignature",
        label: "In chu ky",
        type: "select",
        section: "Tuy chon",
        options: [
          { label: "Co", value: "true" },
          { label: "Khong", value: "false" },
        ],
      },
      { name: "note", label: "Ghi chu", type: "textarea", span: 2, section: "Tuy chon" },
    ],
  },
  promotions: {
    key: "promotions",
    title: "Chuong trinh khuyen mai",
    subtitle: "Uu dai mac dinh, bonus buoi / ngay va quy tac auto-apply.",
    endpoint: "/settings/promotions",
    fields: [optionalSettingBranchField, { name: "programName", label: "Ten chuong trinh", type: "text", section: "Cau hinh" }, { name: "discountPercent", label: "Giam gia (%)", type: "number", section: "Cau hinh" }, { name: "bonusSessions", label: "Bonus buoi", type: "number", section: "Cau hinh" }, { name: "bonusDays", label: "Bonus ngay", type: "number", section: "Cau hinh" }, { name: "startDate", label: "Ngay bat dau", type: "date", section: "Thoi gian" }, { name: "endDate", label: "Ngay ket thuc", type: "date", section: "Thoi gian" }, { name: "autoApply", label: "Tu dong ap dung", type: "select", section: "Thoi gian", options: [{ label: "Co", value: "true" }, { label: "Khong", value: "false" }] }, { name: "note", label: "Ghi chu", type: "textarea", span: 2, section: "Ghi chu" }],
  },
  "incentive-policy": {
    key: "incentive-policy",
    title: "KPI / Incentive",
    subtitle: "Cau hinh target, % thuong Sale / PT va he so theo nguon khach.",
    endpoint: "/settings/incentive-policy",
    fields: [
      optionalSettingBranchField,
      { name: "salesDefaultTarget", label: "Target Sale mac dinh", type: "currency", section: "Sales KPI", description: "VD: 100000000 = target chung cho sale member trong thang." },
      {
        name: "salesTargetOverrides",
        label: "Override target Sale",
        type: "textarea",
        span: 2,
        section: "Sales KPI",
        description: "Moi dong theo dinh dang MA_NV=200000000 hoac username=200000000. VD: EMP-0002=30000000",
      },
      { name: "salesUnlockPercent", label: "Nguong dat KPI Sale (%)", type: "number", section: "Sales KPI", description: "VD: 100 = dat du target moi duoc tinh thuong." },
      { name: "salesBonusRatePercent", label: "Thuong Sale khi dat (%)", type: "number", section: "Sales KPI", description: "VD: 4 = dat KPI thi thuong 4% tren doanh thu quy doi." },
      { name: "salesSelfSourceWeightPercent", label: "He so nguon tu khai thac Sale (%)", type: "number", section: "Sales nguon khach", description: "VD: 100 = walk-in / referral / tu khai thac an du he so." },
      { name: "salesPaidSourceWeightPercent", label: "He so nguon ads / meta Sale (%)", type: "number", section: "Sales nguon khach", description: "VD: 70 = Meta Ads chi tinh 70% doanh thu vao KPI." },
      { name: "salesOtherSourceWeightPercent", label: "He so nguon khac Sale (%)", type: "number", section: "Sales nguon khach", description: "Danh cho website / online / cac nguon khac neu khong match 2 nhom tren." },
      { name: "ptDefaultTarget", label: "Target PT mac dinh", type: "currency", section: "PT KPI", description: "VD: 50000000 = target doanh thu PT thang." },
      {
        name: "ptTargetOverrides",
        label: "Override target PT",
        type: "textarea",
        span: 2,
        section: "PT KPI",
        description: "Moi dong theo dinh dang MA_PT=50000000 hoac ten=50000000. VD: PT001=60000000",
      },
      { name: "ptSelfSourceWeightPercent", label: "He so nguon tu khai thac PT (%)", type: "number", section: "PT nguon khach", description: "Thuong dung 100 neu PT khong bi chia he so theo nguon." },
      { name: "ptPaidSourceWeightPercent", label: "He so nguon ads / meta PT (%)", type: "number", section: "PT nguon khach", description: "Co the de 100 hoac giam neu PT can chia theo nguon nhu Sale." },
      { name: "ptOtherSourceWeightPercent", label: "He so nguon khac PT (%)", type: "number", section: "PT nguon khach" },
      { name: "ptTier1MinRevenue", label: "Moc 1 tu doanh thu", type: "currency", section: "PT bac thuong", description: "VD: 0" },
      { name: "ptTier1RatePercent", label: "Moc 1 thuong (%)", type: "number", section: "PT bac thuong", description: "VD: 25" },
      { name: "ptTier2MinRevenue", label: "Moc 2 tu doanh thu", type: "currency", section: "PT bac thuong", description: "VD: 30000000" },
      { name: "ptTier2RatePercent", label: "Moc 2 thuong (%)", type: "number", section: "PT bac thuong", description: "VD: 30" },
      { name: "ptTier3MinRevenue", label: "Moc 3 tu doanh thu", type: "currency", section: "PT bac thuong", description: "VD: 60000000" },
      { name: "ptTier3RatePercent", label: "Moc 3 thuong (%)", type: "number", section: "PT bac thuong", description: "VD: 35" },
      { name: "ptTier4MinRevenue", label: "Moc 4 tu doanh thu", type: "currency", section: "PT bac thuong", description: "VD: 100000000" },
      { name: "ptTier4RatePercent", label: "Moc 4 thuong (%)", type: "number", section: "PT bac thuong", description: "VD: 40" },
      {
        name: "selfSourceTokens",
        label: "Tu khoa nguon tu khai thac",
        type: "textarea",
        span: 2,
        section: "Nhan dien nguon",
        description: "He thong doi chieu theo code, ten va channel cua nguon khach. Tach bang dau phay hoac xuong dong. VD: walkin, referral, offline, self",
      },
      {
        name: "paidSourceTokens",
        label: "Tu khoa nguon ads / meta",
        type: "textarea",
        span: 2,
        section: "Nhan dien nguon",
        description: "VD: facebook, meta, ads, tiktok, google, campaign.",
      },
      { name: "note", label: "Ghi chu", type: "textarea", span: 2, section: "Nhan dien nguon", description: "Co the luu cong thuc doi chieu. VD Sale: self 100%, Meta 70%, dat 100% KPI thi an 4%." },
    ],
  },
  "loyalty-points": {
    key: "loyalty-points",
    title: "Quan ly tich diem",
    subtitle: "Ty le tich diem, quy doi diem va diem thuong mac dinh.",
    endpoint: "/settings/loyalty-points",
    fields: [optionalSettingBranchField, { name: "enabled", label: "Bat loyalty", type: "select", section: "Trang thai", options: [{ label: "Bat", value: "true" }, { label: "Tat", value: "false" }] }, { name: "earnRate", label: "So tien / 1 diem", type: "number", section: "Tich diem" }, { name: "redemptionRate", label: "So diem / 1.000 VND", type: "number", section: "Quy doi" }, { name: "expiryDays", label: "Han diem (ngay)", type: "number", section: "Quy doi" }, { name: "minContractAmount", label: "Gia tri HD toi thieu", type: "currency", section: "Dieu kien" }, { name: "welcomePoints", label: "Diem chao mung", type: "number", section: "Dieu kien" }, { name: "note", label: "Ghi chu", type: "textarea", span: 2, section: "Dieu kien" }],
  },
  "loyalty-benefits": {
    key: "loyalty-benefits",
    title: "Uu dai Loyalty",
    subtitle: "Nguong hang thanh vien va uu dai sinh nhat / referral.",
    endpoint: "/settings/loyalty-benefits",
    fields: [optionalSettingBranchField, { name: "silverThreshold", label: "Nguong Silver", type: "number", section: "Hang thanh vien" }, { name: "goldThreshold", label: "Nguong Gold", type: "number", section: "Hang thanh vien" }, { name: "vipThreshold", label: "Nguong VIP", type: "number", section: "Hang thanh vien" }, { name: "birthdayBonusPercent", label: "Bonus sinh nhat (%)", type: "number", section: "Uu dai" }, { name: "referralBonusPoints", label: "Diem thuong gioi thieu", type: "number", section: "Uu dai" }, { name: "benefitNote", label: "Mo ta uu dai", type: "textarea", span: 2, section: "Uu dai" }],
  },
  tags: {
    key: "tags",
    title: "Cau hinh Tag",
    subtitle: "Bo tag mac dinh cho lead nong, cong no, VIP va follow-up qua han.",
    endpoint: "/settings/tags",
    fields: [optionalSettingBranchField, { name: "enableAutoTags", label: "Bat auto tag", type: "select", section: "Quy tac", options: [{ label: "Bat", value: "true" }, { label: "Tat", value: "false" }] }, { name: "leadHotTag", label: "Tag lead nong", type: "text", section: "Bo tag" }, { name: "debtTag", label: "Tag cong no", type: "text", section: "Bo tag" }, { name: "vipTag", label: "Tag VIP", type: "text", section: "Bo tag" }, { name: "overdueFollowUpTag", label: "Tag follow-up qua han", type: "text", section: "Bo tag" }, { name: "note", label: "Ghi chu", type: "textarea", span: 2, section: "Bo tag" }],
  },
  "custom-fields": {
    key: "custom-fields",
    title: "Thiet lap truong du lieu",
    subtitle: "Dinh nghia cac field mo rong cho khach hang, lead va hop dong.",
    endpoint: "/settings/custom-fields",
    fields: [optionalSettingBranchField, { name: "customerFields", label: "Field mo rong khach hang", type: "textarea", span: 2, section: "Khach hang va lead" }, { name: "leadFields", label: "Field mo rong lead", type: "textarea", span: 2, section: "Khach hang va lead" }, { name: "contractFields", label: "Field mo rong hop dong", type: "textarea", span: 2, section: "Hop dong" }, { name: "note", label: "Ghi chu", type: "textarea", span: 2, section: "Hop dong" }],
  },
  marketing: {
    key: "marketing",
    title: "Marketing",
    subtitle: "Tien to campaign, default channel, quota gui va audience rule.",
    endpoint: "/settings/marketing",
    fields: [optionalSettingBranchField, { name: "campaignNamePrefix", label: "Tien to campaign", type: "text", section: "Mac dinh" }, { name: "defaultChannel", label: "Kenh mac dinh", type: "select", section: "Mac dinh", options: [...marketingChannelOptions] }, { name: "dailyQuota", label: "Quota / ngay", type: "number", section: "Mac dinh" }, { name: "allowBulkSend", label: "Cho phep gui hang loat", type: "select", section: "Mac dinh", options: [{ label: "Co", value: "true" }, { label: "Khong", value: "false" }] }, { name: "audienceRule", label: "Audience rule", type: "textarea", span: 2, section: "Audience" }, { name: "note", label: "Ghi chu", type: "textarea", span: 2, section: "Audience" }],
  },
  rounding: {
    key: "rounding",
    title: "Cau hinh lam tron so",
    subtitle: "Quy tac lam tron so tien, thue va so chu so hien thi.",
    endpoint: "/settings/rounding",
    fields: [optionalSettingBranchField, { name: "roundingMode", label: "Che do lam tron", type: "select", section: "Lam tron", options: [...roundingModeOptions] }, { name: "roundingUnit", label: "Don vi lam tron", type: "number", section: "Lam tron" }, { name: "taxRoundingMode", label: "Lam tron thue", type: "select", section: "Lam tron", options: [...roundingModeOptions] }, { name: "displayDecimals", label: "So chu so hien thi", type: "number", section: "Hien thi" }, { name: "note", label: "Ghi chu", type: "textarea", span: 2, section: "Hien thi" }],
  },
  penalty: {
    key: "penalty",
    title: "Thiet lap Penalty",
    subtitle: "Muc phat hu muon, vang mat, PT absent va gioi han phat.",
    endpoint: "/settings/penalty",
    fields: [optionalSettingBranchField, { name: "lateCancelFee", label: "Phi huy muon", type: "currency", section: "Muc phat" }, { name: "noShowFee", label: "Phi vang mat", type: "currency", section: "Muc phat" }, { name: "ptAbsentFee", label: "Phi PT absent", type: "currency", section: "Muc phat" }, { name: "graceMinutes", label: "So phut duoc phep tre", type: "number", section: "Quy tac" }, { name: "maxPenaltyPerDay", label: "Muc phat toi da / ngay", type: "number", section: "Quy tac" }, { name: "note", label: "Ghi chu", type: "textarea", span: 2, section: "Quy tac" }],
  },
  "birthday-template": {
    key: "birthday-template",
    title: "Mau sinh nhat",
    subtitle: "Template gui tin chuc mung sinh nhat cho hoi vien.",
    searchPlaceholder: "Tim ten mau, tieu de, doi tuong gui",
    endpoint: "/settings/birthday-template",
    layout: "template",
    fields: [
      optionalSettingBranchField,
      { name: "name", label: "Ten mau", type: "text", required: true },
      { name: "title", label: "Tieu de", type: "text", required: true },
      { name: "targetType", label: "Doi tuong", type: "text", required: true },
      { name: "channel", label: "Kenh gui", type: "text", required: true },
      { name: "isActive", label: "Kich hoat", type: "select", options: [{ label: "Bat", value: "true" }, { label: "Tat", value: "false" }] },
      { name: "remindDays", label: "So ngay nhac", type: "number" },
      { name: "content", label: "Noi dung", type: "textarea", span: 2, required: true },
    ],
  },
  ...socialSettingsRegistry,
};
